[Feature] 투표하기 API 연동
mash-up-kr/gabbangzip-iOS pull request #106
Opened 2024-08-06 10:19 UTC by hope1053

## 📌 Related Issue
- #100 

## 🚀 Description
투표 관련 API 연동 구현했습니다!

## ✅ Done
- [x] 투표 옵션 불러오기
- [x] 투표 결과 보내기
- [x] 투표 가이드 화면 구현
- [x] 투표 완료 화면 API 연동 및 UI 구현

## 📸 Screenshot
- 투표 가이드 화면

https://github.com/user-attachments/assets/da7a00ee-4b4d-4ad5-837b-5cda1bf1d30e

- 투표 완료 화면
<img width="350" alt="image" src="https://github.com/user-attachments/assets/563078dd-c5d1-47f7-a375-ac4950426296">

## 📢 Notes
Coordinator는 추후 한 번에 작업하도록 하겠습니닷...🫡
 
## 🧪 Testing(optional)

2024-08-06 23:13 UTC, GREENOVER submitted a review, later dismissed
수고하셨습니다~
코멘트는 몇개없지만, 중복되는 부분들이 많아요ㅎㅎ..
그래서 해당 코멘트들 보시고 적용하실거면 해당 스타일로된 다른 코드 부분도 같이 반영해주시면 좋을것 같습니다 👍

2024-08-06 23:13 UTC, GREENOVER commented on Projects/DesignSystem/Project.swift
> +        .project(target: .models, projectPath: .core)
DS에 모델 타겟이 꼭 들어가야하나요?
다른 방법은 없나요?
DS에서 모델을 타입으로 사용하지 않는것이 더 좋을것 같아요.
DS는 모델에 국한된게 아니라, 어떤곳에 들어가도 변형없이 사용할 수 있어야 합니다.
그렇기에, PhotoWithFrame에서 keyword 타입을 GroupDate.keyword로 할것이 아니라 Image 타입으로 제너럴하게 만든 다음 호출하는쪽에서 이미지를 넘겨주는것이 적절할것 같아요.
즉, 해당 타겟들은 의존관계를 맺을 필요가 없고 최대한 아토믹한 타겟들의 의존관계는 지양하는것이 좋을것 같습니다~

2024-08-06 23:13 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteCore.swift
> +          }
작업이 아직 덜된 부분인가요?
아래 catch 다루는 모든 부분 공통 질문입니다~

2024-08-06 23:13 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteCore.swift
> +          mainQueue.schedule(after: .init(.now() + 1.0)) {
이건 단순 궁금증인데요.
딜레이의 의도가 궁금합니다. 🙋🏻
swipeCard 액션 완료 후에 resetButtonState 액션 시작이 될텐데 바로 되면 안되는건지, 1초 딜레이가 필요한 이유가 궁금했어요ㅎㅎ

2024-08-06 23:13 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteGuideView/VoteGuideView.swift
> +      ForEach(0..<guideViews.count, id: \.self) { index in
`ForEach(guideViews, id: \.self)`
요 방법이 성능적인 측면에서 더 유리합니다.
컬렉션 자체를 직접적으로 순회하기 때문에 추가 인덱스 계산이 필요없고 count도 필요없습니다.
또한, 인덱스를 사용하지 않기때문에 범위 조건 오류가 발생되지 않음을 보장할 수 있고 아래에서 바인딩할 필요도 없어요.
특히, SwiftUI에서는 이런 방식이 더 최적화가 잘되있습니다~

2024-08-06 23:13 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteGuideView/VoteGuideView.swift
> +  var guideViews: [GuideView]
GuideType을 받아서, 아래에서 GuideView를 호출해 그려주는게 더 심플하지 않나요?
해당 VoteGuideView를 호출할때 GuideView를 생성하여야 하는 번거로움이 있어보여서요.
또한, 뷰 자체를 변수값으로 들고 있는 자체도 메리트가 없어보입니다.
추후, 만약 GuideView에서 파라미터가 여러개 추가된다면 초기화시에 그만큼 guideViews에 넣어줄것이 많은데 아래 ForEach에서 GuideView를 반복 돌려준다면 더 확장성을 가지게 됩니다.
즉, 현재 방법은 예를들면 SOLID에서 개방폐쇄원칙이 지켜지지 않아 유지보수가 힘듭니다.

2024-08-07 07:35 UTC, zekexros requested changes
투표 화면에 첫 방문 여부를 `userDefault`에 저장하고 사용하는 것은 그 목적을 제대로 달성하지 못할 가능성이 높아보이는데 이미 충분히 인지하고 계신거쬬?(변경해야 한다는 의미는 아니고 단순히 궁금해서 여쭤봅니다🤠)

2024-08-07 07:35 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteCore.swift
> +          }
P5
mainQueue의 `sleep(for:)` 메서드로도 구현할 수 있답니다~

2024-08-07 07:35 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteView.swift
> +        .animation(.easeIn)
P2:
`'animation' was deprecated in iOS 15.0: Use withAnimation or animation(_:value:) instead.`

2024-08-07 15:22 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteCore.swift
> +          }
이 부분 추후 한번에 작업하려고 합니다!

2024-08-07 15:23 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/Vote/VoteCore.swift
> +          mainQueue.schedule(after: .init(.now() + 1.0)) {
기획상 명세가 1초 후 상태를 업데이트해줘야해요!
<img width="437" alt="image" src="https://github.com/user-attachments/assets/d3b32d5a-caed-4c34-9073-ff6ceb40ef65">

2024-08-07 15:43 UTC, hope1053 commented on Projects/DesignSystem/Project.swift
> +        .project(target: .models, projectPath: .core)
저도 해당 부분 개발하면서 뭔가 잘못되고 있다는 느낌이 들긴했었는데....^_^ 말씀해주신 방향으로 수정했습니다!

2024-08-07 16:28 UTC, hope1053 commented
> 투표 화면에 첫 방문 여부를 `userDefault`에 저장하고 사용하는 것은 그 목적을 제대로 달성하지 못할 가능성이 높아보이는데 이미 충분히 인지하고 계신거쬬?(변경해야 한다는 의미는 아니고 단순히 궁금해서 여쭤봅니다🤠)

엇 어떤 부분에서 그런건가요...?! 인지를 못하고 있는 것 같습니다...?😵‍💫

2024-08-08 06:26 UTC, serena0720 approved these changes
고생하셨어용!!👍 소소한 코멘트 있는데 참고만해주세용😆

2024-08-08 06:26 UTC, serena0720 commented on Projects/Core/Services/PicAPIClients/VoteAPI/VoteAPIClient.swift
> +    case getAPIError = 0
P5: 0은 없어도 되지 않나욤?

2024-08-08 12:32 UTC, zekexros approved these changes
![image](https://github.com/user-attachments/assets/5c3140b7-7e74-4bc9-afaa-c980deb694f8)

2024-08-08 13:08 UTC, merged