[Feat] 멤버 리스트 API 연동
mash-up-kr/gabbangzip-iOS pull request #109
Opened 2024-08-08 13:53 UTC by hope1053

## 📌 Related Issue
- #107 

## 🚀 Description
멤버 리스트 API 연동 및 로직 구현했습니다!

## ✅ Done
- [x] 멤버 리스트 API 호출
- [x] 정원 다 찬 경우/그렇지 않은 경우 UI 반영
- [x] 초대 링크 → 코드로 네이밍 변경

## 📸 Screenshot
<img width="408" alt="image" src="https://github.com/user-attachments/assets/316aa9e4-8a81-43b7-b349-bd9cf751a3af">
<img width="400" alt="image" src="https://github.com/user-attachments/assets/f0db849d-31d1-4f5a-a710-e49e439aa641">

## 📢 Notes
 
## 🧪 Testing(optional)

2024-08-08 13:53 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +      memberList.members.count == 4
여기서 그룹 최대정원이 4명인걸 그냥 숫자로 박아놨는데... 어떻게 관리하면 좋을지 고민입니다 🤔.. 좋은 아이디어 있으면 공유 부탁드려요!

2024-08-09 00:21 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +      memberList.members.count == 4
Core말고 MemberList 구조체에서 해당 연산 프로퍼티를 가져가도 좋을것 같습니다.
4인걸 숫자로 박아도 저는 괜찮다고는 생각하는데,
별로시면, 해당 구조체에서 4를 상수로 저장해서 대체해서 쓰는것도 있을것 같아요.
(근데 굳이 그렇게까지 모델타입에서 하는게 오버엔지니어링이라는 생각도 듭니다.)

2024-08-09 00:28 UTC, GREENOVER requested changes
코멘트 몇개 안되지만 최종 점검 부탁드려요~

2024-08-09 00:28 UTC, GREENOVER commented on Projects/Core/Models/Group/Response/MemberList.swift
> +      case members
4칸되있네요ㅠ

2024-08-09 00:28 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +          }, catch: { error, send in }
이건 언제 구현되는건가요~?

2024-08-09 00:28 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +      ForEach(store.memberList.members, id: \.self) { member in
id값으로 Member 객체에 유니크한 id 값이 있던데요~
그거 사용하는게 더 적절합니다.
그 외에도 모든곳에서 self로 사용하고 계시는데 그럴 필요가 없어요.
왜냐하면 self로하게 되면 전체 객체 자체를 Hash해서 식별자로 사용한다는걸 의미하는데 만약 객체의 사이즈가 크면 너무 비효율적입니다.
또한, 객체 내부 프로퍼티 등이 변경되거나 한다면 해당 self로 가져온 식별자 자체도 변경되기에 적절하지 않아요.
즉, 무의식적으로 self로 사용된곳들에서 유니크하게 id같이 식별할 수 있는 필드 값이 있다면 그걸 활용하시는게 적절합니다 🙋🏻

2024-08-09 19:57 UTC, serena0720 reviewed
고생하셨어요! 저희 고지가 앞입니다💪

2024-08-09 19:57 UTC, serena0720 commented on Projects/Core/Models/Group/Response/MemberList.swift
> +
P3: 외부 모듈에서 생성하여 사용될 수 있는 객체면 public init 이 필요할 거 같습니당

2024-08-09 19:57 UTC, serena0720 commented on Projects/Core/Models/Group/Response/MemberList.swift
> +public struct Member: Decodable, Hashable {
위와 동일하게 public init 을 고려하면 좋을 거 같아요!

2024-08-09 19:57 UTC, serena0720 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +      case .getMemberList(.failure):
실패 시 에러로그가 있어도 좋을 거 같아요!

2024-08-09 19:57 UTC, serena0720 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +          type: store.isFullCapacity ? .inactive : .active,
P4: isFullCapacity의 값에 따른 active값을 state에서 갖고 있고 type은 store의 state값을 부르는 방식으로 분리하는 건 어떤가요?

2024-08-10 17:42 UTC, zekexros requested changes
수고하셨어요! 👍

2024-08-10 17:42 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +      memberList.members.count == 4
저는 현재의 관리 방식에 문제가 전혀 없다고 생각합니다 👍

2024-08-10 17:42 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +    }
P5
그룹 최대 인원이 4명인가요? 6명인가요?(`isFullCapacity`에서 4로 지정한 부분과 해당 문구가 상충하여 헷갈려서 여쭤봐요)

2024-08-10 17:42 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +    @Shared var userInfo: UserInfo
P4:
개인적으로 매크로나 프로퍼티 래퍼가 적용된 프로퍼티들을 연산 프로퍼티보다 먼저 선언하는 것이 가독성을 높인다고 생각합니다(굳이 수정 안 해도 됨)

2024-08-10 17:42 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +          }, catch: { error, send in }
P1:
`Result`로 이미 에러 핸들링을 하고 있으므로 catch handler가 필요 없습니다

2024-08-10 17:42 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberView/MemberView.swift
> +        .font(.head16)
P2:
다크 모드를 고려하지 않기로 결정한 것을 생각한다면 따라 폰트 색상 설정이 필요하지 않을까요?

2024-08-11 00:05 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +          }, catch: { error, send in }
네 그러면 catch 구문 자체를 제거하는게 적절할것 같은데요~?

2024-08-11 00:08 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberView/MemberView.swift
> +        .font(.head16)
맞아요 왠만하면 명시적으로 색상을 넣어주는게 두 모드 대응을 하던 한 모드만 가져가도 좋습니다.
사실 물론 지금처럼 넣지 않아도 다크모드를 비활성화 될거기에 기본 라이트모드로만 켜질거고 색상또한 그에 맞춰 블랙으로 기본 값이나 상위 값을 따라갈거라 보여지는데 디바이스 모드에 따라 보여지는데 전혀 지장은 없지만, 추후를 생각해도 명시적인게 좋습니다~

2024-08-11 11:44 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberView/MemberView.swift
> +        .font(.head16)
넵 모두 명시하는 방향으로 수정하겠습니다!

2024-08-11 11:45 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +    @Shared var userInfo: UserInfo
ㅎㅎㅎ앞으로 참고하겠습니다 🫡

2024-08-11 11:46 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +    }
아 기획 명세상 4명인데 피그마에 잘못 기입돼있는 부분을 그대로 가져왔네요! 문구 수정하겠습니다~!

2024-08-11 11:48 UTC, hope1053 commented on Projects/Core/Models/Group/Response/MemberList.swift
> +
MemberList, Member 모두 현재 네트워크 response data에서 decoding해서 사용하고 있어서 따로 init 구문이 필요없을거라고 생각돼서 추가하지 않았어요! 혹시 필요하다고 생각되는 부분이 있으시면 알려주실 수 있을까요?.👀

2024-08-11 11:51 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +          type: store.isFullCapacity ? .inactive : .active,
오 그것도 좋은 것 같아요! Core에서 DesignSystem 컴포넌트의 상태값까지 관리하는건 괜찮은 방법일까요? @GREENOVER @zekexros

2024-08-11 14:48 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +          type: store.isFullCapacity ? .inactive : .active,
DesignSystem의 일부 컴포넌트가 갖는 상태를 View에서만 처리하기에 다소 애매한 경우들도 있고, Core에서 관리하면 안 될 이유도 딱히 찾지 못했어요. 이미 Core에서 관리하고 있는 곳들도 몇몇 있구요. 원하는대로 관리하시면 될 것 같아요

2024-08-11 23:12 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +          type: store.isFullCapacity ? .inactive : .active,
네 그럼요.
예를들어 바인딩되야하는 값들이 있다면, 필히 Core와 연결지어야 하는것처럼 필요하다면 DS 컴포넌트의 상태값을 Core와 연계시켜도 좋아요~

2024-08-12 03:35 UTC, serena0720 commented on Projects/Core/Models/Group/Response/MemberList.swift
> +
아아 그렇군요! 필요없다는 의견에 동의합니다👍

2024-08-12 03:42 UTC, zekexros approved these changes
![image](https://github.com/user-attachments/assets/69fb8d27-3441-4800-9f9d-a223afc8d9c9)

2024-08-12 13:34 UTC, GREENOVER approved these changes

2024-08-12 13:34 UTC, merged