[Feat] 멤버 리스트 API 연동
mash-up-kr/gabbangzip-iOS pull request #112
Opened 2024-08-08 15:51 UTC by zekexros

## 📌 Related Issue
- #111 

## 🚀 Description
- 홈 화면의 그룹들을 ChildReducer로 구현하고 쿡찌르기, 이미지 업로드 API 연동
- 독립적인 Model과 DesignSystem을 Scene에서 재사용성과 편의성을 높여 사용하기 위해 새로운 타겟 생성

## ✅ TODO
- [x] 홈 화면 리팩토링
- [x] 이미지 업로드 API 연동
- [x] 쿡찌르기 API 연동
- [x] 러브버그 타겟 생성

## 📸 Screenshot(optional)

## 📢 Notes
 
## 🧪 Testing(optional)

2024-08-09 01:25 UTC, GREENOVER requested changes
수고하셨습니다~ㅎㅎ
야미야미
최종 확인 한번 부탁드려요 👍

2024-08-09 01:25 UTC, GREENOVER commented on Projects/Core/Models/Group/Response/GroupData.swift
>  public struct RecentEvent: Decodable, Hashable {
id값을 명시적으로 추가했기에, Hashable하지 않아도 되지 않나요~?
해당 인스턴스를 Set, Dictionary등으로 사용되지 않아보여서요.
만약 상위 모델 타입과 연관있다면, 제가볼때 왠만해서 대부분 유니크한 id 필드가 존재하는것 같은데, 만약 ForEach의 id로 self 판단을 위해 Hashable하고 있는거라면 제거되도 무방하고 다른 쓰임이 있다면 그대로 가도 좋습니다~

2024-08-09 01:25 UTC, GREENOVER commented on Projects/Core/Models/PushNotification/Response/Kook.swift
> +public struct Kook: Codable {
해당 객체는 Encoding될 일이 있나요? 🙋🏻

2024-08-09 01:25 UTC, GREENOVER commented on Projects/Core/Models/PushNotification/Response/RegisteredFCMToken.swift
> +  public let registedToken: String
서버에서 실수인가 싶은데, registed라는 단어가 있나요?
모델 네이밍해주신것처럼 registered가 맞는거 아닌가 싶네요 🤔
그냥 넘어가도 상관은 없고, 거슬리시다하면 서버 필드 수정을 요하면 될것 같습니다ㅎㅎ
![스크린샷 2024-08-09 오전 9 51 25](https://github.com/user-attachments/assets/4691a4c0-91ab-4033-a9b5-addbd260f889)

2024-08-09 01:25 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Group/GroupCore.swift
> +    case delegate(Delegate)
오 아주 야미야미하네요 👍

2024-08-09 01:25 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Group/GroupView.swift
> +import Lovebug
Lint import 순서 워닝뜰거 같아유~

2024-08-09 01:25 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Group/GroupView.swift
> +      if store.status == .noPastAndCurrentEvent || store.status == .noCurrentEvent {
요 로직도 State에서 연산 프로퍼티로 가지고 있는건 어떤가요?
뷰에서 최대한 연산 로직을 가져가지 않는게 좋아보입니다~

2024-08-09 01:25 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Group/GroupView.swift
> +  private func groupContentView() -> some View {
어떤 방법이 더 확실히 나은것은 없지만 해당 메서드로 구현 시 이런점들을 유의해보면 좋을것 같습니다 🙋🏻
- 뷰가 복잡해지면 GroupView 구조체 자체가 비대해질 수 있음
  - 물론 구조체로 나누는것이 전체적인 복잡성을 없애는것이 아니고, 해당 구조체가 특정 부분의 UI를 담당하기에 책임 분리가 확실한 부분이 있습니다.
- 각 뷰에 책임이 명확하진 않음
- 재사용성이 떨어짐 (이건 뭐 사실 해당 내부에서만 쓰는거니까 크게 상관은 없지만)

물론, 구조체로 만드는것보다 장점도 존재합니다.

그렇기에, 추후에 고려 시 해당 child가 비대하다면 구조체로 생성하는게 좀 더 적절할 수 있을것 같아요. (실제로 정말 비대해지면 성능 차이가 있긴하더라구요. 명확히 이유는 모르겠음)

2024-08-09 01:25 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Group/GroupView.swift
> +  @MainActor
메인액터 어노테이션 꼭 붙여야하나요?
View 프로토콜의 body는 이미 @MainActor로 선언되어 있고, 위 상단 GroupView도 물론 View를 준수하기에 내부 모든 메서드와 계산 프로퍼티와 같은 친구들도 자동으로 메인 액터에서 실행됩니다.
또한 some View를 반환하는 메서드들은 이미 메인스레드에서 실행되는걸 보장받고 있는걸로 알고있어서, 명시적으로 메인액터 어노테이션을 붙일 필요가 있는지 궁금해요 🙋🏻

2024-08-09 01:25 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/GroupList/GroupListCore.swift
> +          for i in 0..<state.groups.count {
```suggestion
          for i in state.groups.indices {
```
이렇게 호출하는것이 미세하지만 성능적으로 도움이 더 됩니다.
왜냐하면 기존 코드는 반복시에 계속 count를 평가하는데, 물론 컴파일러가 대부분 최적화를 시켜줘서 크게 당연히 지장은 없지만 이론적으로는 그렇습니다.
또한, 후자의 방식이 직접 배열의 유효한 인덱스 범위에 접근하기에 배열의 크기가 큰 경우 더 효율적이긴 합니다.
조금 더 간결하기도 하고 유연해보이기도 해요 🙋🏻

2024-08-09 02:31 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Group/GroupView.swift
> +  @MainActor
특히, WWDC 2024 Swift 6 세션에서도 소개되었는데, 이제 body에서가 아닌 더욱 View 프로토콜 전체적으로 메인액터 선언으로 수정되어 명시적으로 표시할 필요가 없긴합니다.
![스크린샷 2024-08-09 오전 11 31 29](https://github.com/user-attachments/assets/b898343c-c142-4094-89ca-a94d62d5eb94)
![스크린샷 2024-08-09 오전 11 31 36](https://github.com/user-attachments/assets/a9c62cec-ab59-4a11-8976-18607687ab5b)

2024-08-09 20:05 UTC, serena0720 reviewed
러브버그... 벗어날 수 없는 버그의 굴레🤦‍♀️
저의 머리론 리팩토링 하신 내용 및 방향은 직접 사용해봐야 이해가능할 거 같습니다😇
항상 좋은 코드를 고민하는 모습 옆에서 보고 배우고 있습니다!👍
대장님 짱짱

2024-08-09 20:05 UTC, serena0720 commented on Projects/Core/Services/PicAPIClients/PushNotificationAPI/PushNotificationAPIClient.swift
> +    case getAPIError = 0
P5: `= 0`은 삭제 가능할 거 같습니다!

2024-08-09 20:05 UTC, serena0720 commented on Projects/Features/Scene/Lovebug/GroupDataStatus+extensions.swift
> +      return nil
default를 타는 경우가 있나요?
default가 nil을 반환하지 않으면 해당 타입이 옵셔널일 필요가 없을 거 같아서 여쭤봅니다! 옵셔널로 사용해야하는 이유가 있는걸까요?

2024-08-10 17:06 UTC, zekexros commented on Projects/Core/Models/Group/Response/GroupData.swift
>  public struct RecentEvent: Decodable, Hashable {
원래 해당 모델에는 `id` 속성이 없었기 때문에 `Hashable`을 채택하여 `SwiftUI`의 `ForEach`를 사용했었는데, 최근 `id` 속성이 추가로 생겼고 또 `Identifiable`한 ChildView 및 Store로 리팩토링하였으므로 `Hashable`을 채택하지 않아도 되겠네요! state로서는 사용될 모델이므로 `Equatable`로 바꾸면 될 것 같아요

2024-08-10 17:06 UTC, zekexros commented on Projects/Core/Models/PushNotification/Response/Kook.swift
> +public struct Kook: Codable {
오? 깜빡했습니다. Decodable로 수정하겠습니다

2024-08-10 17:07 UTC, zekexros commented on Projects/Core/Models/PushNotification/Response/RegisteredFCMToken.swift
> +  public let registedToken: String
맞습니다. registeredToken이 올바른 단어입니다. 수정 요청할게요

2024-08-10 17:08 UTC, zekexros commented on Projects/Features/Scene/MainScene/Group/GroupCore.swift
> +    case delegate(Delegate)
역시 미식가다운 면모를 보여주시네요

2024-08-10 17:08 UTC, zekexros commented on Projects/Features/Scene/MainScene/Group/GroupView.swift
> +import Lovebug
수정 완료!

2024-08-10 17:09 UTC, zekexros commented on Projects/Features/Scene/MainScene/Group/GroupView.swift
> +      if store.status == .noPastAndCurrentEvent || store.status == .noCurrentEvent {
동의합니다. 연산 프로퍼티를 사용하더라도 뷰에서 로직을 작성하는 건 최대한 지양하는게 맞습니다

2024-08-10 17:15 UTC, zekexros commented on Projects/Features/Scene/MainScene/Group/GroupView.swift
> +  private func groupContentView() -> some View {
해당 화면은 사용자가 가장 자주 보게될 View로 역시 성능에 신경을 써야하는 것에 동의합니다. 따라서 View를 분리를 해봤는데 CardFront나 CardBack은 분리가 잘 되었는데 GroupContentView는 대부분의 state를 필요로 하여 store 전체를 파라미터로 받도록 하였지만 이는 분리의 의미가 있을까 싶지만, 성능이 중요한 화면이라는 점을 고려하여 분리하였습니다(트레이드 오프)

2024-08-10 17:18 UTC, zekexros commented on Projects/Features/Scene/MainScene/Group/GroupView.swift
> +  @MainActor
제거하였습니다. 굳이 붙일 필요는 없네요. 붙이는 이유가 분명히 있었는데 당장 기억이 나지 않습니다🫨

2024-08-10 17:18 UTC, zekexros commented on Projects/Features/Scene/MainScene/GroupList/GroupListCore.swift
> +          for i in 0..<state.groups.count {
오.. 그렇군요.. 앞으로 자주 사용하겠습니다! 하나 배워가욧!

2024-08-10 17:19 UTC, zekexros commented on Projects/Core/Services/PicAPIClients/PushNotificationAPI/PushNotificationAPIClient.swift
> +    case getAPIError = 0
제거하였습니다!

2024-08-10 17:20 UTC, zekexros commented on Projects/Features/Scene/Lovebug/GroupDataStatus+extensions.swift
> +      return nil
`GroupData.Status`를 보시면 7가지 케이스가 존재하고 안 쓰이는 케이스는 없습니다, 이때 4가지 경우를 제외하곤 `SmallButtonContentType`이 필요하지 않아 `nil`을 반환하도록 구현하였습니다.

2024-08-11 00:22 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Group/GroupView.swift
> +  @MainActor
아마 붙이는 이유중 하나는, 기존에는 Concurrency 상 해당 뷰에서 메서드를 가질때 해당 메서드가 비동기 작업 시, async 하기에 기본적으로 특정 액터에 속하지 않게 될거라 보여요.
그래서, 예를들어 아래와 같이
```swift
struct GreenView: View {
  var body: some View {
    ...
      .onAppear { await fetch() }
 
 func fetch() async {
   let data = await fetchNetwork()
   update(data)
  }
```
요랬을때, fetchNetwork는 await를 만났기에 현재의 스레드 제어권을 포기하고 시스템에 넘겨줘 백그라운드 스레드에서 실행될거고, 이후 update는 UI를 업데이트를 한다고 생각하면 메인 스레드에서 일어나야하지만, fetchNetwork를 진행한 스레드를 이어받아 실행하게 됩니다.

그렇기에 원래 swift 6전에는 body에만 MainActor가 붙어있어 View 내에서 작성되는 메서드들에 대해 이런 쓰임이 있다면 명시적으로 붙이던가 아니면 아래와 같이,
```swift
struct GreenView: View {
  var body: some View {
    ...
      .task { await fetch() }
 
 func fetch() async {
   let data = await fetchNetwork()
   await MainActor.run {
     update(data)
   }
  }
```
으로 하여 UI 사항을 메인스레드로 다시 제어권을 가져오는 방법을 택하여 사용했어요.
즉, swift 6 이전 기준으로는 준혁님이 붙였던것도 이런 메서드들의 구조가 담길때는 아예 무조건 불필요하다라고 볼 순없는데,
현재 코드에선 뷰에 대한것만 존재하고 또한 TCA로 우린 뷰에서가 아닌 Core에서 처리하고, 마지막으로 이제 swift 6 전환 시점이라 더 이상 이런 부분을 고려하지 않아도 되기에 진보적으로 제거하는것이 적절한 방향으로 보입니다 😃

기억이 나지 않는다하셔서 왠지 이런 쓰임이였을수도 있어서 남겨봐요~!

2024-08-11 00:26 UTC, GREENOVER approved these changes
1 기영 드리고 갑니다 👍
![스크린샷 2024-08-11 오전 9 26 35](https://github.com/user-attachments/assets/3e1df3c3-32bb-4238-91aa-ac468eb75e25)

2024-08-11 03:24 UTC, zekexros commented on Projects/Features/Scene/MainScene/Group/GroupView.swift
> +  @MainActor
와우.. 자세한 설명 감사합니다. 사실 TCA를 사용할 때 비동기 처리가 필요할 경우 Effect의 run 메서드에서 제공되는 비동기 컨텍스트를 주로 활용한 점 & 평소에 메서드로 화면을 구성하지 않는다는 점이 해당 어노테이션을 붙인 기억이 나지 않는 이유라고 볼 수 있는데요. 찬우님의 설명을 들어보니 아마 거의 저 쓰임(비동기로 처리 후 메인 스레드에서 업데이트)을 위해 MainActor를 항상 붙여 쓰지 않았나 생각이 듭니다. 구우우우웃👍

2024-08-11 03:25 UTC, zekexros commented
기영이 받고 심슨 추가합니다
![image](https://github.com/user-attachments/assets/6920f93e-6c0d-42cd-b130-1b4aff0051b3)

2024-08-11 12:19 UTC, hope1053 approved these changes
수고하셨습니다 👍 한가지 궁금한 점이 있는데 LoveBug 타겟을 별도의 프로젝트가 아니라 Scene 프로젝트 내부의 타겟으로 구성한건 해당 타겟이 Scene 내부의 타겟들에서만 사용될 예정이라 그런건가요 ?!

2024-08-11 12:19 UTC, hope1053 commented on Projects/Features/Scene/MainScene/Group/Views/GroupContentView.swift
> +        FlipView(
P5: 요 부분 변수로 살짝 분리해도 좋을 것 같은데 어떻게 생각하시나요!

2024-08-11 12:19 UTC, hope1053 commented on Projects/Features/Scene/MainScene/GroupList/GroupListCore.swift
> +          for i in state.groups.indices {
객체에 대한 for문이 아닌 indices에 대한 for문으로 작성하신 이유가 궁금해요~!

2024-08-11 14:53 UTC, zekexros commented on Projects/Features/Scene/MainScene/Group/Views/GroupContentView.swift
> +        FlipView(
그룹 상세에서도 쓰이나요? 두 곳 이상에서 쓰인다면 저도 변수로 분리하는 것은 찬성이에요

2024-08-11 14:58 UTC, zekexros commented on Projects/Features/Scene/MainScene/GroupList/GroupListCore.swift
> +          for i in state.groups.indices {
객체를 바탕으로 for문을 작성한다면 해당 구문 안에서의 각 group은 상수 취급하므로 상태 변경을 할 수 없습니다😵

2024-08-11 15:08 UTC, zekexros commented
> 수고하셨습니다 👍 한가지 궁금한 점이 있는데 LoveBug 타겟을 별도의 프로젝트가 아니라 Scene 프로젝트 내부의 타겟으로 구성한건 해당 타겟이 Scene 내부의 타겟들에서만 사용될 예정이라 그런건가요 ?!

네, 맞습니다! LoveBug는 독립적인 DesignSystem과 Models 타겟을 Scene에서 편리하기 사용하기 위한 용도로 Helper성격의 타겟을 굳이 프로젝트 단위까지 나눌 필요는 없다고 생각했어요💡

2024-08-12 00:30 UTC, hope1053 commented on Projects/Features/Scene/MainScene/Group/Views/GroupContentView.swift
> +        FlipView(
아 아뇨 ! 그건 아니구 그냥 요 view 안에서 조금 더 보기 편하게 분리하자~라는 의미였습니다! 그냥 가셔도 될 것 같아요 ~

2024-08-12 02:02 UTC, merged