[Feat] 이벤트 생성 화면 구현
mash-up-kr/gabbangzip-iOS pull request #114
Opened 2024-08-09 17:56 UTC by serena0720

## 📌 Related Issue
- #43 

## 🚀 Description
- EventStart, EventProcess 화면 구현하였습니다.
- 관련 화면을 CreatEventCoordinator로 연결하였습니다.

## ✅ Done
- EventStart 화면에 로띠파일 넣어 생성하였습니다.
- EventProcess 화면에 텍스트뷰, CurrentDate, ImagePicker 화면을 구현하였습니다.
- Design파일 : GabbangzipDate, SelectPhoto를 생성하였습니다.
- CreateEventCoordinator를 생성하였습니다.

## 📸 Screenshot
<img src="https://github.com/user-attachments/assets/9a36d548-7da8-4f75-b6ff-d449a9f4f8b1" width=“350"/>
<img src="https://github.com/user-attachments/assets/e086118b-6327-49ac-a4b6-75bfffe63fa2" width=“350"/>

## 📢 Notes
 - Event API는 별도 이슈 생성하여 작업 예정입니다.
 - CreateEventCoordinator가 MainCoordinator를 알게되면 순환구조 문제가 발생하는데, 이를 어떻게 해결해야할지 모르겠습니다.
 - 현재 CreateEventCoordinator를 삭제해야할 수도 있습니다.. 이벤트 생성 Start 화면이 불필요하다는 코멘트가 있었습니다.
 이 부분 상의되는 대로 업데이트 공유하겠습니다. 오히려 MyPageCoordinator를 살리는것이 현명한 판단이었을 거 같습니다.. 역시 대장님의 혜안..

2024-08-09 23:29 UTC, GREENOVER commented
@serena0720 
리뷰하기 앞서 이상한게 있어서 말씀드려요.
첫번째 gif를 보니까 이벤트 만들기 뷰에서 뒤로 가기를 통해 홈 메인 화면이 나오는데, 왜 push되는 그림이죠?
(우측에서 슬라이딩해서 나오는 전형적인 push)
코멘트에 남겨주셨던, CreateEventCoordinator가 MainCoordinator를 알고 있어서 push 시키고 있나요?
그렇다면 역전이 된거에요.
MainCoordinator가 CreateEventCoordinator를 아는 구조거나 아니면 MainCoordinator와 CreateEventCoordinator 같은 레벨로 본다면 그 두개를 가지고 있는 상위 코디네이터 route 액션에서 pop을 발행해주는 구조로 가야합니다.
좋은 방식이 아닌걸 떠나서, 아예 잘못된 흐름이기에 수정을 요청드립니다 🙏🏻
즉, [MainCoordinator, [CreateEventCoordinator]] 이런 방식으로 쌓이는것이 흐름상 맞다면 같은 레벨 선상으로 볼텐데 그럼 이걸 관장하는 app이나 home 코디네이터 (상위 코디네이터 객체)에서 route를 다뤄줘야 의도하신 CreateEventCoordinator 스택을 pop했을때 MainCoordinator가 적절히 나오고 할것 같아요.
여튼... 요 리뷰 반영보다 우선적으로 요 부분 긴급 수정해주셔야 될듯 합니다.

2024-08-09 23:58 UTC, GREENOVER requested changes
일단 좀 문제되는 부분만 핵심으로 남겼어요~
전체 점검 하셔야 합니다!

2024-08-09 23:58 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/Date/GabbangzipDate.swift
> +  ) {
한줄이여도 충분할것 같아요~!

2024-08-09 23:58 UTC, GREENOVER commented on Projects/DesignSystem/Resources/Icons.xcassets/Event/delete.imageset/Contents.json
> +  "images" : [
svg 추가하신 아이콘들 다 1배수만 적용되있죠~?
우측 인스펙터 섹션에서 scales를 single scales로 바꿔주세요~
(작업으로 추가하신 svg 전부요.)

2024-08-09 23:58 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/PhotoPicker/PhotoInfo.swift
> +public struct PhotoInfo: Equatable, Hashable {
Hashable 필요한 이유 설명해주실수 있나요~?

2024-08-09 23:58 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/PhotoPicker/PhotoInfo.swift
> +public struct PhotoInfo: Equatable, Hashable {
추가로, 이건 플젝을 떠나서 생각해보시면 좋을것 같아요.
Equatable은 무엇이고 Hashable은 기본적으로 뭘 채택하고 있을까요~?
두 쓰임이 정확히 어떤것이고 우리 플젝 현재 코드에서는 어떤것을 채택하는게 왜 적절한지 서술해봐주세요 🙇🏻

2024-08-09 23:58 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/SelectPhoto/SelectPhoto.swift
> +          Text("/\(maxCount)")
적절히 한줄 개행해보기ㅎㅎ

2024-08-09 23:58 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/SelectPhoto/SelectPhoto.swift
> +    HStack(spacing: 0) {
왜 HStack으로 한번 더 감쌌어요?
불필요합니다.
제거하고 적절히 나타나도록 수정해주세요 🙏🏻

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Coordinator/CreateEventCoordinator/CreateEventCoordinatorCore.swift
> +      case .router(.routeAction(id: _, action: .createEventStart(.moveToCreateEventProcess))):
저는 보통 저희 Lint룰로 정한것처럼 인자 기준으로 개행을 하긴 하는데 요건 뭐 스타일이라 PR 코멘트에 적어주신것처럼 같이 토의해보시면 될것 같아요ㅎㅎ

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Coordinator/CreateEventCoordinator/CreateEventCoordinatorView.swift
> +        switch screen.case {
CreateEvent쪽에서 흐름이 단방향이 아닌가요?
즉, 탭바처럼 스위칭해서 독립적으로 뷰가 보여지는 구조인지 몰라서요~!
제가 코드만봐서 모를수 있는데, 이전 PR 코멘트에 남긴것처럼 해당 코디네이터 구조 리팩토링이 필요해서 일단 크게 신경안쓰고 넘어가겠습니다~
추후, 개선되면 그때 리뷰하겠습니다.

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessCore.swift
> +    case onAppear
순서상 항상 제일먼저 타니 앞으로 가도될것 같아요~
(작은 의견)

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessCore.swift
> +          }
```suggestion
          await send(.changeIsEventNamedStatus(state.text.isEmpty))
```
한줄로 표현하면 간결할것 같아요.

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessCore.swift
> +          return formatter.string(from: Date())
DateFormatter+extensions에 확장시켜서 사용해주세요~
일원화 관리하는게 편합니다.
필요하면 String+extensions도 보시구요~!

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessCore.swift
> +        }
코드를 줄여보세요~

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Scene/CreateEventScene/CreateEventStart/CreateEventStartCore.swift
> +    ) {
파라미터 1개 = 한줄 (우리의 코드 컨벤션)

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessView.swift
> +    VStack(spacing: 0) {
뷰 비대합니다.
나누주세요 🙏🏻

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessView.swift
> +        VStack(spacing: 0) {
VStack에서 또 아래 VStack으로 감쌀 필요가 있나요?
이미 수직적 계층으로 쌓이고 있는 형태로 보여서요.

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessView.swift
> +    VStack(spacing: 0) {
그리고 되게 VStack으로 여러 중첩되어 쌓여있는데, 점검해주세요.
필요없는 Stack 제거해주세요ㅠ
만약 이렇게 꼭 표현되어야 한다?
그럼 코드가 잘못된걸거에요.. 다른 방법을 모색해보셔야 합니다.

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessView.swift
> +              GabbangzipPhotoPicker(
Indent 안맞아요.

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessView.swift
> +                isPresentedError: .constant(false),
에러는 표시안해서 상수처럼 박아두신거죠~?
쓸거면 수정해주시고 값 넣어줄 필요없어요.
해당 컴포넌트 들어가보시면 기본값 들어가있습니다.

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessView.swift
> +                        .padding([.trailing], -8)
하나인데 배열에 담아줄 필요는 없어보이네요!

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessView.swift
> +          } else {
위 코멘트에서도 말했듯, 무조건 뷰 쪼개주세요.
비대합니다.

2024-08-09 23:58 UTC, GREENOVER commented on Projects/Features/Scene/CreateEventScene/CreateEventStart/CreateEventStartView.swift
> +        .frame(width: geometry.size.width - 229, height: geometry.size.width - 229)
229 이건 DS 상 수치인거죠?ㅋㅋ
frame으로 이렇게 줄거면, 이걸 생각해보셔야 합니다.
작은 디바이스에서는 정말 작게 보일거고,
큰 디바이스에서는 비교적 크게 보일거에요.
즉, 화면에 대해 해당 로티 비율이 다를겁니다 디바이스마다
그래서 비율 유지시킬거면 패딩으로~

2024-08-10 18:29 UTC, zekexros requested changes
이벤트를 만든 후 그룹 상세 화면으로 가고 싶다면 `MainCoordinator`에서 조작을 해야 합니다. 그렇다면 이벤트 생성 코디네이터를 닫은 후(dismiss) 그룹 상세로 이동(push)이 되어야 하겠죠. 2번의 화면 전환을 발생시키려면 TCACoordinator의 [Making complex navigation updates](https://github.com/johnpatrickmorgan/TCACoordinators#making-complex-navigation-updates)를 참조하셔서 MainCoordinator에서 구현하시면 됩니다.

기능에 대한 구현 **속도**와 **품질**이 예전에 비해 크게 향상된 것을 보고 놀랐습니다. 감동이에요 👍

2024-08-10 18:29 UTC, zekexros commented on Projects/DesignSystem/Sources/Views/Date/GabbangzipDate.swift
> +    .cornerRadius(10)
P4:
피그마에선 Radius가 8로 설정되어있는데 혹시 다시 한번 확인해주시겠어요?!

2024-08-10 18:29 UTC, zekexros commented on Projects/DesignSystem/Sources/Views/SelectPhoto/SelectPhoto.swift
> +  @Binding private var selectedPhotosInfo: [PhotoInfo]
P2:
Binding일 필요가 없어보입니다. selectedPhotosInfo를 전달받아 SelectPhoto 안에서 값을 변경해주는 곳이 없는 것 같아요

2024-08-10 18:29 UTC, zekexros commented on Projects/Features/Coordinator/CreateEventCoordinator/CreateEventCoordinatorCore.swift
> +        state.routes.push(.moveToGroupList(.init()))
P1:
...? move가 두 번씩 쓰였어요

2024-08-10 18:29 UTC, zekexros commented on Projects/Features/Coordinator/CreateEventCoordinator/CreateEventScreen.swift
> +  case moveToCreateEventProcess(CreateEventProcessCore)
P1:
첫 번째 케이스(createEventStart) 처럼 나머지 케이스들도 Reducer에 맞춰 작성해주시면 됩니다

2024-08-10 18:29 UTC, zekexros commented on Projects/Features/Coordinator/MainCoordinator/MainCoordinatorCore.swift
> +
Good👍

2024-08-10 18:29 UTC, zekexros commented on Projects/Features/Coordinator/Project.swift
> +      ]
P1:
해당 코디네이터는 groupDetail, main을 알 필요가 없으므로 Dependencies쪽 수정되어야 하겠죠

2024-08-12 14:58 UTC, serena0720 commented on Projects/DesignSystem/Resources/Icons.xcassets/Event/delete.imageset/Contents.json
> +  "images" : [
와 또 하나 배웠습니다 감사합니다!

2024-08-12 15:00 UTC, serena0720 commented on Projects/DesignSystem/Sources/Views/Date/GabbangzipDate.swift
> +  ) {
앗 거의 기계적으로 쳐놨더니...! 꼼꼼한 리뷰 감사합니다 유사 케이스 함께 수정했습니다!

2024-08-12 15:00 UTC, serena0720 commented on Projects/DesignSystem/Sources/Views/SelectPhoto/SelectPhoto.swift
> +          Text("/\(maxCount)")
넵 수정하겠씁니다!

2024-08-13 02:31 UTC, serena0720 commented on Projects/DesignSystem/Sources/Views/SelectPhoto/SelectPhoto.swift
> +    HStack(spacing: 0) {
오우 감사합니다!!

2024-08-13 02:32 UTC, serena0720 commented on Projects/Features/Coordinator/CreateEventCoordinator/CreateEventCoordinatorView.swift
> +        switch screen.case {
현재 화면이 단일뷰로 수정되면서 CreateEventCoordinator를 삭제하기로 하였습니다🥹 이와 관련된 이슈들 모두 함께 닫도록 하겠습니다🙇‍♀️

2024-08-13 02:32 UTC, serena0720 commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessCore.swift
> +          }
와 너무 좋은 조언 감사합니다!!

2024-08-13 02:37 UTC, serena0720 commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessCore.swift
> +        }
넹~ 삼항으로 변경했습니다

2024-08-14 03:50 UTC, serena0720 commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessCore.swift
> +          return formatter.string(from: Date())
GroupCore와 동일하게 DateFormatter를 활용하며, RecentEvent를 받아서 처리하는 방식으로 수정하겠습니다!

2024-08-14 03:50 UTC, serena0720 commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessView.swift
> +              GabbangzipPhotoPicker(
헉 감사합니다!

2024-08-14 03:51 UTC, serena0720 commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessView.swift
> +                isPresentedError: .constant(false),
GroupCore에서도 사용 시 명시했길래 통일되게 한것인데 삭제하도록하겠습니다!

2024-08-14 03:52 UTC, serena0720 commented on Projects/Features/Scene/CreateEventScene/CreateEventProcess/CreateEventProcessView.swift
> +                        .padding([.trailing], -8)
앗... 이래저래 고민하다가 놓쳤네요ㅜ 감사합니다!

2024-08-14 03:53 UTC, serena0720 commented on Projects/Features/Scene/CreateEventScene/CreateEventStart/CreateEventStartView.swift
> +        .frame(width: geometry.size.width - 229, height: geometry.size.width - 229)
해당 뷰가 삭제되면서 전체적인 수정하도록 하겠습니다🥹

2024-08-14 03:56 UTC, serena0720 commented on Projects/DesignSystem/Sources/Views/Date/GabbangzipDate.swift
> +    .cornerRadius(10)
해당 뷰와 동일한 모양으로 가는 "이벤트 한줄 요약"의 코너에 맞췄습니다 이부분 디자인팀에 업데이트 하겠습니다!

2024-08-14 04:01 UTC, serena0720 commented on Projects/DesignSystem/Sources/Views/SelectPhoto/SelectPhoto.swift
> +  @Binding private var selectedPhotosInfo: [PhotoInfo]
오호... 아 맞네요... 와 감사합니다!

2024-08-14 04:02 UTC, serena0720 commented on Projects/Features/Coordinator/CreateEventCoordinator/CreateEventCoordinatorCore.swift
> +        state.routes.push(.moveToGroupList(.init()))
ㅠ 해당 코디네이터 삭제해야해서 전체적으로 수정 후 재확인 부탁드립니다ㅜ

2024-08-14 04:10 UTC, serena0720 commented on Projects/Features/Coordinator/CreateEventCoordinator/CreateEventScreen.swift
> +  case moveToCreateEventProcess(CreateEventProcessCore)
꼼꼼한 리뷰 감사합니다!

2024-08-14 04:26 UTC, serena0720 commented on Projects/DesignSystem/Sources/Views/Date/GabbangzipDate.swift
> +    .cornerRadius(10)
10으로 통일하기로 했습니당~ 꼼꼼한 확인👍 갓갓

2024-08-14 06:17 UTC, serena0720 commented
##Note
디자인 수정으로 CreateEventCoordinator가 아닌 CreateEvent로 수정하였습니다.
이부분 참고 부탁드립니다.
@GREENOVER @zekexros @hope1053

2024-08-14 09:15 UTC, GREENOVER approved these changes

2024-08-14 09:45 UTC, zekexros approved these changes

2024-08-14 11:04 UTC, serena0720 commented on Projects/DesignSystem/Sources/Views/PhotoPicker/PhotoInfo.swift
> +public struct PhotoInfo: Equatable, Hashable {
Equatable은 두개의 값이 동일한지를 비교, Hashable을 Key값을 Hashtable을 통해 Hashvalue를 찾아 비교합니다.
이때 Hashable이 Equatable을 상속하고 있기 때문에 Hashable을 사용한다면 Equatable을 채택하지 않아도 될 거 같습니다!

현재 코드에선 이미지의 고유한 key값으로 해시값을 비교하여 동일한 사진 중복을 막고자 하여 Hashable을 채택하였습니다.

2024-08-14 12:49 UTC, zekexros requested changes

2024-08-14 12:49 UTC, zekexros commented on Projects/Features/Coordinator/MainCoordinator/MainCoordinatorCore.swift
> +
P1:
`GroupList`가 `Home`으로 바뀌었습니다

2024-08-14 13:26 UTC, zekexros approved these changes

2024-08-14 13:38 UTC, merged

2024-08-15 23:58 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/PhotoPicker/PhotoInfo.swift
> +public struct PhotoInfo: Equatable, Hashable {
@serena0720 
동일 사진 중복을 막고자한다면, Equatable만으로 충분하지 않나요?
Hashable은 어느정도 이해하고 계시지만, 놓친 부분이 해시 값을 사용하는 목적에서 놓쳤다고 생각해요.
해시 값은 동등성 비교를 위해 직접 사용이 되는것의 목적보다 빠른 검색에 있어요.
즉, 딕셔너리나 Set 같은 친구들에서 순환하며 요소로 판단될때 사용한것이죠.
그렇기에 현재 코드에서 단순 동일 사진 중복 체크를 위함이라면 Equatable만으로 충분합니다.