[Hotfix] MyPage 앱버전 확인 로직 추가
mash-up-kr/gabbangzip-iOS pull request #115
Opened 2024-08-09 18:22 UTC by serena0720

## 📌 Related Issue
- #113 
## 🚀 Description
- onAppear, onChange 시 앱 버전 확인 로직 추가하였습니다.

## ✅ Done
- BundleClient 사용하여 앱 버전 확인

## 📸 Screenshot
![e](https://github.com/user-attachments/assets/f2c04f53-5b92-4dec-9ce5-fe1db2f6c413)

2024-08-09 23:21 UTC, GREENOVER requested changes
수고하셨습니다ㅎㅎ
최종 점검 부탁드려요~

2024-08-09 23:21 UTC, GREENOVER commented on Projects/App/Sources/GabbangzipApp.swift
> + struct GabbangzipApp: App {
한칸 띄워졌네요 🥲

2024-08-09 23:21 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +          await send(.updateCurrentVersion(version))
두 액션이 순서가 아닌 독립적으로 어떤것이 먼저 실행되도 상관없다면 TaskGroup을 활용할수도 있는데 그냥 이건 사소한거니까 나중에 학습해보세요~

2024-08-09 23:21 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +        store.send(.onAppear)
사실 이건 push 알림 설정때문에 scenePhase의 변화를 감지해 액션을 방출하고 계신거잖아요?
그런데 onAppear 액션에서는 현재 버전까지 체크하고 있어서 적절하지 않은 액션이라고 생각됩니다.
즉, onAppear에서 현재 푸시알림 + 앱버전 두가지 액션을 다루고 있는데 그걸 여기에서 실행시킬 필요는 없는거죠.
그래서 두 액션을 쪼개고 onAppear에선 두가지를 다 부르고 여기서는 푸시알림에 대한 액션만 부르는게 적절하다고 보입니다 😃

2024-08-10 18:39 UTC, zekexros requested changes
수고하셨습니다!
`UserInfo`부분 한번 살펴봐주세요🤠

2024-08-10 18:39 UTC, zekexros commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +            break
P2:
UserDefaultsClientError는 고려할 필요가 없어보입니다

2024-08-10 18:39 UTC, zekexros commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
P2:
userInfo를 Shared State로 관리하도록 변경한 것에 대한 리팩토링이 이뤄지지 않은 것 같아요. 여전히 access token은 keychain에 저장된 userInfo를 통해 사용하고 있습니다

2024-08-10 18:41 UTC, zekexros commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
(아, UserInfo로 바꾼 곳이 없어 마땅히 참조할 코드가 없기에 그냥 아무 라인이나 선택해서 글을 작성했습니다ㅎㅎ)

2024-08-12 03:29 UTC, serena0720 commented on Projects/App/Sources/GabbangzipApp.swift
> + struct GabbangzipApp: App {
이런 일이...! 꼼꼼한 확인 감사합니다🙇‍♀️

2024-08-12 03:31 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +          await send(.updateCurrentVersion(version))
현재 Push와 Version체크 액션을 분리하면서 해당 부분이 변경되었지만 추후 TaskGroup을 사용할 일이 있으면 참고하여 공부해보겠습니다! 감사합니다👍

2024-08-12 03:32 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +        store.send(.onAppear)
좋은 조언 감사합니다~! 해당 부분 조언 참고하여 수정했습니다!

2024-08-12 03:32 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +            break
꼼꼼한 리뷰 감사합니다!!🙇‍♀️

2024-08-12 03:33 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
아 userinfo에 accesstoken이 있다는것을 놓쳤습니다! 감사합니다👍

2024-08-12 03:52 UTC, zekexros approved these changes
![R720x0 q80](https://github.com/user-attachments/assets/3677b5fd-c95a-4df1-b6cc-2ccd8a334109)

2024-08-12 04:10 UTC, GREENOVER approved these changes

2024-08-14 07:43 UTC, merged