[Feat] 그룹 상세 API 연동 2탄
mash-up-kr/gabbangzip-iOS pull request #121
Opened 2024-08-13 07:55 UTC by hope1053

## 📌 Related Issue
- #118 

## 🚀 Description
그룹 상세 나머지 부분 기능 구현 & 코디네이터 작업까지 진행했습니다!

## ✅ Done
- [x] 그룹상세 하단 우리들의 인생네컷 GridView
- [x] 상세 이미지 뷰어
- [x] 코디네이터 작업

## 📸 Screenshot
<img width="398" alt="image" src="https://github.com/user-attachments/assets/0a74e783-2152-461c-b8de-84bdc40a8335">
<img width="401" alt="image" src="https://github.com/user-attachments/assets/f4216024-4709-4d44-af05-d832a7bea383">

## 📢 Notes
아직 짜잘한 이슈가 많긴 한데요? 다른 브랜치에서 열심히 작업 중 입니다. 많관부.
 
## 🧪 Testing(optional)

2024-08-13 10:03 UTC, zekexros requested changes
수고하셨습니다👍

2024-08-13 10:03 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/HistoryDetail/HistoryDetailCore.swift
> +        return .none
P2:
backButtonTapped액션을 보낸 이후 backToGroupDetail 액션을 보내는 코드가 누락된 것 같아요

2024-08-13 10:03 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +      memberList: MemberList = .mock,
P2:
mock보다는 optional 타입으로 바꾼 후 nil로 넣어두는 것이 더 적절해 보입니다.

2024-08-13 10:10 UTC, GREENOVER requested changes
수고하셨어요ㅎㅎ
짧은 몇가지만 최종 확인 부탁드려요 ㅎㅎ

2024-08-13 10:10 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
> +      groupDetail: GroupDetailInfo = .mock,
mock객체가 담긴 초기값이 prod에 나가면 안됩니다 ㅎㅎ

2024-08-13 10:10 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/HistoryDetail/HistoryDetailView.swift
> +          status: store.keyword.convertToPhotoCardStatus()) {
괄호 개행이 좀 어색해요 ㅎㅎ

2024-08-13 10:10 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +      memberList: MemberList = .mock,
mock 객체 코드는 prod에 나가면 안돼요ㅎㅎ
예기치 못했을때, 해당 목 데이터로 보여지니까요ㅎㅎ
3탄에서 테스트용으로 사용하고 지우실거였다면, 코멘트 스킵하셔도됩니다ㅎㅎ

2024-08-13 11:28 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
> +      groupDetail: GroupDetailInfo = .mock,
헿.. 이러면 안될거같긴했는데^_^ 수정할게요 ~~~~

2024-08-13 11:47 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/HistoryDetail/HistoryDetailCore.swift
> +        return .none
이걸 까먹었네요 ,,, 감사합니다 ~

2024-08-13 22:21 UTC, GREENOVER approved these changes
굿ㅎㅎ

2024-08-14 00:12 UTC, zekexros approved these changes

2024-08-14 00:12 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
>        }
P5
```swift
switch groupDetail?.status {
  case .noCurrentEvent, .noPastAndCurrentEvent, .eventCompleted:
    return .generateEvent
  case .beforeMyUpload:
    return .uploadPIC
  case .beforeMyVote:
    return .vote
  case .afterMyUpload, .afterMyVote:
    return .stabbing
  case .none:
    return .generateEvent
}
```
이렇게도 가능합니다

2024-08-14 00:12 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
> +                  eventID: state.groupDetail?.recentEventDetail.id ?? -1
P5:
이런 경우에 저라면 옵셔널 바인딩을 하고 값이 있을때만 요청을 보내도록 할 것 같아요(기존 코드와 결과는 같으니 나중에 리팩토링해도 될 것 같아요)

2024-08-14 00:12 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/HistoryGrid/HistoryGridView.swift
> +  private let histories: [History]?
배열은 옵셔널 타입을 사용하지 않아도 되는 경우들이 많이 있습니다. 옵셔널 타입의 none을 사용하는 대신에 빈 배열로 사용하는 식으로요

2024-08-14 00:12 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/HistoryGrid/HistoryGridView.swift
> +  private let histories: [History]?
P5:
이 부분은 초기값을 nil로 설정하는 대신에 옵셔널을 다시 제거하고 빈 배열로 두면 옵셔널 바인딩 단계를 생략할 수 있다는 점에서 더 편할 것 같아요(굳이 수정 안해도 됨)

2024-08-14 00:22 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
>        }
오 ...!!! 좋은 것 같아요! 👍

2024-08-14 00:22 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
> +                  eventID: state.groupDetail?.recentEventDetail.id ?? -1
앗 네네 추후 리팩토링 하도록 하겠습니다~!

2024-08-14 00:22 UTC, merged