[Chore] 프로젝트 기초 작업
mash-up-kr/gabbangzip-iOS pull request #19
Opened 2024-05-26 16:20 UTC by zekexros

## 📌 Related Issue
- #18 

## 🚀 Description
- 커스텀 에러 프로토콜 정의
- Get 헬퍼 타겟 및 초기화 함수 추가
- RouteType 프로토콜 정의
- 미디어 에셋 관련 프로젝트의 특성을 고려한 MultipartFormDataKit 추가
- Tuist를 이용한 프로젝트 관리의 용이성을 위해 타입 및 함수 추가

## ✅ TODO
- [x] 에러 프로토콜 정의
- [x] Get 헬퍼 타겟 추가
- [x] RouteType 프로토콜 정의
- [x] MultipartFormDataKit 추가
- [x] Tuist를 이용한 프로젝트 관리의 용이성을 위해 타입 및 함수 추가

## 📸 Screenshot

## 📢 Notes
- Get 라이브러리를 활용하여 가빵집 프로젝트용 네트워크 객체를 만들까도 생각해보았지만 사실 Get 자체로도 이미 추상화가 잘 되어있고 자칫 애매하게 만들다간 Get의 사용성에 대한 편리함을 잃을 수 있겠다는 생각들도 인해 객체를 따로 만들지 않고 그냥 APIClient에서 바로 사용하기로 생각했습니다.
  - Route와 APIClient를 활용하여 아래와 같이 사용하면 될 듯 합니다
```swift
public enum HomeAPI {
  case logout(token: String)
}

extension HomeAPI: RouteType {
  public var baseURL: URL {
    return URL(string: "https://www.gabbang.com")!
  }
  
  public var path: String {
    switch self {
    case .logout:
      return "/logout"
    }
  }
  
  public var query: [(String, String?)]? {
    switch self {
    case .logout:
      return nil
    }
  }
  
  public var method: HTTPMethod {
    switch self {
    case .logout:
      return .post
    }
  }
  
  public var body: Encodable? {
    switch self {
    case .logout:
      return nil
    }
  }
  
  public var headers: [String: String]? {
    switch self {
    case let .logout(token):
      return [
        "Content-type": "application/json",
        "Authorization": "Bearer \(token)"
      ]
    }
  }
}
```
```swift
@DependencyClient
public struct HomeAPIClient: Sendable {
  var logout: @Sendable () async throws -> Void
}

extension HomeAPIClient: DependencyKey {
  public static var liveValue: HomeAPIClient {
    return HomeAPIClient(
      logout: {
        let route = HomeAPI.logout()
        let request = Request<Void>(route: route)
        
        do {
          try await APIClient(baseURL: route.baseURL).send(request)
        } catch {
          throw HomeAPIClientError(
            code: .getAPIError,
            underlying: error
          )
        }
      }
    )
  }
  
  public static var testValue: HomeAPIClient {
    return HomeAPIClient()
  }
}

extension DependencyValues {
  public var homeAPIClient: HomeAPIClient {
    get { self[HomeAPIClient.self] }
    set { self[HomeAPIClient.self] = newValue }
  }
}

public struct HomeAPIClientError: GabbangzipError {
  public var userInfo: [String: Any]
  public var code: APIResponseError
  public var underlying: Error?

  public init(
    userInfo: [String: Any] = [:],
    code: APIResponseError,
    underlying: Error? = nil
  ) {
    self.userInfo = userInfo
    self.code = code
    self.underlying = underlying
  }
}

public enum APIResponseError: Int {
  case getAPIError = 0
}

```
- 미디어 파일의 송수신 작업이 많아 보이는 프로젝트의 특성을 고려하여 Get에서 추천하는 [MultipartFormDataKit](https://github.com/Kuniwak/MultipartFormDataKit) 라이브러리를 추가하였습니다
- 휴먼 에러를 줄이기 위해 Tuist에서 타겟 및 디펜던시, 프로젝트 경로 등 기존엔 문자열로 넣던 것을 enum으로 관리하도록 수정해보았습니다
 
## 🧪 Testing(optional)

2024-05-27 00:54 UTC, GREENOVER requested changes
수고 많으셨습니다!
리뷰 코멘트와 더불어 현재 실제 활용되는 코드 예시를 보여주신 부분에서 의견 코멘트 전달드려봅니다 🙋🏻
1. 현재 APIClient에서 `APIClient(baseURL: route.baseURL)`는 대부분 공통이기에 각 프로퍼티에서 초기화 호출되는것보다 APIClient 액터 인스턴스를 공용적으로 사용할 수 있으면 어떨까요?
2. 통신 에러 시 현재 getAPIError로 모든 에러가 합쳐져 있을것 같은데, 세분화해서 던져주는게 어떨까요?
Get 라이브러리 내 APIClientDelegate 프로토콜에 `func client(_ client: APIClient, validateResponse response: HTTPURLResponse, data: Data, task: URLSessionTask) throws` 메서드가 있어 APIClientDelegate를 채택해 가빵집만의 네트워크딜리게이트를 만들어서 해당 메서드에서 status Code 상태값에 따라 에러 타입을 나눈다면 좀 더 명확할것 같습니다.
예를 들어 이런식이 될것 같아요.
```swift
class GabbangzipDelegate: APIClientDelegate {
  let decoder = JSONDecoder() 
  ...
  
  func client(
      _ client: APIClient,
      validateResponse response: HTTPURLResponse,
      data: Data,
      task: URLSessionTask
  ) throws {
    ... 
    // 단순 예시
    guard (200..<300).contains(response.statusCode) else {
      var errorModel: CommonErrorModel?
      do {
        errorModel = try decoder.decode(CommonErrorModel.self, from: data)
      } catch {
        ...
        errorModel = nil
      }
      throw NetworkError.unacceptableStatusCode(response.statusCode, errorModel)
    }
  }
  
// APIClient 인스턴스 생성 부
let client = APIClient(baseURL: ...) {
  $0.delegate = GabbangzipDelegate()
}
```
이런식으로가 아니라더라, 현재 샘플로 보여주신 catch 쪽에서 error가 DecodingError인지 다운캐스팅을 통해서 처리하는 식으로 여러 catch 구문을 활용해봐도 될것 같구요!
다만 그럴 경우엔, 매번 프로퍼티에서 catch 시 모두 작성해줘야하는 번거로움이 있어 위 코드와 같은 형태도 제안드려봤습니다 🙋🏻

3. 요건 어떻게 현업에서 사용하고 있는지 궁금한 포인트인데, HomeAPI.logout에 만약 body, 헤더들을 다 넣어 통신해야한다면 실제 HomeAPIClient를 구성할때 아래와 같은 식으로 매개변수가 많아지고, 사용도 복잡해질 수 있을것 같다고 느껴졌는데 실제 어떻게 사용하시나요?
```swift
@DependencyClient
public struct HomeAPIClient: Sendable {
  var logout: @Sendable (String, RequestModel, ...) async throws -> Void
}

extension HomeAPIClient: DependencyKey {
  public static var liveValue: HomeAPIClient {
    return HomeAPIClient(
      logout: { token, requestModel, ... in
        let route = HomeAPI.logout(token: token, requestModel: requestModel, ...)
        let request = Request<Void>(route: route)
        ...
}
```

질문이 길었네요! 수고많으셨습니다 😃

2024-05-27 00:54 UTC, GREENOVER commented on Projects/Core/Project.swift
> +		)
[p3] Services내에서도 모듈을 나누는것의 이점이 궁금합니다 🙋🏻
실제 피쳐 구현시 사실상 GetHelpers와 Error 모듈을 각각 임포트하지않고 통합된 Services를 디펜던시로 가져가면서 구현될것 같은데 서비스 내에서 이렇게 모듈을 나눠줌으로 복잡성이 좀 더 증가하지 않을까 싶어서요..!

2024-05-27 00:54 UTC, GREENOVER commented on Projects/Core/Services/GetHelpers/Get+extensions.swift
> +import Foundation
[p4] Get이 이미 Foundation을 채택하고 있기에, 제거되도 되지 않을까 합니다 🙋🏻

2024-05-27 00:54 UTC, GREENOVER commented on Tuist/ProjectDescriptionHelpers/TargetDependency+extensions.swift
> +extension TargetDependency {
[p1] 현재 전체적으로 Tuist 관련 swift 파일들도 2칸 인덴트를 사용하고 있어 2칸으로 맞추면 좋을것 같습니다 🙋🏻

2024-05-27 04:44 UTC, zekexros commented on Tuist/ProjectDescriptionHelpers/TargetDependency+extensions.swift
> +extension TargetDependency {
Xcode가 또... 수정 완료했습니다!

2024-05-27 11:44 UTC, zekexros commented on Projects/Core/Project.swift
> +		)
1. `HomeAPIClient`, `MyInfoAPIClient` `DatabaseClient` 등 다양한 서비스들을 모두 Services모듈에 포함시켜 Feature 모듈에서 사용하는 방안
2. `HomeFeature`, `MyInfoFeature` 등 각 Feature모듈에 필요한 Service모듈만을 골라서 dependency로 들고가는 방안

1번의 경우 모듈화 설계 및 기능 분리에 대한 고민으로 인해 개발 프로세스가 다소 지연될 수 있지만 빌드 시간을 단축할 수 있고 2번의 경우 이와 반대로 빠른 개발 프로세스과 길어진 길어지는 빌드 시간을 예상했습니다.

고민하다 결국 2번을 염두하고 모듈을 나눠보았는데요, 코멘트를 보고 든 생각은 우선 개발의 편의성을 위해 Services로 진행하고 Service들의 분리는 후순위로 미루는 것이 좋겠네요(지금처럼 폴더 구조 잘 지키고 다른 라이브러리에 대한 의존성을 적절히 관리한다면 향후 분리하는 과정에서도 큰 어려움은 없을 듯 합니다)

2024-05-27 11:50 UTC, GREENOVER commented on Projects/Core/Project.swift
> +		)
ㅇㅈㅌㅇ👍

2024-05-27 12:21 UTC, serena0720 reviewed
구조 고민하고, 구현하시느라 너무 고생하셨습니다💪

개인적으로 궁금해서 질문남깁니다.
Router인 HomeAPI는 enum으로, APIClient는 struct로 구현한 이유가 무엇인가요?
특히 APIClient의 경우 extension에 구현하신 내용을 참고하여 짐작했을 때, logout부분만 정의부에 두고 나머지는 구현부에 두어 protocol로 해도 되는 게 아닌가하는 궁금증이 들어 여쭤봅니다

```swift
public enum HomeAPI {
  case logout(token: String)
}
```

```swift
@DependencyClient
public struct HomeAPIClient: Sendable {
  var logout: @Sendable () async throws -> Void
}
```

2024-05-27 12:21 UTC, serena0720 commented on Projects/Core/Services/GabbangzipError/GabbangzipError.swift
> +}
P5: 해당 프로토콜은 추후 Error 타입에 적용하기 위한 추상화 객체인건가요?

2024-05-27 12:21 UTC, serena0720 commented on Projects/Core/Services/GabbangzipError/GabbangzipError.swift
> +    return userInfo
P5: return 앞에서 개행하는 컨벤션 어떤가요

2024-05-27 12:21 UTC, serena0720 commented on Projects/Core/Services/GabbangzipError/GabbangzipError.swift
> +  public var errorCode: Int { self.code.rawValue }
P5: 한줄은 return 안 붙이고, 2줄 이상은 return 붙이는 거로 컨벤션 통일하는 걸까요?

2024-05-27 12:24 UTC, GREENOVER commented on Projects/Core/Project.swift
> +		)
동의합니다~
실제로, 현재 위 구조에서는 HomeAPI / HomeAPIClient를 Core에서 파일로 생성하여 작업할때, Services내에 존재하더라도 Get+extensions과 Error 모듈을 임포트해야하기도 해서 조금 더 번거로울 순 있을것 같습니다.
아니면 차라리 Service > Network 모듈로 만들어서 네트워크에 관련된거는 다 다뤄도 괜찮을 수 있다고도 보이고, 그냥 Services에서 말씀하신것처럼 우선은 다 가져가도 괜찮아보이긴합니다!

실제로 Feature에선 이제 Services 만 채택하여 아래와 같이 사용되면 임포트하는 경우의 수도 적어지지 않을까 싶어요.

그냥 VM으로 예시를 들어봅니다!
```swift
import Services

class HomeViewModel: ObservableObject {
  private let homeAPIClient: HomeAPIClient
  
  init(homeAPIClient: HomeAPIClient = HomeAPIClient.liveValue) {
    self.homeAPIClient = homeAPIClient
  }
  
  func logout(token: String) {
    Task {
      do {
        try await homeAPIClient.logout(token)
        ...
      } catch {
        DispatchQueue.main.async {
          ...
        }
      }
    }
  }
}
```

즉, Service에서 그룹 구조는 이렇게도 될 수 있지 않을까 생각했습니다.

1. Service(모듈) > Network(폴더) > APIs (폴더), APIClients (폴더), Extension, Error 들
- 여기서 APIs, APIClients 폴더에는 HomeAPI, HomeAPIClient들이 나눠서 들어가거나 하나로 합쳐도 무방하긴 해보입니다.
2. Services (모듈) > Network (모듈) > APIs (폴더), APIClients (폴더), Extension, Error 들
- 그럼 실제로 Feature단에서는 네트워킹을 위해 Services를 다 가져가지 않고 Network만 채택해서 사용해도 될것 같았어요.

+또한, APIClientError들도 각각 HomeAPI 등처럼 나누지 않고 공통으로 GabbangzipError를 채택해서 NetworkAPIError를 만들어서 사용해도 좋아보입니다!

2024-05-27 12:27 UTC, GREENOVER commented on Projects/Core/Services/GabbangzipError/GabbangzipError.swift
> +  public var errorCode: Int { self.code.rawValue }
해당 코드에서 return을 붙이지 않은건 한줄이여서가 아닌, swift 특성상 연산 프로퍼티의 경우 단일 표현으로 될 경우 return을 생략하여 간결하게 사용할 수 있어서라고 보입니다 🙋🏻
아래 errorUserInfo의 경우 단일 표현이 아니기에 명시적으로 return을 해주어야 컴파일러가 어디서 해당 값이 리턴되는지 파악할 수 있습니다..!

2024-05-27 14:45 UTC, GREENOVER commented on Projects/Core/Project.swift
> +      sources: ["Services/**/*.*"],
```suggestion
      sources: ["Services/**"],
```
로도 되지 않나요~?

2024-05-27 14:45 UTC, GREENOVER commented on Projects/Core/Services/GetHelpers/RouteType.swift
> +import Foundation
놓쳤는데 여기서도 Foundation이 필요없을것 같아요 😃

2024-05-27 15:11 UTC, zekexros commented on Projects/Core/Project.swift
> +      sources: ["Services/**/*.*"],
그러네요! 수정하겠습니다🙋‍♂️

2024-05-27 15:13 UTC, zekexros commented on Projects/Core/Services/GetHelpers/RouteType.swift
> +import Foundation
URL 타입으로 인해 이 부분은 그대로 두겠습니다🙇‍♂️

2024-05-27 15:59 UTC, zekexros commented
@GREENOVER 
> 현재 APIClient에서 `APIClient(baseURL: route.baseURL)`는 대부분 공통이기에 각 프로퍼티에서 초기화 호출되는것보다 APIClient 액터 인스턴스를 공용적으로 사용할 수 있으면 어떨까요?

- 이 코멘트를 보고 앞으로 다양하게 생겨날 ~~APIClient의 각 엔드포인트를 호출할 때마다 Get의 APIClient 객체를 인스턴스화하고 엔트포인트의 호출이 끝날 땐 다시 인스턴스 해제가 되는 것을 고려할 때 불필요한 **오버헤드**가 발생한다는 점을 깨달았습니다. 심지어 APIClient가 reference type인 것을 생각한다면 싱글턴 객체를 활용하는 것이 확실히 더 낫겠더군요.
- 어떤 방식으로 싱글톤 패턴을 사용할까 고민한 끝에 `NetworkManager`에 `APIClient` 타입 프로퍼티를 선언하였습니다. 해당 타입이 처음 사용되는 시점에 단 한 번 초기화되고 이후에는 프로그램이 종료될 때까지 메모리에 유지됨으로써 인스턴스 생성 및 해제되며 발생하는 오버헤드를 줄였고, APIClient의 메서드들은 **그대로** 사용할 수 있습니다. TCA의 Dependency를 이용하면 **테스트 코드** 작성에도 문제가 없습니다. struct로 만든 이유는 class, actor로 만들 이유가 없어서 그렇습니다

<br><br>

> 통신 에러 시 현재 getAPIError로 모든 에러가 합쳐져 있을것 같은데, 세분화해서 던져주는게 어떨까요?
> Get 라이브러리 내 APIClientDelegate 프로토콜에 `func client(_ client: APIClient, validateResponse response: HTTPURLResponse, data: Data, task: URLSessionTask) throws` 메서드가 있어 APIClientDelegate를 채택해 가빵집만의 네트워크딜리게이트를 만들어서 해당 메서드에서 status Code 상태값에 따라 에러 타입을 나눈다면 좀 더 명확할것 같습니다.
> 예를 들어 이런식이 될것 같아요.

- 이 부분을 보고 APIClient가 어떤 에러를 어떻게 던지는 지 확인해봤는데요, 말씀해주신 것처럼 APIClientDelegate를 활용하여 자체적으로 에러를 추가적으로 구조화를 시켜야 디버깅하기 편할 것 같다는 것은 생각이 들었고 그것이 APIClientDelegate를 만든 의도인 것 같기도 합니다. 따라서 APIClientDelegate를 채택하는 Delegate를 만들고 4~500대 및 네트워크 실패에 대한 에러를 던지도록 구현하였습니다.
- 여기에 추후 reqeust와 response타입을 바탕으로 로깅을 구현하면 개발의 편의성이 크게 증가할 것 같습니다.

<br><br>

> 이런식으로가 아니라더라, 현재 샘플로 보여주신 catch 쪽에서 error가 DecodingError인지 다운캐스팅을 통해서 처리하는 식으로 여러 catch 구문을 활용해봐도 될것 같구요!
> 다만 그럴 경우엔, 매번 프로퍼티에서 catch 시 모두 작성해줘야하는 번거로움이 있어 위 코드와 같은 형태도 제안드려봤습니다 🙋🏻

- 디코딩 에러 같은 경우는 NetworkManager의 underlying에 기본 제공 타입인 DecodingError로 들어올 것으로 예상하여 디코딩 에러 타입을 따로 만들지 않았습니다. 예상이 틀렸거나 더 나은 방안이 있다면 추후 수정해보겠습니다.

<br><br>

> 요건 어떻게 현업에서 사용하고 있는지 궁금한 포인트인데, HomeAPI.logout에 만약 body, 헤더들을 다 넣어 통신해야한다면 실제 HomeAPIClient를 구성할때 아래와 같은 식으로 매개변수가 많아지고, 사용도 복잡해질 수 있을것 같다고 느껴졌는데 실제 어떻게 사용하시나요?

- 엔드포인트에서 필요로하는 변수가 많을 때에는 body에 들어갈 정보들을 Encodable을 채택하는 별도의 모델을 만들어 전달하여 매개 변수를 줄이는 방안으로 어느 정도 해소할 것으로 보입니다
  (저도 자주 사용하는 타입이거나 body에 필요로하는 정보가 많을 경우 모델로 따로 만들어 사용하는데 이 때 불편함은 크게 못느꼈습니다)

2024-05-27 23:27 UTC, GREENOVER approved these changes
고생 많으셨습니다!
훨씬 보완되고 깔끔해졌네요ㅎㅎ
간단히 코멘트 몇개만 남기면서 어프로브하겠습니다 🙋🏻

아..! PR 재 질문에 리코멘트로 남겨주신 마지막은 body 객체는 물론 인코딩할 RequestModel로 만들어서 관리하는것은 당연하고 그 외 호옥시나 query나 header에 많은 필드를 요할경우
```swift
...
public struct HomeAPIClient: Sendable {
  var logout: @Sendable (String, Int, String, ...) async throws -> Void
}
...
```
처럼 필드 타입이 들어가고 사용부에서도
```swift
...
return HomeAPIClient(
      logout: { token, time, value, ... in
        let route = HomeAPI.logout(token: token, time: time, ...)
        let request = Request<Void>(route: route)
...
```
처럼 비대해질텐데 휴먼 에러가 나기 좋아 보이는 환경이라 다른 방법이 있는지 궁금해서 여쭤봤었습니다.
일단 이렇게 사용되는게 맞다면 킵고잉해봐도 될것 같아요!
극한까지 생각해봐서 그런거고 코드의 허점은 없다고 생각합니다.

다시 한번 수고 많으셨어요 👍

2024-05-27 23:27 UTC, GREENOVER commented on Projects/Core/Services/GetHelpers/RouteType.swift
> +  var baseURL: URL { get }
[p1] baseURL은 이제 NetworkManager/APIClient 초기화 시 넣어주기에 사용되지 않을것 같은데 사용될 여지가 있나요~? 🙋🏻

2024-05-27 23:27 UTC, GREENOVER commented on Projects/Core/Services/GetHelpers/RouteType.swift
> +import Foundation
[p5] 오 놓쳤네요!
만약 아래 코멘트가 반영되면 같이 반영되어도 될것 같네요ㅎㅎ

2024-05-27 23:27 UTC, GREENOVER commented on Projects/Core/Services/GetHelpers/NetworkManager.swift
> +        string: ""
[ p5] 추후 다른분들이 먼저 작업하실때 여기에 baseURL 설정하는거 혹시나 놓치지 않도록 주석을 다는건 어떨까요? 🙋🏻

2024-05-28 00:19 UTC, zekexros commented on Projects/Core/Services/GetHelpers/NetworkManager.swift
> +        string: ""
좋은 생각입니다😀

2024-05-28 00:19 UTC, zekexros commented on Projects/Core/Services/GetHelpers/RouteType.swift
> +  var baseURL: URL { get }
이젠 필요가 없어졌네요! 삭제하겠습니다

2024-05-28 00:25 UTC, zekexros commented on Projects/Core/Services/GabbangzipError/GabbangzipError.swift
> +    return userInfo
가독성을 높이기 위해서일까요? 가독성 향상보단 개행에 신경써야하는 부분이 더 크게 느껴져서 저는 불필요하다고 보는데 다른 분들의 의견은 어떤가요?
@GREENOVER  @hope1053

2024-05-28 00:26 UTC, zekexros commented on Projects/Core/Services/GabbangzipError/GabbangzipError.swift
> +}
네 맞습니다👍

2024-05-28 00:31 UTC, zekexros commented
@serena0720 
> 개인적으로 궁금해서 질문남깁니다.
Router인 HomeAPI는 enum으로, APIClient는 struct로 구현하고자 생각하신 이유가 무엇인가요?
특히 APIClient의 경우 extension에 구현하신 내용을 참고하여 짐작했을 때, logout부분만 정의부에 두고 나머지는 구현부에 두어 protocol로 해도 되는 게 아닌가하는 궁금증이 들어 여쭤봅니다

[Moya](https://github.com/Moya/Moya?tab=readme-ov-file)에서 route를 enum으로 관리하는 방식을 보고 매우 편리해보여 따라 만든 것입니다.
APIClient가 struct인 이유에 대한 답변은 [Point-free](https://www.pointfree.co/blog/posts/120-macro-bonanza-dependencies)의 설명으로 갈음하는 것이 더 좋을 것 같습니다👍

2024-05-28 00:33 UTC, GREENOVER commented on Projects/Core/Services/GabbangzipError/GabbangzipError.swift
> +    return userInfo
저도 사실 지금도 가독에선 자연스러워서 꼭 너무 강제적인 컨벤션으로 가져가지 않고 개발에 따라서 자연스럽다고 느껴지는걸로 가져가면 좋을것 같아요~

2024-05-28 01:35 UTC, GREENOVER approved these changes
대장정 수고 많으셨습니다!

2024-05-28 02:51 UTC, serena0720 approved these changes

2024-05-28 23:30 UTC, merged