[Infra] fastlane 세팅
mash-up-kr/gabbangzip-iOS pull request #20
Opened 2024-05-29 09:29 UTC by hope1053

## 📌 Related Issue
- #10 

## 🚀 Description
앱 생성 및 fastlane 설정 진행했습니다.

## ✅ Done
- [x] AppStore Connect > 앱 생성 및 팀원 초대
- [x] 개발자 계정 팀 ID 설정 및 공유
- [x] 프로비저닝 및 인증서 파일 공유
- [x] fastlane match 작업 추가

## 📸 Screenshot
<img width="740" alt="image" src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/22907483/1da26058-c22c-4f6f-b293-7ddd4365eeb4">
Provisioning profile 뜨는거까지는 확인했습니다.

## 📢 Notes
fastlane 비밀번호는 노션에 작성해놨습니다! [해당 링크](https://www.notion.so/zip-690cde6e03494013b683ad6d9ccc4772?pvs=4)에서 확인하시면 됩니다.
처음 세팅해본거라 제대로 됐는지 모르겠네요 🥲 피드백 대환영입니다 ..
 
## 🧪 Testing(optional)

2024-05-29 10:01 UTC, GREENOVER commented
```
fastlane match development --readonly 
fastlane match appstore --readonly 
```
다른 팀원들도 초기 bootstrap 시 인증서를 가져오도록 해당 스크립트도 추가하면 어떨까요?

2024-05-29 10:25 UTC, GREENOVER requested changes
수고하셨습니다 😃
현재 추가된 코드 자체와 cert Git레포 관련하여서는 문제가 없어 보이지만, 이 위 PR 코멘트로 남겨둔 조금 더 편리하게 팀원들이 인증서를 얻어올 수 있도록 해당 PR에서 작업해주시면 좋을것 같아요.
추가로, 실제 fastlane 명령어를 통해 prod 배포도 한번 테스트 해보시면 어떨까요?

2024-05-29 10:56 UTC, GREENOVER commented on fastlane/.env.default
> +ITC_TEAM_ID="123345060"
해당 부분에 APPLE_ID 값이 존재하지 않는데,
AppFile에서 해당 env 파일을 바라보며 색인하는걸로 변경되었기에 아마 fastlane match를 돌릴때 경고가 나올거 같아요.
추가가 필요해보입니다~

2024-05-29 11:13 UTC, GREENOVER commented
@serena0720 @zekexros 
cc. @hope1053 

![스크린샷 2024-05-29 오후 8 07 51](https://github.com/mash-up-kr/gabbangzip-iOS/assets/72292617/f21b43c5-b24a-42f4-b637-9c8b19c8763e)
readonly 시 이 에러를 만나신다면 아래 스텝으로 진행하시면 됩니다.

1. 에러 메시지에서 친절히 알려주는 실행 명령어 입력 (터미널에서)
```
git clone https://github.com/hope1053/Gabbangzip-cert.git /var/folders/1h/2hn8slfx1fx0jh_j8yc326zr0000gq/T/d20240529-76034-u4joq5
```
2. 아래와 같이 userName에는 본인 깃헙 ID / Password에는 본인의 PAT (Personal Access Token)으로 입력합니다.
만약 PAT 없으시면 생성하세요!
![스크린샷 2024-05-29 오후 8 09 17](https://github.com/mash-up-kr/gabbangzip-iOS/assets/72292617/ae4b900b-bb5b-48ab-b4bb-ab5c083eedf0)

3. 다시 fastlane match development --readonly를 레포에서 실행사면 중간 중간 비밀번호 설정하는곳에 노션에 기재된 fastlane 패스워드로 입력

4. 정상적으로 모두 설정이 되면 프로젝트 실행 후 타겟에서 오토 사이닝 푸신 후 Provisioning Profile을 셀렉해보시면 아래와 같이 나온다면 정상입니다.
![스크린샷 2024-05-29 오후 8 12 23](https://github.com/mash-up-kr/gabbangzip-iOS/assets/72292617/5eac02e8-454a-4cbf-bf28-3801b0e70227)

2024-05-29 11:31 UTC, GREENOVER commented
하나만 더...
Gabbangzip.shared.xcconfig에서 DEVELOPMENT_TEAM 값 변경하시고 주석도 제거해야 합니다.

2024-05-30 00:30 UTC, GREENOVER commented
위 코멘트중 아래 항목 반영해서 푸시했습니다.

1. Gabbangzip.shared.xcconfig에서 DEVELOPMENT_TEAM 값 변경하시고 주석도 제거
2. bootstrap 시 development Cert, Provisioning 겟해올 수 있도록 스크립트 추가
3. 리드미 최신화
4. FastFile 내 배포 시 match 명령어 추가 & .dev -> -dev 오탈자 수정

2024-05-31 00:00 UTC, GREENOVER approved these changes

2024-05-31 03:08 UTC, zekexros approved these changes
LGTM

2024-05-31 03:08 UTC, merged

2024-05-31 08:28 UTC, chansooo commented
LGTM