[Feat] AppDelegate 추가, AppDelegateReducer 구현 및 여러 Client들 구현
mash-up-kr/gabbangzip-iOS pull request #34
Opened 2024-06-08 04:58 UTC by zekexros

## 📌 Related Issue
- #33 
## 🚀 Description
- AppDelegate 추가
- AppDelegateReducer로 푸시 알림 요청 및 처리 구현
- 다양한 Dependencies 구현
  - Bundle
  - UserDefaults
  - UserNotification
- 생산성 향상을 위해 Xcode Templates 추가

## ✅ Done
- [x] Xcode Templates 추가
- [x] AppDelegate 추가
- [x] AppDelegateReducer 구현
- [x] BundleClient 구현
- [x] UserDefaultsClient 구현
- [x] UserNotificationClient 구현
- [x] 푸시 알림 요청 및 푸시 알림 처리 구현

## 📸 Screenshot

## 📢 Notes
 
## 🧪 Testing(optional)

2024-06-10 03:15 UTC, GREENOVER requested changes
고생 많으셨습니다!
리뷰를 하다보니 짜잘한것도 있어 조금 양이 많아보이는데, 한번 점검차 보시면 좋을것 같아요 🙋🏻
혹시 제가 잘못알고 있는 부분들도 있다면 의견 부탁드립니다 😀

2024-06-10 03:15 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateReducer.swift
> +        return .run { send in
p5. 추후 더 다른 처리를 위해 send 인자를 명시적으로 남겨둔건가요?

2024-06-10 03:15 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateReducer.swift
> +          completionHandler([.banner, .badge, .sound])
p5. 메인 스레드에서 실행을 보장하지 않아도 괜찮은가요?
시스템적으로 willPresentNotification이 메인 스레드에서 호출되도록 보장될거라 여기서의 처리는 필요없어 보이긴하는데 혹시 다른 부분을 알고 계시면 공유 부탁드립니다 👍

2024-06-10 03:15 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateReducer.swift
> +  @Dependency(\.userNotificationClient) var userNotificationClient
p5. private하게 범위를 가져갔을때 문제가 없다면 private해도 되지 않을까 싶습니다 🙋🏻

2024-06-10 03:15 UTC, GREENOVER commented on Projects/Core/Services/UserDefault/UserDefaultsClient.swift
> +  }
p2. 실제로 에러라곤 볼 수 없지만, userDefaults 내 값이 없을 경우 nil이 반환될텐데 이에 대한 판단을 에러 타입을 담아 Result로 반환하는것은 어떤가요? 🙋🏻
즉, 옵셔널 타입을 반환하는것보다 Result로 반환하여 에러를 던져주는 식이면 어떨까 싶습니다.

2024-06-10 03:15 UTC, GREENOVER commented on Projects/Core/Services/UserDefault/UserDefaultsClient.swift
> +//  UserDefaultsClient.swift
p5. 정말 사소하지만 상위 폴더명이 UserDefaults로 통일되면 어떨까요?

2024-06-10 03:15 UTC, GREENOVER commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +//  UserNotificationClient.swift
p5. 이것도 사소하지만, UserDefaults와 같은 맥락에서 파일/폴더명이 UserNotifications이여도 통일성 있어 보이는데 어떤가요?
기준은 프레임워크 명칭을 따르는걸로 잡았습니다.

2024-06-10 03:15 UTC, GREENOVER commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +            _ = delegate
p3. stream 종료 시점에 delegate 자체를 nil로 주어 메모리 누수를 방지하는건 어떤가요?

2024-06-10 03:15 UTC, GREENOVER commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +          let delegate = UserNotificationClient.Delegate(continuation: continuation)
```suggestion
          let delegate = Delegate(continuation: continuation)
```
p2. Delegate 클래스가 구조체 내부에 정의되어 중첩되 있기에 해당 구조체를 명시적으로 붙여서 사용하지 않아도 충분할것 같습니다 🙋🏻
해당 Delegate를 사용하는 외부 타입에서 UserNotificationClient의 Delegate를 접근해야한다면 필요할 순 있지만 내부에서는 Delegate로 사용하는것이 외부에서 직접적인 생성 및 접근을 막을 수 있어 캡슐화를 강화할 수 있지 않을까해요.

2024-06-10 03:15 UTC, GREENOVER commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +  public enum DelegateEvent {
p5. DelegateEvent라는 네이밍이 조금 모호하다고 생각이 드는데 UserNotificationsEvent와 같이 조금 더 명확하면 어떨까요?

2024-06-10 03:15 UTC, GREENOVER commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +  fileprivate class Delegate: NSObject, UNUserNotificationCenterDelegate {
p5. 여기서도 조금 더 명확하게 네이밍을 가져가도 좋지 않을까 싶습니다 🙋🏻

2024-06-10 03:15 UTC, GREENOVER commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +
```suggestion
```
p5. 한줄 개행이 더 된것 같습니다.

2024-06-10 03:15 UTC, GREENOVER commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +        )
p2. 에러가 나는 경우도 있지 않을까요?
granted와 error를 인자로 받아 적절히 처리해도 좋을것 같습니다 🙋🏻

2024-06-10 03:15 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateReducer.swift
> +          self.userNotificationClient.requestAuthorization()
p2. requestAuthorization전에 권한 요청에 대한 처리가 이미 되어 있을 수 있기에, getAuthorizationStatus로 확인 후 필요시에만 권한 요청하는것이 어떤가요~?
즉, notDetermined일때만 요청하는것이 적절해보여서요!

2024-06-10 03:15 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateReducer.swift
> +          completionHandler([.banner, .badge, .sound])
p5. 추가로, 이미  UserNotificationClient의 requestAuthorization에서 authOptions으로 요청하고 있는것으로 보이는데, 그렇다면 여기서 컴플리션으로 처리하지 않아도 되는거 아닌지 문의드립니다 🙋🏻

2024-06-10 08:32 UTC, zekexros commented on Projects/App/Sources/AppDelegateReducer.swift
> +        return .run { send in
향후 다른 처리를 위해서가 아닌 단순히 run 메서드를 사용할 때 send를 대부분 사용했기에 습관적으로 항상 명시적으로 두었습니다.
run메서드 내에서 send 사용 여부에 따라 와일드카드를 사용할지 말지는 앞으로 같이 정하면 될 듯합니다.

2024-06-11 07:24 UTC, zekexros commented on Projects/App/Sources/AppDelegateReducer.swift
> +          completionHandler([.banner, .badge, .sound])
> 메인 스레드에서 실행을 보장하지 않아도 괜찮은가요?

네 completionHandler를 호출하는 부분은 메인 스레드에서 호출하지 않아도 상관 없습니다(공식 문서에서는 메인 스레드 호출을 보장해줘야 한다는 내용이 없기도 하고 실제 작동시켰는데 별 문제가 발생하진 않았습니다. 아마 UI Update와는 상관 없고 그저 시스템에게 정보 제공 용도이기에 메인 스레드로 제한을 두지 않은 것으로 추측됩니다)

> UserNotificationClient의 requestAuthorization에서 authOptions으로 요청하고 있는것으로 보이는데, 그렇다면 여기서 컴플리션으로 처리하지 않아도 되는거 아닌지 문의드립니다 🙋🏻

애플 공식 문서를(아래) 보니 찬우님 말씀대로 UNUserNotificationCenter의 `requestAuthorization` 메서드의 옵션으로 [.alert, .badge, .sound]를 넣어줬던 것과 willPresent메서드의 completionHandler의 옵션은 동일하므로 생략해도 되겠네요

> If you do not provide a delegate at all for the [UNUserNotificationCenter](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter) object, the system uses the notification’s original options to alert the user.

2024-06-11 08:46 UTC, GREENOVER commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +  public enum DelegateEvent {
p2. 지금은 필요없지만, Swift 6 대응을 원하시면 해당 타입이 Sendable을 채택해야 빌드 에러가 발생하지 않을것 같네요!

2024-06-11 11:09 UTC, zekexros commented on Projects/App/Sources/AppDelegateReducer.swift
> +  @Dependency(\.userNotificationClient) var userNotificationClient
좋습니다 👍

2024-06-12 00:51 UTC, dev-rin commented on Projects/Core/Services/UserDefault/UserDefaultsClient.swift
> +      string: unimplemented("\(Self.self).string"),
unimplemented는 추후 테스트 실패가 유발되고 해당 부분에 대한 테스트를 작성하기 위해 사용하신건가요 ?! 사용하는 이유가 궁금해서 여쭤봅니다

2024-06-12 00:58 UTC, dev-rin commented on Projects/App/Sources/AppDelegateReducer.swift
> +        return .run { @MainActor send in
요 부분 왜 MainActor에서 실행되는건가요...?!

2024-06-12 01:05 UTC, dev-rin approved these changes
수고하셨습니다 🙇‍♀️

2024-06-12 06:56 UTC, zekexros commented on Projects/App/Sources/AppDelegateReducer.swift
> +          completionHandler([.banner, .badge, .sound])
다시 확인한 결과, `completionHandler`는 알림의 표시 옵션을 포함하여 호출되어야 합니다. 그렇지 않으면 'PresentationOptionNone' 옵션으로 설정되어 Foreground 상태에서는 알림이 안보인다고 하네요
> If your delegate does not implement this method, the system behaves as if you had passed the [UNNotificationPresentationOptionNone](https://developer.apple.com/documentation/usernotifications/unnotificationpresentationoptionnone) option to the completionHandler block.

2024-06-12 07:17 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateReducer.swift
> +          completionHandler([.banner, .badge, .sound])
그렇네요.
기본적으로 앱이 포그라운드에 있다면 알림이 표시되지 않기에 핸들러로 표시해줘야하군여 👍

2024-06-12 07:21 UTC, zekexros commented on Projects/Core/Services/UserDefault/UserDefaultsClient.swift
> +  }
좋은 아이디어입니다!
다만, 디펜던시의 각 엔드포인트에 대한 반환 타입을 `Result`로 설정하기보다는 원시 타입(`String`, `Int`, `Float`)을 반환하도록 하고 Reducer 안에서 Result로 감싸 처리하는 것이 테스트 코드 작성 시 override할 때 더 간결하고, 가독성이 높을 것 같습니다!!
다양한 TCA 예제 앱에서도 활용하는 방식이기도 하구요!

2024-06-12 07:24 UTC, zekexros commented on Projects/Core/Services/UserDefault/UserDefaultsClient.swift
> +//  UserDefaultsClient.swift
알려주셔서 감사합니다! 제가 놓쳤네요!

2024-06-12 07:26 UTC, zekexros commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +//  UserNotificationClient.swift
좋은 기준이 생겼네요👍 앞으로 프레임워크 명칭을 참조하여 폴더 이름을 지정하겠습니다.

2024-06-12 07:36 UTC, zekexros commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +            _ = delegate
`UNUserNotificationCenter`의 `delegate`는 약한 참조로 되어있어 AsyncStream이 종료된 후 onTermination 클로저가 실행되어 delegate에 대한 참조가 더이상 아무것도 없게되어 인스턴스가 해제되고 메모리 누수가 발생하지 않을 것으로 보았습니다!

2024-06-12 07:54 UTC, zekexros commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +          let delegate = UserNotificationClient.Delegate(continuation: continuation)
그렇군요😯 말씀하신 대로 앞에 UserNotificationClient를 빼고 Delegate로 시작하는 것이 더 좋아보입니다

2024-06-12 07:56 UTC, GREENOVER commented on Projects/Core/Services/UserDefault/UserDefaultsClient.swift
> +  }
오 너무 좋네요!
저도 해당 방식으로 작업 수정하겠습니다 🫡

2024-06-12 08:02 UTC, GREENOVER commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +            _ = delegate
`weak var delegate: (any UNUseNotificationCenterDelegate)? { get set }`
앗 제가 꼼꼼히 못봤군요 🥲 확인 감사합니다!

2024-06-12 08:04 UTC, zekexros commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +  public enum DelegateEvent {
p5. DelegateEvent라는 네이밍이 조금 모호하다고 생각이 드는데 UserNotificationsEvent와 같이 조금 더 명확하면 어떨까요?
```swift
struct AppDelegateReducer {
  enum Action {
    case didFinishLaunching
    case userNotifications(UserNotificationClient.UserNotificationsEvent)
  }
}
```
말씀하신대로 타입명을 수정하여 적용해본 결과, Reducer에서 해당 타입을 불러올 때 타입 이름이 중복되어 보이는 점이 개인적으론 조금 어색하게 느껴집니다. 어떤가요?!

2024-06-12 08:05 UTC, zekexros commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +  public enum DelegateEvent {
> p2. 지금은 필요없지만, Swift 6 대응을 원하시면 해당 타입이 Sendable을 채택해야 빌드 에러가 발생하지 않을것 같네요!

그렇군요! 지금부터 미리 Sendable을 채택하여 기술 부채를 줄이면 좋을 것 같습니다👍

2024-06-12 08:06 UTC, GREENOVER commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +  public enum DelegateEvent {
그러네요 별개로 보면 명확하지만 케이스 시그니쳐에 붙인다면 기존이 더 나은것 같습니다 👍
킵고잉 해주시죠ㅎㅎ

2024-06-12 08:09 UTC, zekexros commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +  fileprivate class Delegate: NSObject, UNUserNotificationCenterDelegate {
고민 끝에 타입 이름의 길이와 이름에 담겨야 할 정보를 고려하여 `NotificationCenterDelegate`라는 이름을 지어봤는데 어떤가요?!

2024-06-12 08:11 UTC, zekexros commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +
수정 완!

2024-06-12 08:12 UTC, GREENOVER commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +  fileprivate class Delegate: NSObject, UNUserNotificationCenterDelegate {
동의합니다 👍

2024-06-12 08:40 UTC, zekexros commented on Projects/Core/Services/UserNotification/UserNotificationClient.swift
> +        )
문서를 찾아보니 해당 메서드에 대해 비동기 버전도 제공하고 있더군요. 더 간결하게 그리고 error처리 쉽게 할 수 있도록 수정했습니다

2024-06-12 08:48 UTC, zekexros commented on Projects/App/Sources/AppDelegateReducer.swift
> +          self.userNotificationClient.requestAuthorization()
좋은 제안입니다! 수정하겠습니다👍

2024-06-12 09:04 UTC, zekexros commented on Projects/Core/Services/UserDefault/UserDefaultsClient.swift
> +      string: unimplemented("\(Self.self).string"),
`unimplemented`로 선언하면 테스트 모듈에서 어떤 엔드 포인트가 재정의하지 않고 호출되었는지 테스트 실패와 정확한 에러 메시지로 쉽게 알 수 있다는 장점이 있습니다. 그러면 메시지를 보고 해당 엔드포인트만 재정의를 하고 또 testValue로 간단하게 초기화할 수 있어 빠르게 테스트 코드를 작성하는데 의미가 있지 않을까 생각합니다

2024-06-12 09:07 UTC, zekexros commented on Projects/App/Sources/AppDelegateReducer.swift
> +        return .run { @MainActor send in
여기에는 주로 앱 시작 시 초기화 및 설정이 필요한 작업들이 포함되는데, 이러한 작업들을 백그라운드 스레드에서 실행할 경우 작업 처리 시점이 늦어져 초기화 전에 다른 리듀서에서 해당 메서드를 호출하여 런타임 에러가 발생하는 경우가 종종 있었습니다. 그 때 메인 스레드로 수정하여 해결한 경험이 있었는데 좋은 아이디어 있으면 제시해주세요 👍

2024-06-12 09:18 UTC, zekexros commented
`UserNotificationClient`에서 `getAuthorizationStatus`와 `getAuthorizationStatus`에 초기값을 설정한 이유에 대해 궁금해하실 것 같아 참고할 문서를 전달드립니다. >> [@DependencyClient macro](https://swiftpackageindex.com/pointfreeco/swift-dependencies/main/documentation/dependencies/designingdependencies#DependencyClient-macro)

요약하자면 컴파일러 버그때문입니다

2024-06-12 09:29 UTC, GREENOVER approved these changes
수고 많으셨습니다! 👍

2024-06-12 09:47 UTC, GREENOVER approved these changes

2024-06-12 09:47 UTC, GREENOVER commented on Projects/Core/Services/Bundle/BundleClient.swift
> +public struct BundleClient {
여기도 `@DependencyClient` 매크로 어노테이션을 사용하고
testValue를 다른 기조에 맞게 가는것도 좋아보이는데 어떤가요?
전해주신 공식문서를 보니 Self()로 해도 되겠다고 보이네요 👀

2024-06-12 10:15 UTC, zekexros commented on Projects/Core/Services/Bundle/BundleClient.swift
> +public struct BundleClient {
좋습니다! 제가 매크로 적용하는 것을 깜빡했네요!!

2024-06-13 00:21 UTC, hope1053 approved these changes

2024-06-13 01:16 UTC, serena0720 approved these changes

2024-06-13 01:17 UTC, merged