[Chore] tuist 적용 및 프로젝트 파일 생성
mash-up-kr/gabbangzip-iOS pull request #5
Opened 2024-05-19 06:32 UTC by serena0720

## 📌 Related Issue
- 이슈 #4 

## 🚀 Description
- Tuist 프로젝트 셋팅

## ✅ Done
- [ ] Package Dependency 생성 - TCA, Nuke, Lottie, Get
- [ ] 프로젝트 생성

## 📸 Screenshot

## 📢 Notes
 
## 🧪 Testing(optional)

2024-05-19 15:33 UTC, zekexros reviewed
`MyApp/`의 파일들을 루트 디렉토리로 옮겨도 될 듯 합니다(옮긴 후 `MyApp`폴더를 한 개로 유지)

2024-05-19 15:33 UTC, zekexros commented on MyApp/Tuist/Package.swift
> +)
P1: Nuke와 Get의 버전을 `X.Y.Z`형태로 바꿔주세요. 위 상태로 `tuist install`를 실행할 경우 첨부한 사진과 같은 에러가 발생합니다
![CleanShot 2024-05-20 at 00 08 44@2x](https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/9fa33fa1-2707-4d1b-bd12-84b38b34a8de)

2024-05-19 15:33 UTC, zekexros commented on MyApp/Tuist/Package.swift
> +)
P2: [TCACoordinators](https://github.com/johnpatrickmorgan/TCACoordinators)가 누락되었습니다. `TCACoordinators`를 추가할 때 최소 요구 버전을 `0.10.0`으로 하고. 이에 맞춰 TCA의 버전도 `1.8.0`으로 고정적으로 사용하면 어떨까요(TCACoordinator의 업데이트 주기가 상대적으로 더 길어, TCA의 버전 업데이트에 따른 신규 기능 추가 또는 기존 API 삭제 등에 대한 대응이 늦기 때문입니다)

2024-05-19 15:33 UTC, zekexros commented on .github/.gitignore
>  # End of https://www.toptal.com/developers/gitignore/api/macos,swift,swiftpackagemanager,xcode
P1: `.gitignore` 파일의 위치가 잘못되어 제대로 적용되지 않고 있습니다(이전 PR에서 놓쳤네요)
파일의 위치를 루트 디렉토리로 옮기면 어떨까요🙇‍♂️

2024-05-20 00:14 UTC, GREENOVER requested changes
초기 작업 처음했을텐데 수고 많으셨습니다 👍
리뷰들 기반으로 한번 검토 부탁드려요!
그리고 하나 더 중요한 설정이 빠졌어요.
workspace 파일 생성이 되지 않아요~
Project.swift 파일 설정을 통해 xcodeproj 파일 구성을 하고 만드신것처럼,
최상위 경로에서 Workspace.swift 파일을 생성/구성하여 MyApp.xcworspace 파일을 생성할 수 있도록 추가 부탁드립니다!
(https://docs.tuist.io/generated/structs/Workspace.html#workspace)

2024-05-20 00:14 UTC, GREENOVER commented on MyApp/MyApp/Sources/ContentView.swift
> +struct ContentView_Previews: PreviewProvider {
p5: Xcode 15부턴 매크로 적용이 가능해서 아래와 같이 편하게 프리뷰를 생성할 수 있습니다.
```swift
#Preview {
  ContentView()
}
```

2024-05-20 00:14 UTC, GREENOVER commented on MyApp/MyApp/Sources/ContentView.swift
> +import SwiftUI
p3: 파일 생성 및 정보에 관련된 주석은 일부로 지운것일까요~?
없어도 상관없긴하지만, 없는 정책으로 갈 시 매번 파일 생성 후 해당 주석을 제거해줘야하는데 번거로울것도 같습니다.
그래서 지우는데 특별한 의견이 없다면 그냥 지우지 않고 가도 되지 않을까해요.
cc. @zekexros @hope1053

2024-05-20 00:14 UTC, GREENOVER commented on MyApp/MyApp/Tests/MyAppTests.swift
> +import Foundation
p3: 테스트를 초반에 하지 않을것 같으니 왠만하면 테스트 관련 파일 및 설정들은 빼고 가는게 좋을듯합니다.

2024-05-20 00:14 UTC, GREENOVER commented on MyApp/Project.swift
> +    .target(
p3: 위 코멘트와 이어집니다 🙋🏻 나중에 테스트 필요할때 넣는게 나을듯해요.

2024-05-20 00:14 UTC, GREENOVER commented on MyApp/Project.swift
> +import ProjectDescription
p1: 해당 파일은 MyApp 폴더 내부에 위치시켜주세요~
추후 MyApp 프로젝트 모듈 외 다양한 모듈이 존재할때 다같이 최상위에 존재할 수 없음으로 관리가 힘들어집니다 🙏🏻

2024-05-20 01:06 UTC, zekexros commented on MyApp/MyApp/Sources/ContentView.swift
> +import SwiftUI
> 그냥 지우지 않고 가도 되지 않을까해요

동의합니다👍

2024-05-20 02:19 UTC, serena0720 commented on MyApp/Tuist/Package.swift
> +)
```swift
    .package(url: "https://github.com/kean/Nuke.git", from: "12.0.0"),
    .package(url: "https://github.com/kean/Get.git", from: "2.2.0")
```
위 형태로 수정이 맞는지 확인 부탁드립니다!

2024-05-20 02:19 UTC, serena0720 commented on MyApp/MyApp/Sources/ContentView.swift
> +struct ContentView_Previews: PreviewProvider {
확인했습니다👍

2024-05-20 02:37 UTC, zekexros commented on MyApp/Tuist/Package.swift
> +)
네 맞습니다🎉 
로컬에서 `tuist install`명령어를 통해 수정이 올바른지 확인할 수 있습니다

2024-05-20 04:15 UTC, GREENOVER approved these changes
고생했어유~ 👍

2024-05-20 04:28 UTC, zekexros approved these changes
고생하셨습니다🙇‍♂️

2024-05-20 04:46 UTC, merged