[Feat] KakaoClient 생성 및 AppReducer 생성
mash-up-kr/gabbangzip-iOS pull request #56
Opened 2024-06-19 23:18 UTC by serena0720

## 📌 Related Issue
- #30 

## 🚀 Description
- KakaoSDK 및 Alamofire Dependency 추가
- KakaoSDK init 및 openUrl 기능 구현

## ✅ Done
- [ ] KakaoSDK 및 Alamofire Dependency 추가
- [ ]  KakaoSDK init 및 openUrl 기능 구현
- [ ]  AppCore 생성

## 📢 Notes
 [ 실행 시 체크해야할 부분 ]
- TARGETS > Info > URL Types > URL Schemes 값 `kakao${네이티브앱키} `이 있는지 확인해야 합니다.
- 아래 링크 속 Secret 폴더를 Core > Project > Common 내부에 저장하였는지 확인해야 합니다.
> [참고](https://www.notion.so/KakaoLogin-9c5960f29e934687bdf89f717e12e26f)

## 🔥 Trouble Shooting
### [ open URL 구현 위치 ]
Kakao 공식 문서 상 open URL을 구현하는 방법은 총 3가지입니다.
1. AppDelegate에 구현하는 방법
```swift
import KakaoSDKAuth
...
class AppDelegate: UIResponder, UIApplicationDelegate {
    ...
    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        if (AuthApi.isKakaoTalkLoginUrl(url)) {
            return AuthController.handleOpenUrl(url: url)
        }
        return false
    }
}
```
해당 방법은 AppDelegate와 SceneDelegate가 분리전인 iOS 13 이전 버전에서 사용해야 합니다.

2. SceneDelegate에 구현하는 방법
```swift
import KakaoSDKAuth
...
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    ...
    func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        if let url = URLContexts.first?.url {
            if (AuthApi.isKakaoTalkLoginUrl(url)) {
                _ = AuthController.handleOpenUrl(url: url)
            }
        }
    }
}
```
 iOS 13 이상으로 생성된 프로젝트라면 Info.plist 파일에 UIApplicationSceneManifest 설정이 추가되며, UISceneDelegate.swift를 기본으로 사용하도록 설정되기 때문에, 해당 매서드를 SceneDelegate에서 구현해야합니다.

3. App에 구현하는 방법
```swift
import SwiftUI
import KakaoSDKCommon
import KakaoSDKAuth

@main
struct SwiftUI_testApp: App {
    var body: some Scene {
        WindowGroup {
            // onOpenURL()을 사용해 커스텀 URL 스킴 처리
            ContentView().onOpenURL(perform: { url in
                if (AuthApi.isKakaoTalkLoginUrl(url)) {
                    AuthController.handleOpenUrl(url: url)
                }
            })
        }
    }
    ...
}
```

✅ 저희 앱의 경우 AppDelegate를 살려놨기 때문에 AppDelegate에서 해당 매서드를 구현했습니다.
하지만 token이 저장되지 않는다는 에러가 발생하여 원인을 찾다보니, 저희 앱은 iOS 13 버전 이상을 타겟하는 앱이기 때문에 해당 매서드를 AppDelegate에서 구현하면 안된다는 것을 알게되었습니다. 하여 App에서 최초 ContentView에 진입 시 `.onOpenURL` 에 해당 매서드를 구현하였습니다.
[참고](https://devtalk.kakao.com/t/kakaosdkcommon-clientfailurereason-tokennotfound/134277/10)

### [ open URL 시 Main Thread Running ]

![스크린샷 2024-06-17 오전 5 24 46](https://github.com/mash-up-kr/gabbangzip-iOS/assets/101619749/a6584129-a82a-4b84-a513-ce1af1860d94)
실행 시 Kakao를 열 때 Thread 이슈가 발생하여 AuthController의 handleOpenUrl매서드를 호출하는 함수에 @MainActor 매크로를 사용하여 Thread 문제를 해결하고자 하였습니다. 하지만 해당 매서드는 URL경로를 등록하는 개념의 매서드이기 때문에 Thread 문제와는 무관하다는 것을 알게되었습니다. 하여 실제 화면 변화가 일어나는 Login 매서드에 @MaingActor를 사용하여 문제를 해결하였습니다.

### [ DependencyClient unimplemented value ]
- DependencyClient 매크로 사용 시 throw되지 않고 void가 아닌 반환인 클로저가 있는 경우, 구현되지 않은 값을 생성할 수 있도록 기본값을 줘야합니다. 런타임 시 충돌 없이 테스트 및 SwiftUI preview에 해당 기본값을 사용하여 즉각 접근할 수 있기 때문입니다. 
> [참고](https://swiftpackageindex.com/pointfreeco/swift-dependencies/main/documentation/dependenciesmacros/dependencyclient()#Restrictions)

2024-06-20 00:06 UTC, GREENOVER requested changes
수고하셨습니다!!
확실히 PR을 쪼개서 단위당 가져가니까 리뷰하기도 수월하고 현아님 이해도도 많이 높은것 같아 성공이네요 👍
리뷰드린것 한번 봐주시면 좋을것 같습니다 😃

2024-06-20 00:06 UTC, GREENOVER commented on .gitignore
> +Projects/Core/Common/Secret
위 End of 주석이 문서의 끝을 알리는거라 그 전에 적용할 깃이그노어들을 적용하는게 어떨까요~?

2024-06-20 00:06 UTC, GREENOVER commented on Projects/App/Info.plist
> +		<string>kakaokompassauth</string>
카카오톡으로 공유하려면 kakaolink도 추가되야할것 같아 보입니다 🙋🏻
이후 피쳐들의 명세를 보시고 필요하다 싶으면 넣고 아니면 안넣으셔도 됩니다~!

2024-06-20 00:06 UTC, GREENOVER commented on Projects/App/Sources/ContentView.swift
>  public struct ContentView: View {
이참에 이름을 바꿔도 될것 같아요!
그전에는 초기 만들어진 그대로였는데, 이제 유의미하게 해당 앱의 진입이라면 AppView같은것으로 변경해도 명확할것 같습니다.

2024-06-20 00:06 UTC, GREENOVER commented on Projects/App/Sources/ContentView.swift
>  public struct ContentView: View {
그에따라 GabbangzipCore의 명칭도 같이 통일되면 좋을것 같습니다 🙋🏻

2024-06-20 00:06 UTC, GREENOVER commented on Projects/App/Sources/ContentView.swift
> +  ContentView(store: .init(initialState: GabbangzipCore.State(), reducer: { GabbangzipCore() }))
적절한 개행을 해주는것도 좋아보입니다 🙋🏻

2024-06-20 00:06 UTC, GREENOVER commented on Projects/App/Sources/GabbangzipCore.swift
> +import Foundation
Foundation import는 안해도 이미 Composable에도 들가 있어서 괜찮을것 같아요 🙋🏻

2024-06-20 00:06 UTC, GREENOVER commented on Projects/App/Sources/GabbangzipCore.swift
> +import KakaoSDKUser
둘다 필요한건가요~?
보통이라면 KakaoSDKUser가 Services 내에 채택되있고 구현되어 있다면 필요 없지 않을까 해서요..!
즉, 중복으로 보이는데 단일로 Services만 import하여도 될 수 있도록 구성하면 좋을것 같습니다.

2024-06-20 00:06 UTC, GREENOVER commented on Projects/Core/Models/KaKaoUserInformation.swift
> +//  Models
모델에서도 추후 많은 파일들이 올 수 있어 Kakao같은 이름으로 모델 내에서도 폴더 그룹을 만드는것이 좋을것 같습니다 🙋🏻

2024-06-20 00:06 UTC, GREENOVER commented on Projects/Core/Models/KaKaoUserInformation.swift
> +  public let nickName: String?
닉네임은 합성어가 아니라 nickname이 더 적절할것 같아요~!

2024-06-20 00:06 UTC, GREENOVER commented on Projects/DesignSystem/Project.swift
> +        .external(externalDependency: .kakaoSDK)
DS에 kakaoSDK가 왜 필요한건지 모르겠습니다 🙋🏻

2024-06-20 00:06 UTC, GREENOVER commented on Projects/Features/Coordinator/Project.swift
> +        .external(externalDependency: .kakaoSDK)
현재 구조가 정해지지 않았지만 코디네이터 패턴에 kakaoSDK가 왜 필요한건지 모르겠습니다 🙋🏻

2024-06-20 00:06 UTC, GREENOVER commented on Tuist/Package.swift
> +    .package(url: "https://github.com/kakao/kakao-ios-sdk", from: "2.22.2")
요거 인덴트 위랑 맞는건가요~?
깃헙에서는 안맞아 보여서 여쭤봅니다!
visual studio로 해당 파일 여셔서 보셔도 정확해요!
가끔 xcode도 이상해서

2024-06-20 00:06 UTC, GREENOVER commented on Projects/Core/Services/KakaoLoginClient/KakaoLoginClient.swift
> +import Foundation
불필요하지 않을까 싶습니다 🙋🏻

2024-06-20 00:06 UTC, GREENOVER commented on Projects/Core/Services/KakaoLoginClient/KakaoLoginClient.swift
> +//  CoreKit
타겟은 Services라 Services가 맞을것 같아요 🙋🏻

2024-06-20 00:06 UTC, GREENOVER commented on Projects/Core/Services/KakaoLoginClient/KakaoLoginClient.swift
> +//  KakaoLoginClient.swift
요건 제가 놓친것 같은데,
현재 Services 내 폴더들의 명칭이 조금씩 다른것 같아요.

PhotoClient / SnapshotClient는 폴더명에 클라이언트가 붙어있고,
나머지는 안붙어 있는데 폴더명에서는 클라이언트를 붙이지 않는걸로 통일되면 좋을것 같습니다 🙋🏻

한번에 이전 폴더명까지 수정해주시면 감사하겠습니다!

2024-06-20 00:06 UTC, GREENOVER commented on Projects/Core/Services/KakaoLoginClient/KakaoLoginClient.swift
> +}
Good

2024-06-20 00:06 UTC, GREENOVER commented on Projects/Core/Services/KakaoLoginClient/KakaoLoginClient.swift
> +              continuation.resume(throwing: error)
여기서는 정제된 KakaoLoginClientError를 내뱉지 않아도 괜찮을까요~?

2024-06-20 00:06 UTC, GREENOVER commented on Projects/Core/Services/KakaoLoginClient/KakaoLoginClient.swift
> +              continuation.resume(throwing: error)
아래 동일한 부분도 비슷한 맥락으로 보시면 좋을것 같습니다~!

2024-06-20 00:06 UTC, GREENOVER commented on Projects/Core/Models/KaKaoUserInformation.swift
> +public struct KaKaoUserInformation: Codable {
해당 모델은 추후 가빵집 서버 단에서 회원가입 시 필요한 Request Model인가요!?
카카오 로그인 시에는 토큰만 받아오는것 같아서 해당 모델 타입은 아닐테고 어디서 어떻게 사용되는건지 궁금합니다 🙋🏻

또한, 디코딩/인코딩 모두 되는 Codable한 객체의 쓰임을 가지나요?

2024-06-20 01:45 UTC, GREENOVER commented
+ 시크릿 키를 Common 모듈 내 저장보다 그냥 해당 Core 리소스 내 저장하는건 어떨까요?
물론 숨기는건 같아야하구요!ㅎㅎ
그리고 지금 노션 링크 개인것인지 저희 접근 권한이 없어서 확인할 수 없는것 같아요 🥲

2024-06-20 02:15 UTC, serena0720 commented on Projects/App/Info.plist
> +		<string>kakaokompassauth</string>
공유하기 담당자가 제가 아니기 때문에 혼선이 생길 수 있어서 말씀주신대로 추후 카카오 Link의 ShareApi를 사용할때 추가하는 것이 어떨까 싶습니다!

2024-06-20 02:48 UTC, serena0720 commented on Projects/App/Sources/ContentView.swift
> +  ContentView(store: .init(initialState: GabbangzipCore.State(), reducer: { GabbangzipCore() }))
넵 수정했습니다!

2024-06-20 02:50 UTC, serena0720 commented on Projects/Core/Services/KakaoLoginClient/KakaoLoginClient.swift
> +//  CoreKit
와 꼼꼼한 확인 감사합니다👍
동일 타겟인 RouteType, NetworkManager 또한 Corekit으로 기재되어 있어서 함께 수정했습니다

2024-06-20 02:55 UTC, serena0720 commented on Projects/Core/Services/KakaoLoginClient/KakaoLoginClient.swift
> +//  KakaoLoginClient.swift
넵 변경했습니다~

2024-06-20 03:00 UTC, serena0720 commented on Projects/App/Sources/ContentView.swift
>  public struct ContentView: View {
저희 Identity를 살려 Gabbangzip으로 Core, App, View 모두 통일하겠습니다!
가자~ 빵집으로!🥖

2024-06-20 03:01 UTC, serena0720 commented on Projects/App/Sources/GabbangzipCore.swift
> +import Foundation
아 꼼꼼한 리뷰 감사합니다!😊

2024-06-20 03:03 UTC, serena0720 commented on Projects/App/Sources/GabbangzipCore.swift
> +import Foundation
저도 저번에 Composable 안에 foundation이 있다고 들었는데, 제 컴퓨터에선 Foundation을 지우면 URL 타입을 찾을 수 없다고 나옵니다😇 이부분에 대해 조언 부탁드립니다🥹

> Cannot find type 'URL' in scope

2024-06-20 03:09 UTC, serena0720 commented on Projects/Core/Models/KaKaoUserInformation.swift
> +public struct KaKaoUserInformation: Codable {
아 encoding도 필요하지 않을까 싶어서 codable을 채택했는데, 말씀주신대로 서버로부터 받는 객체는 별도로 생성할 듯 싶어 decodable만 채택하는 것이 더 적절할 거 같습니다! 꼼꼼한 체크 감사합니다!

2024-06-20 03:18 UTC, serena0720 commented on Projects/Core/Services/KakaoLoginClient/KakaoLoginClient.swift
> +              continuation.resume(throwing: error)
넵 케이스별로 KakaoLoginError 타입으로 수정했습니다~

2024-06-20 03:21 UTC, serena0720 commented on .gitignore
> +Projects/Core/Common/Secret
End of 전에 APIKey 파일에 대한 깃이그노어를 추가하라는거일까요?

2024-06-20 03:23 UTC, serena0720 commented
@hope1053 @zekexros APIKey 파일 위치에 대한 추가 의견이 있으면 말씀해주세요 다른 분들 의견도 알려주시면 참고하겠습니다!

+ 노션 링크는 매시업 내부 링크라서 매시업 아이디 확인해주세용~

2024-06-20 04:54 UTC, GREENOVER commented on .gitignore
> +Projects/Core/Common/Secret
예쓰

2024-06-20 04:55 UTC, GREENOVER commented on Projects/App/Sources/GabbangzipCore.swift
> +import Foundation
아 URL이 있어서 그르네요. 킵고잉하시면 됩니다!

2024-06-20 11:43 UTC, serena0720 commented on Projects/App/Sources/GabbangzipCore.swift
> +import KakaoSDKUser
중복이 맞습니다🥹 Service만 남기겠습니다!

2024-06-20 11:43 UTC, serena0720 commented on Projects/Core/Models/KaKaoUserInformation.swift
> +//  Models
네~ 반영하겠습니다💪

2024-06-20 11:45 UTC, serena0720 commented on Projects/Core/Models/KaKaoUserInformation.swift
> +  public let nickName: String?
카카오 문서에도 nickname이라 명시되어 있네요🥹 꼼꼼한 리뷰 감사합니다!

2024-06-20 11:46 UTC, serena0720 commented on Projects/DesignSystem/Project.swift
> +        .external(externalDependency: .kakaoSDK)
tuist를 처음 다루다보니 불필요한 곳에도 Dependency를 생성한 거 같습니다😅 불필요한 부분들 삭제하겠습니다!

2024-06-20 11:48 UTC, serena0720 commented on Tuist/Package.swift
> +    .package(url: "https://github.com/kakao/kakao-ios-sdk", from: "2.22.2")
Xcode 상으론 문제가 없었는데 앞으로 Visual Studio로도 확인해보겠습니다!💪

2024-06-20 11:56 UTC, serena0720 commented on Projects/Core/Services/KakaoLoginClient/KakaoLoginClient.swift
> +import Foundation
위와 동일하게 URL 타입으로 인해 Foundation이 필요합니다🥹

2024-06-20 13:18 UTC, serena0720 commented on .gitignore
> +Projects/Core/Common/Secret
카톡으로 의논한대로 xcconfig에 Native Key 값을 옮겼고, .xcconfig 확장자 파일들은 모두 ignore 시켰습니다

2024-06-21 00:32 UTC, GREENOVER requested changes
리팩토링 하느라 수고하셨습니다!
코멘트 다시 한번 점검 부탁드립니다 🙏🏻

2024-06-21 00:32 UTC, GREENOVER commented on Projects/App/Info.plist
> +	<key>CFBundleInfoDictionaryVersion</key>
해당 버전은 엑코가 자동으로 설정해준건가요?
왜냐면 해당 키 값 자체는 엑코에서 자동으로 생성되기에 수동으로 변경하면 안되는걸로 알아서 추가된 경위가 궁금했습니다 🙋🏻

2024-06-21 00:32 UTC, GREENOVER commented on Projects/App/Sources/RootCore.swift
> +//  GabbangzipCore.swift
이름 변경 필요합니다~!

2024-06-21 00:32 UTC, GREENOVER commented on Projects/App/Sources/RootView.swift
> +//  ContentView.swift
이름 변경 필요222

2024-06-21 00:32 UTC, GREENOVER commented on Projects/App/Sources/RootView.swift
> +import ComposableArchitecture
아마 린트룰 돌아서 경고가 나왔을건데요.
현재 린트룰로 import를 할때 알파벳순으로 import하도록 설정되있어서 전체적으로 작업하신곳에서 체크 및 수정 부탁드립니다~!
즉, C > D > S 순으로 import 되어야함

2024-06-21 00:32 UTC, GREENOVER commented on Projects/App/Project.swift
> +        .external(externalDependency: .kakaoSDK)
Core에서 kakaoSDK를 채택하고 있고 다른 모듈에선 services 모듈을 사용하고 있기에 여기서 채택하지 않아도 되는거 아닌가 여쭤봅니다 🙋🏻

2024-06-21 00:32 UTC, GREENOVER commented on Projects/Features/Scene/Project.swift
> +        .external(externalDependency: .kakaoSDK)
채택해야 하나요?

2024-06-21 01:12 UTC, serena0720 commented on Projects/App/Info.plist
> +	<key>CFBundleInfoDictionaryVersion</key>
자동으로 생성되었습니다!

2024-06-21 01:14 UTC, serena0720 commented on .gitignore
> +Projects/Core/Common/Secret
@GREENOVER @zekexros @hope1053 
xcconfig 파일은 하기 주소안에 있으니 참고해주세요!
> [xcconfigs](https://www.notion.so/xcconfigs-8d19e501424d4de8a00053c65f125485)

2024-06-21 01:17 UTC, serena0720 commented on Projects/App/Sources/RootView.swift
> +import ComposableArchitecture
이런 규칙이 있었군요👀 동일 경고 있는 부분들 수정하였습니다! 알려주셔서 감사합니다🙇‍♀️

2024-06-21 01:23 UTC, serena0720 commented on Projects/App/Project.swift
> +        .external(externalDependency: .kakaoSDK)
네 채택할 필요가 없는 거 같습니다😅 Prod와 Dev에서 모두 삭제하겠습니다!

2024-06-21 01:26 UTC, serena0720 commented on Projects/Features/Scene/Project.swift
> +        .external(externalDependency: .kakaoSDK)
해당 부분은 DesignSystem과 연관 있는 부분이라 필요 없을 거 같습니다🥹

2024-06-21 07:20 UTC, GREENOVER approved these changes

2024-06-21 09:52 UTC, zekexros approved these changes
고생하셨어요!!👍

2024-06-21 11:02 UTC, hope1053 approved these changes

2024-06-21 16:56 UTC, merged