Feat/#57
mash-up-kr/gabbangzip-iOS pull request #59
Opened 2024-06-24 15:58 UTC by serena0720

## 📌 Related Issue
- #57 

## 🚀 Description
- Login화면과 관련된 Dependency 생성 및 뷰 생성하였습니다.

## ✅ Done
- 기존 RouteType의 init 파라미터 path -> url 로 수정하여 사용했습니다.
- KakaoClient와 이에 사용되는 모델 객체들 생성했습니다.
- KeyChainClient CRUD 구현했습니다.

## 📸 Screenshot
<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/101619749/c79fd535-f828-4f90-b80c-16c4912448b0"  width="200" height="400">
<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/101619749/479cc9f9-2214-49b4-abc3-e207104926c7"  width="200" height="400">

## 📢 Notes
- LoginView의 PIC. 부분은 추후 로고 이미지로 변경원한다는 디자인팀 의견이 있어서 현재 PIC. 캡쳐 이미지로 구현하였습니다.
- LoginView의 로띠 이미지 사이즈를 2가지를 전달받았는데, 전체 화면 기준으로 사이즈된 로띠 이미지를 ZStack으로 쌓아서 구현했습니다.

## 🔥 Trouble Shooting
### [ KeyChain Create Error ]
KeyChain Create 시 이미 값이 존재하는 경우 아래 경고가 떴습니다.
```
An "Effect.run" returned from "KakaoLogin/LoginCore.swift:124" threw an unhandled error. …

    KeyChainClientError(
      userInfo: [:],
      code: .failToCreate,
      underlying: nil
    )

All non-cancellation errors must be explicitly handled via the "catch" parameter on "Effect.run", or via a "do" block.
```
이에 create 시 status 중 errSecDuplicateItem의 경우 create가 아닌 update를 할 수 있도록 로직 수정하였습니다.

> [status 참고 링크](https://developer.apple.com/documentation/security/1542001-security_framework_result_codes)

2024-06-25 01:07 UTC, GREENOVER requested changes
우선 시간 관계상 대략적으로 먼저 1차 리뷰 드립니다🙋🏻

2024-06-25 01:07 UTC, GREENOVER commented on Projects/App/Project.swift
> +        .project(target: .mainCoordinator, projectPath: .coordinator),
App에서 메인 코디네이터 연결이 필요한가요?

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        Image(uiImage: DesignSystem.Icons.Login.logoUIImage)
`DesignSystem.Icons.Login`로 쓰시면 됩니다~

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        Image(uiImage: DesignSystem.Icons.Login.logoUIImage)
컴포넌트 단위로 개행 부탁드려요.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +          .font(DesignSystemFontFamily.Pretendard.regular.font(size: 21))
폰트 만약 DS에 정의되지 않은 21 폰트이면 디자인에 요청 혹은 우리가 직접 fonts.stencil에 정의하여 `.font(.body21)`처럼 쓸 수 있도록 하는것이 좋을것 같아요.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        Spacer()
사이 공간은 사실 기기마다 다르기에 로그인 버튼의 하단 padding을 잡고 사이 공간은 유연하게 가져가는것이 더 적절할것 같아요.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +          Image(uiImage: DesignSystem.Icons.Login.kakaoUIImage
개행 스타일 통일 부탁드립니다~

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +            ))
`.padding(.horizontal, 16)`으로 충분하지 않나요?

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        ToastView(message: errorMessage)
공통적으로 쓰일 수 있기에 만약 먼저 작업하셨다면 DS에 공통화 시켜 작업해주시면 좋을것 같습니다.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Core/Models/Kakao/KakaoResponse.swift
> +  public let errorResponse: KakaoResponseError?
kakaoErrorReponse가 더 적절해보입니다.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/App/Sources/RootView.swift
> +      )
로티 뷰를 LoginView에 넣으면 되지 않나요?

2024-06-25 01:07 UTC, GREENOVER commented on Projects/App/Sources/RootView.swift
> +      LoginView(
추후 자동로그인되면 RootView에서 로그인뷰를 타지 않기에,
로그인 여부에 따라 로그인뷰를 보여줄지 MainView를 보여줄지 분기가 필요할것 같아요.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Core/Common/Extensions/URLComponents+extensions.swift
> +}
꼭 필요한가요?
이미 URL 생성에 대해 다 구현되어 있기에 프로토콜을 따르는것이 좋을것 같아서요.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Core/Models/Kakao/KakaoLoginRequestInformation.swift
> +  public init(idToken: String, provider: String, nickname: String, profileImage: String) {
개행 부탁드립니다.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Core/Models/Kakao/KaKaoUserInformation.swift
> +public struct KaKaoUserInformation: Equatable {
모델 폴더 내에서 Response와 Request 폴더를 두어 파일 관리를 하시는것이 더 명확할것 같아요!

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Core/Models/Kakao/KakaoURL.swift
> +      return "3.39.133.214"
네트워크 매니저에서 baseURL을 설정해두면 어떤가요?
해당 host는 동일할거라 보입니다.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Core/Models/Kakao/KakaoURL.swift
> +      return "3.39.133.214"
만약 추가 설정이 필요하면 해당 네트워크 baseURL에서 컨트롤해주는것이 더 다른 작업이 추가 되지 않을것 같아요.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Core/Services/KakaoAPI/KakaoAPI.swift
> +  case login(_ idToken: String, _ provider: String, _ nickname: String, _ profileImage: String)
개행이 필요합니다.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Core/Models/Kakao/KakaoURL.swift
> +      return "http"
이것도 baseURL에서 한번에 넣어둘 수 있어보입니다.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Core/Services/KakaoAPI/KakaoAPI.swift
> +      return try? JSONEncoder().encode(body)
그냥 request모델이 Encodable을 따르면 인코딩을 직접 해주지 않아도 충분해보입니다.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Core/Services/KakaoAPI/KakaoAPI.swift
> +      let query: [String: String]? = [
헤더와 쿼리는 다릅니다.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Core/Services/KakaoAPI/KakaoAPI.swift
> +  public var id: String? {
왜 필요한가요?

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Core/Services/KakaoAPI/KakaoAPIClient.swift
> +    _ profileImage: String
명시적으로 파라미터를 호출하는것이 안헷갈릴것 같다고 느껴져요..!
현재는 다 같은 String 타입이라 실수할 여지가 있지 않을까 합니다.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Core/Services/KakaoAPI/KakaoAPIClient.swift
> +          let user = try JSONDecoder().decode(KakaoResponse.self, from: response.data).data
디코딩도 다 Get에서 해주기에 적절히 사용만 하면 불필요한 코드가 될것 같아요.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +      case let .loginWithKakaoTalkResponse(.failure(error)):
error 인자 쓰이는 경우가 있나요?

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +          }))
개행 + 인덴트를 적절히 해주면 가독성이 더 좋을것 같습니다.

2024-06-25 01:07 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +      VStack {
ZStack으로 되어 있어서 해당 토스트 메시지 뜰때 하위 깔린 로그인 버튼이나 다른 인터랙션을 받을 수 없을것 같은데 괜찮나요?

2024-06-25 02:59 UTC, zekexros requested changes
오랫동안 수고 많으셨어요! 정상이 눈앞에 있습니다👀
그리고 출력문 제거 부탁드립니다🙂

2024-06-25 02:59 UTC, zekexros commented on Projects/App/Sources/AppDelegateCore.swift
> +          await kakaoLoginClient.initSDK(appKey)
P2:
카카오 SDK관련 로직과 알림 권한 요청 관련 로직이 섞여있네요. 정리가 필요합니다

2024-06-25 02:59 UTC, zekexros commented on Projects/App/Sources/AppDelegateCore.swift
> +          let appKey = try bundleClient.getValue("KakaoNativeAppKey") as? String ?? ""
P3:
appKey가 타입 캐스팅에 실패하여 ""로 초기화되어 `initSDK`의 파라미터로 사용되어도 `initSDK` 함수는 어떠한 에러도 던져주지 않기에 디버깅에 어려움을 겪을 수 있습니다.
타입 캐스팅 실패에 대한 에러를 처리하는 것은 어떨까요

2024-06-25 02:59 UTC, zekexros commented on Projects/App/Sources/RootCore.swift
> +    }
P1:
줄바꿈 확인해 주세요

2024-06-25 02:59 UTC, zekexros commented on Projects/App/Sources/RootCore.swift
> +      case .login(_):
P3:
```suggestion
      case .login:
```
연관값을 사용하지 않는다면 더 간단하게 선언하는 것도 가독성 측면에선 좋을 수 있습니다

2024-06-25 02:59 UTC, zekexros commented on Projects/App/Sources/RootView.swift
> +      .frame(width: 600)
P1:
width를 실수로 잘못 적용하신 것 같아요

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Common/Extensions/URLComponents+extensions.swift
> +    }
P1:
URL생성할 때 실패할 경우에 대한 처리가 미흡합니다
이 부분을 보완하거나 Get에게 그 역할을 일임하는 것도 하나의 방법이 되겠네요

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Common/Extensions/URLComponents+extensions.swift
> +    }
```suggestion
    if let port = port {
      components.port = port
    }
    components.host = hostcomponents.host = host
```
이렇게 줄일 수 있겠네요

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Common/Extensions/URLComponents+extensions.swift
> +    }
4칸 indent가 적용되었는데 2칸으로 수정이 필요합니다

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Models/Kakao/PICUserInformation.swift
> +  public let nickname, accessToken, refreshToken: String
P4:
같은 타입을 가지는 것들에 대해선 작성하신 바와 같이 한 줄로도 표현이 가능하지만,
저는 같은 타입이라도 줄바꿈을 적용하면 위에서 아래로 단순하게 읽기가 더 쉬워 가독성이 향상된다고 생각합니다. 이에 대해 어떻게 생각하시나요?

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Services/GetHelpers/GabbangzipAPIClientDelegate.swift
>      case 400..<500:
P2:
말씀드린 바와 같이 400..<500, 500..<600 만 처리하고 이외에는 `default: break`로 선언하는 것이 더 편할 듯 합니다.
작성하신 부분은 200번대뿐만 아니라 300번도 포함되어 있으며, 추가로 300..<400 번대도 처리해야 하는 번거로움이 있습니다.

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Services/GetHelpers/RouteType.swift
P3:
path에서 url로 바뀌었으니 주석도 변경이 필요합니다

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Services/KakaoAPI/KakaoAPI.swift
> +      return try? JSONEncoder().encode(body)
P2:
JSON형식으로 인코딩에 실패했을 경우 nil로 반환하도록 하는 것은 디버깅에 어려움을 줄 수 있습니다

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Services/KakaoAPI/KakaoAPIClient.swift
> +    _ profileImage: String
이 부분은 대신 답변드리자면,
와일드 카드 패턴을 사용하지 않으면`Function types cannot have argument labels`라는 에러가 발생합니다. 따라서 타입만 선언하거나 와일드 카드 패턴을 사용해야만 하고 파라미터를 명시적으로 볼 수 없었는데,
새롭게 출시된 신상 `@DependencyClient` 매크로를 사용하면 와일드 카드 패턴을 적용하더라도 실제 리듀서에서 사용할 때 파라미터가 명확하게 표시됩니다.
`loginAPIClient.login(idToken: idToken, nickname: nickname, profileImage: profileImageUrl)`

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Services/KakaoAPI/KakaoAPIClient.swift
> +  }
P1:
타입은 `KakaoAPIClient`인데 선언은 `loginAPIClient`로 했습니다. 하나로 통일해주세요

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Services/KakaoAPI/KakaoAPIClient.swift
> +          let user = try JSONDecoder().decode(KakaoResponse.self, from: response.data).data
찬우님 말처럼 불필요한 디코딩입니다. `response.value`로 바로 반환하면 되겠네요

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Services/KeyChain/KeyChainClient.swift
> +                             encoding: String.Encoding.utf8)
P1:
줄바꿈 확인해주세요

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Services/KeyChain/KeyChainClient.swift
> +                             encoding: String.Encoding.utf8)
P3:
디버깅 용이성을 위해 nil이 아니라 error를 던지면 어떨까요

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Services/KeyChain/KeyChainClient.swift
> +          print("Keychain Delete Success")
P1:
출력문이 포함되었네요

2024-06-25 02:59 UTC, zekexros commented on Projects/Core/Services/KeyChain/KeyChainClient.swift
> +  private static func updateKey(_ key: Key,_ data: String) throws {
P1:
```suggestion
  private static func updateKey(_ key: Key, _ data: String) throws {
```

2024-06-25 02:59 UTC, zekexros commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +    public init() {}
P2:
State를 초기화할 때 다른 값을 넣을 수 있도록 초기화는 가능한 한 초기화 함수 내에서 하는 것이 어떨까요

2024-06-25 02:59 UTC, zekexros commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +  public init() {}
P2:
초기화 함수가 중첩 타입보다 아래에 위치하는 것이 가독성이 더 좋다고 판단하신 걸까요?

2024-06-25 02:59 UTC, zekexros commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +          }))
P3:
try await에서 줄바꿈이 적용되었네요. 확인 부탁드립니다

2024-06-25 02:59 UTC, zekexros commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +          await send(.saveRefreshTokenInKeyChain(user?.refreshToken ?? ""))
P2:
accessToken이 없는 경우, 빈 문자열로 키체인에 저장하는 것이 맞을까요?

2024-06-25 02:59 UTC, zekexros commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +        }
P4:
하나로 합쳐서 사용할 수 있어 보입니다

2024-06-25 02:59 UTC, zekexros commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        Text("우리가 픽! 하는\n우리끼리 네컷앨범")
P2:
작은 화면을 가진 디바이스에선 글자가 줄여지는 현상(ellipsis)이 나타납니다
또, Spacer()에 고정된 높이를 설정하는 것은 다양한 화면 크기에 대응하는 데 적합하지 않습니다

2024-06-25 08:25 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        Image(uiImage: DesignSystem.Icons.Login.logoUIImage)
혹시 바로 Image 타입을 사용하라는 걸까요?
타입이 UIImage와 Image 타입 2가지가 있어서 아래와 같이 수정했는데 말씀하신 방법이 맞을지 확인 부탁드립니다~!
```swift
        DesignSystem.Icons.Login.logo
          .resizable()
          .scaledToFit()
          .frame(width: 100)
```

2024-06-25 08:27 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        Image(uiImage: DesignSystem.Icons.Login.logoUIImage)
비슷한 경우 아래와 같이 개행하면 되는 걸지 확인 부탁드립니다!
```swift
        DesignSystem
          .Icons
          .Login
          .logo
          .resizable()
          .scaledToFit()
          .frame(width: 100)
```

```swift
        Text("우리가 픽! 하는\n우리끼리 네컷앨범")
          .font(
            DesignSystemFontFamily
              .Pretendard
              .regular
              .font(size: 21)
          )
```

2024-06-25 10:12 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +          Image(uiImage: DesignSystem.Icons.Login.kakaoUIImage
꼼꼼한 확인 감사합니다 ☺️

2024-06-25 10:12 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +            ))
우와 감사합니다~!

2024-06-25 10:17 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        Image(uiImage: DesignSystem.Icons.Login.logoUIImage)
맨끝 logo 없어두 됩니다~
이미 이미지타입으로 해놨어요.

2024-06-26 09:34 UTC, hope1053 requested changes
정말 수고많으셨습니다!! 👍

2024-06-26 09:34 UTC, hope1053 commented on Projects/Features/Scene/Project.swift
> +        .external(externalDependency: .lottie)
P3: 사용하지 않는 디펜던시는 삭제해주세요!

2024-06-26 09:34 UTC, hope1053 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/ToastView.swift
P2: 말씀드렸던 것 처럼 ToastView window 기반으로 수정 & DS로 빼는게 좋을 것 같습니다!

2024-06-26 09:34 UTC, hope1053 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +      case let .loginWithKakaoAccountResponse(.failure(error)):
P2: 여기도 error 사용하지 않으시면 수정해주세요!

2024-06-26 09:34 UTC, hope1053 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +      case let .checkUserInformationResponse(.failure(error)):
P2: 동일합니다 👀

2024-06-26 09:34 UTC, hope1053 commented on Projects/DesignSystem/Sources/Views/Lottie/LottieView.swift
> +  private var loopMode: LottieLoopMode
loopMode 왜 변수로 변경하셨는지 궁금해요!

2024-06-26 09:34 UTC, hope1053 commented on Projects/Core/Services/KakaoAPI/KakaoAPIClient.swift
> +        var request = Request<KakaoResponse>(route: route)
P1: 상수로 선언해도 되지않을까요~?

2024-06-26 13:19 UTC, serena0720 commented on Projects/App/Project.swift
> +        .project(target: .mainCoordinator, projectPath: .coordinator),
톡으로 의논한바와 같이 코디네이터 부분에 대한 협의가 완료되면 수정사항 업데이트하도록 하겠습니다!💪

2024-06-26 13:24 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        Image(uiImage: DesignSystem.Icons.Login.logoUIImage)
Login이 enum 타입 네임이어서 ImageAsset의 image까지 접근하기 위해선 .logo 까지 필요하다 생각하여 작성한 것인데 확인 부탁드립니다~!

2024-06-26 13:46 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        Spacer()
조언 감사합니다~!
현재 Button bottom 공간을 임의값 40으로 잡았는데 디자인팀과 더블 체크 하겠습니다!

2024-06-26 14:00 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        ToastView(message: errorMessage)
별도 이슈 생성하여 추후 작업해도 괜찮을까요?

2024-06-26 14:00 UTC, serena0720 commented on Projects/App/Sources/RootView.swift
> +      LoginView(
코디네이터 패턴 적용하면서 수정하고자 했는데 추후 변경 괜찮을까요?

2024-06-26 14:09 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +      VStack {
토스트뷰가 2초뒤에 바로 사라지기 때문에 그동안 터치가 되지 않는것도 괜찮지 않을까 생각했는데, 사용자 입장에선 로그인 에러가 뜨면 바로 다시 로그인 버튼을 누르고 싶을 수도 있겠다는 생각이 드네요👀
ZStack 위치를 변경하겠습니다!!💪

2024-06-26 14:12 UTC, serena0720 commented on Projects/Core/Services/GetHelpers/GabbangzipAPIClientDelegate.swift
>      case 400..<500:
넵 반영하겠습니당~

2024-06-26 14:13 UTC, serena0720 commented on Projects/Core/Services/KeyChain/KeyChainClient.swift
> +          print("Keychain Delete Success")
확인차 넣은 것인데 삭제하도록 하겠습니다~💪

2024-06-26 14:18 UTC, serena0720 commented on Projects/Core/Services/KakaoAPI/KakaoAPI.swift
> +      let query: [String: String]? = [
코드 수정하다가 네이밍 실수가 있었습니다🥹 수정완료했습니다~!

2024-06-26 14:19 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +          .font(DesignSystemFontFamily.Pretendard.regular.font(size: 21))
디자인팀과 협의하여 Regular 22케이스를 디자인 시스템에 추가하기로했습니다~!

2024-06-26 15:29 UTC, serena0720 commented on Projects/Core/Models/Kakao/KaKaoUserInformation.swift
> +public struct KaKaoUserInformation: Equatable {
KakaoLogin을 Request하는 KakaoLoginInformation, KakaoURL / Response를 받는 KakaoResponse, KakaoErrorResponse, PICUserInformation / 유저 정보를 저장하는 DTO에 KaKaoUserInformation, KakaoToken로 분리하였습니다!
추가 의견 있으면 참고하겠습니다💪

2024-06-26 17:03 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +      case let .loginWithKakaoTalkResponse(.failure(error)):
불필요한 error 인자 모두 삭제하였습니다~!

2024-06-26 17:04 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +          }))
아래와 같은 개행이 맞을까요?
```swift
          await send(
            .loginResponse(
              Result { try await
                kakaoAPIClient.login(
                  idToken,
                  nickname,
                  profileImageUrl
                )
              }
            )
          )
        }
```

2024-06-26 17:20 UTC, serena0720 commented on Projects/App/Sources/RootView.swift
> +      LoginView(
넹~
RootCore에서 AccessToken이 KeyChain에 저장되어있는지 체크하여 뷰를 토글하도록 구현하였습니다!
현재 MainView가 없기 때문에 임의의 TextView를 띄우도록 수정하였습니다!

2024-06-26 17:30 UTC, serena0720 commented on Projects/Core/Models/Kakao/PICUserInformation.swift
> +  public let nickname, accessToken, refreshToken: String
좋습니당~ 수정하겠습니당👍

2024-06-26 17:58 UTC, serena0720 commented on Projects/Core/Models/Kakao/KakaoURL.swift
> +      return "3.39.133.214"
아 이해했습니다! 그럼 굳이 RouteType의 프로퍼티를 url로 수정할 필요가 없군요..👀
이전 PR 내용에서 어떤 부분을 제가 놓쳤는지 알게되었습니다🥹
이전에 구현한 RouteType으로 적용하여 전체적인 코드 수정하겠습니다~!

2024-06-26 18:04 UTC, serena0720 commented on Projects/Core/Services/KakaoAPI/KakaoAPI.swift
> +  public var id: String? {
Requset에 기본 구현되어있는 포맷을 따르고자 구현한 것인데 RouteType에 맞추어 수정하면서 삭제해도 될 거 같습니다!
>참고한 부분
```swift
public struct Request<Response>: @unchecked Sendable {
    /// HTTP method, e.g. "GET".
    public var method: HTTPMethod
    /// Resource URL. Can be either absolute or relative.
    public var url: URL?
    /// Request query items.
    public var query: [(String, String?)]?
    /// Request body.
    public var body: Encodable?
    /// Request headers to be added to the request.
    public var headers: [String: String]?
    /// ID provided by the user. Not used by the API client.
    public var id: String?
```

2024-06-26 18:06 UTC, serena0720 commented
로그인 임시 서버를 닫으면서 전체적으로 로그인 Rquest 주소 수정을 하였습니다!
아래 문서 참고해주세요~🌼
> [참고](https://www.notion.so/API-8922a627f84a4579b186ba1bb70bb6dc)

2024-06-26 18:07 UTC, serena0720 commented on Projects/Core/Common/Extensions/URLComponents+extensions.swift
> +}
위 내용과 함께 수정했습니다!

2024-06-26 18:27 UTC, serena0720 commented on Projects/Core/Services/GetHelpers/RouteType.swift
https://github.com/mash-up-kr/gabbangzip-iOS/pull/59#discussion_r1655308031

위 코멘트를 수정하면서 삭제되었습니다!

2024-06-26 18:27 UTC, serena0720 commented on Projects/Core/Common/Extensions/URLComponents+extensions.swift
> +    }
https://github.com/mash-up-kr/gabbangzip-iOS/pull/59#discussion_r1655308031

위 코멘트를 수정하면서 삭제되었습니다!

2024-06-26 18:28 UTC, serena0720 commented on Projects/Core/Services/KakaoAPI/KakaoAPI.swift
> +      return try? JSONEncoder().encode(body)
https://github.com/mash-up-kr/gabbangzip-iOS/pull/59#discussion_r1655308031

위 코멘트를 수정하면서 삭제되었습니다!

2024-06-26 18:28 UTC, serena0720 commented on Projects/Core/Common/Extensions/URLComponents+extensions.swift
> +    }
https://github.com/mash-up-kr/gabbangzip-iOS/pull/59#discussion_r1655308031

위 코멘트를 수정하면서 삭제되었습니다!

2024-06-26 18:30 UTC, serena0720 commented on Projects/Core/Services/KeyChain/KeyChainClient.swift
> +                             encoding: String.Encoding.utf8)
꼼꼼한 확인 감사합니다 😆

2024-06-26 18:33 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +    public init() {}
오히려 외부에서 넣어주지 않기 위해 default 값으로 준 것인데, 파라미터에서 기본값을 넣어 외부에서 init 호출 시 자동완성되지 않도록 하겠습니다!
> 수정 코드
```swift
    public init(
      errorMessage: String?,
      kakaoUser: KaKaoUserInformation = KaKaoUserInformation(),
      kakaoIdToken: KakaoToken = KakaoToken()
    ) {
      self.errorMessage = errorMessage
      self.kakaoUser = kakaoUser
      self.kakaoIdToken = kakaoIdToken
    }
```

2024-06-26 18:38 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +          }))
유사 케이스 개행 없는 쪽으로 수정하였으나, 개행하고자 할 때 어디서 개행하는 것이 좋을지 조언 부탁드립니다🥹
아래와 같은 형태로 개행하면 될까요?
```swift
await send(
            .loginResponse(
              Result { try await
                kakaoAPIClient.login(
                  idToken,
                  nickname,
                  profileImageUrl
                )
              }
            )
          )
```

2024-06-26 18:40 UTC, serena0720 commented on Projects/DesignSystem/Sources/Views/Lottie/LottieView.swift
> +  private var loopMode: LottieLoopMode
사용하는 곳에서 임의로 루프 횟수를 넣어줄 수 있도록 수정하였습니다!

2024-06-26 18:42 UTC, serena0720 commented on Projects/Core/Services/KakaoAPI/KakaoAPIClient.swift
> +        var request = Request<KakaoResponse>(route: route)
꼼꼼한 리뷰 감사합니다 ☺️ 수정하였습니다!

2024-06-26 22:38 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/Lottie/LottieView.swift
> +  private var loopMode: LottieLoopMode
초기화 시 넣어주면 되지 않는건가요~?
중간에 해당 루프 값이 변경되거나 하나요?

2024-06-26 23:08 UTC, serena0720 commented on Projects/DesignSystem/Sources/Views/Lottie/LottieView.swift
> +  private var loopMode: LottieLoopMode
아 그렇네요 그럼 default값을 삭제하고 상수로 변경하겠습니다!

2024-06-26 23:34 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        Image(uiImage: DesignSystem.Icons.Login.logoUIImage)
현재 Category나 Common 보면 provides-namespace를 지정하지 않고 사용하기에 바로 DesignSystem.Icons.xxx로 사용하면 되는데 Login에 대해서는 provides-namespace를 적용하셨더라구요.
이유가 있을까요?
한쪽으로 통일되면 좋을것 같습니다.
그냥 폴더로 만들어서 provides-namespace를 적용하지 않고 사용하는게 더 빠르지 않을까해요.

추가로, PNG 파일들로 사용하셨으니 1,2,3배수 파일도 같이 넣어두시는것이 좋을것 같습니다.

2024-06-26 23:34 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        ToastView(message: errorMessage)
네네 별도로 처리하시죠!

2024-06-26 23:36 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +          .font(DesignSystemFontFamily.Pretendard.regular.font(size: 21))
현재 사용하는곳에서는 text22를 사용하시는것 같은데, Font에 추가가 안되어서 찾을 수 없네요.
Tuist에서 Font.stencil 파일에서 text22를 추가하셔야합니다.

2024-06-26 23:39 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +          }))
네네 해당 개행 스타일로 해주시면 좋을것 같습니다!

2024-06-26 23:40 UTC, serena0720 commented on Projects/Core/Services/KakaoAPI/KakaoAPIClient.swift
> +          let user = try JSONDecoder().decode(KakaoResponse.self, from: response.data).data
우와 이런 방법이 있었군요🥹
제가 GET에 대한 이해가 아직 부족한 거 같습니다🥲

2024-06-26 23:40 UTC, serena0720 commented on Projects/Core/Services/KakaoAPI/KakaoAPI.swift
> +      return try? JSONEncoder().encode(body)
와... 꼼꼼한 리뷰 감사합니다🙇‍♀️

2024-06-26 23:45 UTC, julia0926 commented
LGTM~

2024-06-26 23:53 UTC, GREENOVER requested changes
시뮬레이터로 실행 시 계속 로그인에 실패하는데 혹시 테스트를 해보셨을까요~?
다른 설정을 해줘야 할까요?
xcconfig 파일은 들어가있는 상태입니다.
```
2024-06-27 08:51:10004 [ℹ️][Api.swift 135:29] -> request: 
 method: HTTPMethod(rawValue: "POST")
 url:https://kauth.kakao.com/api/agt
 headers:nil
 parameters: Optional(["client_id": "780d820d0746affeeb251adf0ade6075"]) 


2024-06-27 08:51:10004 [ℹ️][Api.swift 136:41] -> response:
 Optional({
    error = "invalid_request";
    "error_code" = KOE323;
    "error_description" = "required parameter access_token not presented.";
})
```
에러 문구이니 확인 해보시면 좋을것 같아요!

2024-06-26 23:53 UTC, GREENOVER commented on Projects/App/Sources/RootCore.swift
> +        return .run { send in
```
An "Effect.run" returned from "Dev_Gabbangzip/RootCore.swift:42" threw an unhandled error. …

    KeyChainClientError(
      userInfo: [:],
      code: .failToRead,
      underlying: nil
    )

All non-cancellation errors must be explicitly handled via the "catch" parameter on "Effect.run", or via a "do" block.
```
onAppear 시 여전히 해당 런타임 워닝이 발생합니다.
확인 부탁드려요~

2024-06-26 23:53 UTC, GREENOVER commented on Projects/Core/Services/KakaoAPI/KakaoAPIClient.swift
> +    _ profileImage: String
@zekexros @serena0720 @hope1053 
아마 현재는 바뀌었는지 모르겠지만, enum 해당 케이스에서 와일드 카드 패턴을 사용하지 않아도 에러가 나진 않을거에요~!
말씀하신, Function types cannot have argument labels 에러는 함수 타입에서 발생하는것이라고 보입니다.
`a: (idToken: String, nickname: String) -> Void` 처럼 사용했을 경우
즉, 해당 열거형에선 연관 값 정의 시 인자 레이블을 사용할 수 있어 Function types cannot have argument labels와는 무관할것이고 아마 와일드 카드를 사용하지 않고 컴파일 및 런을 시켜보면 정상적으로 실행되는걸 볼 수 있을거라 생각합니다.

2024-06-26 23:55 UTC, serena0720 commented on Projects/Features/Scene/Project.swift
> +        .external(externalDependency: .lottie)
어떤 걸 말씀하시는 걸까요🥹

2024-06-26 23:56 UTC, GREENOVER commented on Projects/Core/Services/KakaoAPI/KakaoAPIClient.swift
> +    _ profileImage: String
아 맞네요~!
제가 KakaoAPI에 단다는게 여기 달았네요🥲
KakaoAPI에서는 enum 케이스에 명시적으로 사용해주시는것이 좋을것 같아요.
실제 APIClient에서 호출할때 명확히 구분하기가 힘들지 않을까합니다.

2024-06-27 00:08 UTC, GREENOVER commented
+추가로, 하시면서 120자가 넘어가서 Lint 워닝이 나거나 하는 부분도 최종 수정할때 반영해주세요~

2024-06-27 00:11 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +          .font(DesignSystemFontFamily.Pretendard.regular.font(size: 21))
수정하였습니다!

2024-06-27 00:14 UTC, GREENOVER commented
@serena0720 
카카오톡 계정으로 로그인 안되는 이유의 원인은 이거네요.
```
loginWithKakaoAccount: { @MainActor in
        try await withCheckedThrowingContinuation { continuation in
          var scopes = [String]()
          scopes.append("openid")
          
          UserApi.shared.loginWithKakaoAccount(scopes: scopes) { oauthToken, error in
            if let error {
              continuation.resume(throwing: KakaoLoginClientError(code: .failToGetOauthToken))
            } else if let oauthToken {
              continuation.resume(returning: oauthToken.idToken)
            } else {
              continuation.resume(throwing: KakaoLoginClientError(code: .failToLoginWithKakaoAccount))
            }
          }
        }
      }
```
여기서
```
loginWithKakaoAccount: { @MainActor in
        try await withCheckedThrowingContinuation { continuation in
          UserApi.shared.loginWithKakaoAccount { oauthToken, error in
            if let error {
              continuation.resume(throwing: KakaoLoginClientError(code: .failToGetOauthToken))
            } else if let oauthToken {
              continuation.resume(returning: oauthToken.idToken)
            } else {
              continuation.resume(throwing: KakaoLoginClientError(code: .failToLoginWithKakaoAccount))
            }
          }
        }
      }
```
로 하시면 정상적으로 카카오 계정으로 로그인이 되실거에요.
카카오톡으로 로그인 시에는 코드가 달라서 정상적으로 되셨을거같네요.
한번 openID가 어떻게 쓰이고 있고 필요한지 등 점검해보시면 좋을것 같습니다.

2024-06-27 00:40 UTC, namsoo5 approved these changes
그냥 지나가다가 재밌어 보여서 낙서하고 도망갑니다 🏃‍♂️‍➡️

2024-06-27 00:40 UTC, namsoo5 commented on Projects/App/Sources/RootCore.swift
> +        state.isLogin = isLogin
(불청객1)
키체인에 저장하면 거의 영구저장이라
앱을삭제하고 나중에 키거나 카카오 토큰 정보가변하더라도
kakao accessToken을 키체인에 저장해버리고 토큰이 만료됬음에도 `토큰이 존재만 한다면` 정상적으로
로그인이 됬다고 판단하는거같은데
토큰에대한 문제가없다면 넘어가셔요~

2024-06-27 01:17 UTC, AhnSangHee reviewed
![lgtm](https://github.com/mash-up-kr/gabbangzip-iOS/assets/95578975/c2e18583-a1f7-4b24-bbae-498eeb433e2f)

2024-06-27 02:36 UTC, serena0720 commented on Projects/App/Sources/RootCore.swift
> +        return .run { send in
Kakao Developer에 OpenID설정이 되어있어 아래 주신 조언대로 scope가 현재 상황에 맞지도 않으며, 필요도 없을 듯 하네요🥹
조언 감사합니다🙇‍♀️

2024-06-27 03:20 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        Image(uiImage: DesignSystem.Icons.Login.logoUIImage)
아 이미지Set이 아니라 일반 폴더로 생성해야 enum 뎁스가 생성되지 않는군요..!

png파일들은 디자인팀에 전달받는대로 업데이트하겠습니다!

2024-06-27 03:22 UTC, serena0720 commented on Projects/Core/Services/KakaoAPI/KakaoAPIClient.swift
> +    _ profileImage: String
수정했습니다!

2024-06-27 03:24 UTC, serena0720 commented on Projects/App/Sources/AppDelegateCore.swift
> +          await kakaoLoginClient.initSDK(appKey)
상수 선언끼리 모으려고 했는데 오히려 혼돈을 야기했나보네요😅 로직끼리 묶도록 수정했습니다~

2024-06-27 03:46 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +        Text("우리가 픽! 하는\n우리끼리 네컷앨범")
디자인팀에서 고정값을 주어 해당 고정값에 맞추어 잡았습니다🥹
flexable하게 갈 수 있는 방법 조언해주시면 감사하겠습니다!

2024-06-27 04:01 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +          await send(.saveRefreshTokenInKeyChain(user?.refreshToken ?? ""))
에러처리했습니다🙇‍♀️

2024-06-27 05:22 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +  public init() {}
Reducer의 init을 보통 어디에 위치 시키나요?🥺

2024-06-27 08:31 UTC, zekexros approved these changes
고생하셨습니다👏👏👏

2024-06-27 08:31 UTC, zekexros commented on Projects/App/Sources/RootCore.swift
> +        }
P2:
```swift
static func run(
        priority: TaskPriority? = nil,
        operation: @escaping (Send<RootCore.Action>) async throws -> Void,
        catch handler: ((any Error, Send<RootCore.Action>) async -> Void)? = nil,
        fileID: StaticString = #fileID,
        line: UInt = #line
    ) -> Effect<RootCore.Action>
```
run의 catch 파라미터를 사용하여 에러를 처리할 수 있습니다

2024-06-27 08:31 UTC, zekexros commented on Projects/App/Sources/RootView.swift
> +      store.send(.checkAccessToken)
```suggestion
      store.send(.onAppear)
```
View로부터 받는 액션은 Modifier 혹은 컴포넌트의 이름과 최대한 연관지어 명명하면 Reducer내에서 로직 구조를 이해하기 편리하다는 장점이 있습니다

2024-06-27 08:31 UTC, zekexros commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +            }
P4:
Reducer에서 `@Dependency(\.mainQueue)`를 활용하는 방법도 고려해보면 좋겠습니다.

2024-06-27 11:16 UTC, serena0720 commented on Projects/App/Sources/RootCore.swift
> +        }
operation이 자동 throws가 되는군요! do-catch보다 편하게 사용가능할 거 같네요!

2024-06-27 11:26 UTC, GREENOVER reviewed
현재 앱 실행후 카카오 최초 로그인 후에 다시 로그인 뷰로 돌아왔을때 자동으로 로그인된 이후의 뷰로 가지 않고 앱을 재실행 시 메인뷰로 이동하는것 같은데, 구현이 덜 된건가요? 🙋🏻
확인 부탁드립니다~!

2024-06-27 11:26 UTC, GREENOVER commented on Projects/Core/Services/KakaoLogin/KakaoLoginClient.swift
>              if let error {
```suggestion
            if error != nil {
```
error를 if let 바인딩하고 쓰는곳이 없어 아마 워닝으로 알려줄것같은데요.
이렇게 해당 바인딩 값을 사용하지 않으면 적용하는것이 좋을것 같아요.
한번 전체적으로 다른 부분들도 컴파일 워닝을 띄우는곳이 있다면 수정해주시면 좋겠습니다 🙋🏻

2024-06-27 11:50 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +            }
적용했습니다!

2024-06-27 18:12 UTC, serena0720 commented
@GREENOVER 자동로그인 기능을 말씀하시는 거 같은데 별도 이슈 생성해서 진행하는 것을 어떤가욤?

2024-06-27 22:34 UTC, GREENOVER commented
@serena0720 
아하 앱 재실행 시에는 자동 로그인 여부를 가지고 메인 뷰를 띄워준것처럼 최초 로그인 후 성공 시 메인 뷰를 띄워주는 작업에 대해 조금 더 생각할 부분이 필요한건가요~?
이미 체크 로직이 있다고 생각했는데, 해당 PR 이후 별도 이슈로 바로 작업하셔도 됩니다!
편하게 하세요ㅎㅎ

2024-06-28 05:57 UTC, GREENOVER commented on Projects/App/Project.swift
> +        .project(target: .mainCoordinator, projectPath: .coordinator),
어떻게 논의되고 결정되셨을까요?
변경 사항이 있다면 반영해주시면 좋을것 같습니다~

2024-06-28 06:15 UTC, GREENOVER requested changes

2024-06-28 06:15 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateCore.swift
> +      case .showError:
에러에 대한 처리는 실제 없는건가요~?

2024-06-28 06:15 UTC, GREENOVER commented on Projects/App/Sources/RootCore.swift
> +    case showError(Error)
여기서도 에러 타입을 만들어서 사용하는건 어떤가요?

2024-06-28 06:15 UTC, GREENOVER commented on Projects/Core/Models/Kakao/Response/KakaoErrorResponse.swift
> +public struct KakaoErrorResponse: Decodable {
만약 에러 리스폰스가 API들마다 공통적인 폼이라면 공통으로 처리하는건 어떨까요?

2024-06-28 06:15 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +          DesignSystem.Icons.logo
컴포넌트 단위당 개행을 하시면 가독이 더 나을것 같습니다~!

2024-06-28 06:15 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +      ZStack {
ZStack을 쓸 이유가 없어보입니다.
무분별한 ZStack은 성능 저하를 초래합니다. 뷰 디버깅을 떠보시면 뷰가 쌓이는 구조라서요.

2024-06-28 06:15 UTC, GREENOVER commented on Tuist/ResourceSynthesizers/Fonts.stencil
> +    guard let font = UIFont(font: self, size: 22) else {
추가된 코드들만 인덴트가 깃헙으로 볼때 다른것 같은데 맞을까요?

2024-06-28 06:43 UTC, serena0720 commented on Projects/App/Sources/AppDelegateCore.swift
> +      case .showError:
사실 AppDelegate에서 발생되는 에러를 화면에 보여줘야하는 것인지 아니면 디버깅용으로 print를 찍어야하는지 대한 의문이 들긴했습니다.
현재 별도의 처리를 하지 않은 것은 아래 코드를 참고한것인데 에러 처리에 대한 조언이 있다면 부탁드립니다!
```swift
  case let .authorizationStatusResposne(.success(status)):
    return .none
    
  case let .authorizationStatusResposne(.failure(error)):
    return .none
```

2024-06-28 07:03 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateCore.swift
> +      case .showError:
기획 단계에서 없었기에 사용자에게 안보여줘도 현재는 괜찮긴 하겠지만, 개발용 디버그 로그는 남기는게 좋을것 같습니다.
Debuglogger를 구현해뒀으니 해당 PR 참고하시어 사용해보시몀 좋을것 같아요.

2024-06-29 08:16 UTC, GREENOVER approved these changes
수고하셨습니다~

2024-06-29 08:16 UTC, hope1053 approved these changes

2024-06-29 08:17 UTC, merged