[Feat] 자동 로그인 구현 및 ToastView 적용
mash-up-kr/gabbangzip-iOS pull request #71
Opened 2024-07-02 02:45 UTC by serena0720

## 📌 Related Issue
- #63

## 🚀 Description
- 자동 로그인을 구현하였습니다.
- DesignSystem의 ToastView를 적용하였습니다.

## ✅ Done
- AccessToken 만료 시 RefreshToken으로 Token 유효성을 체크하고, Token이 유효하지 않다면 로그인 화면으로 전환됩니다.
- 로그인 완료 후 "로그인이 되었습니다." 페이지로 넘어가게 구현하였습니다.

## 📸 Screenshot
<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/101619749/6dd63a57-6780-4454-a697-23c9d0f0689b"  width="200" height="400">

## 📢 Notes
- GroupMain 페이지가 완료되면, Group에서 호출하는 API에서 에러 발생 시 인터셉트하는 쪽으로 수정되어야합니다.
> TestInformation, KakaoAPI의 testToken, KakaoAPIClient의 testToken

- 현재 AccessToke, RefreshToken 모두 만료가 한달인 상태여서 API 테스트에 어려움이 있습니다.

2024-07-02 06:11 UTC, GREENOVER requested changes
우선 일정이 촉박한 관계로 코드 리뷰 전 동작에 관련하여 먼저 피드백을 드리는게 좋을것 같습니다.
현재 자동 로그인은 되지만, 로그인 뷰가 잠시 나왔다가 바로 이후 메인 뷰로 넘어가는것이 좋은 동작은 아닌것 같아요.
그렇기에, 간단히 RootCore State의 isLogin 초기값을 true로 하여 어색한 부분을 처리할 수도 있고 로직적으로 다시 검토해서 자연스럽게 만드는 방법도 있을것 같습니다.

한번 이 부분 자연스러운 동작이 되도록 수정 부탁드립니다 🙏🏻

2024-07-02 11:17 UTC, serena0720 commented
@GREENOVER 꼼꼼한 확인 감사합니다! 기본값을 true로 변경하니 로그인 완료후 넘어오는 동작이 보다 자연스럽네요!👍 이미 기존 로직이 default 값에 상관없이 케이스별로 Bool값을 지정해놔서 default 값 수정만 하였습니다!

2024-07-02 11:56 UTC, serena0720 commented
```
objc[83965]: Class _TtC6Common11DebugLogger is implemented in both
...KakaoLogin.framework/KakaoLogin (0x106fbe550) and ...Dev_Gabbangzip.app/Dev_Gabbangzip (0x104e51b18). One of the two will be used. Which one is undefined.

objc[83965]: Class _TtC6Common8SwiftLog is implemented in both
...KakaoLogin.framework/KakaoLogin (0x106fbe650) and Dev_Gabbangzip.app/Dev_Gabbangzip (0x104e51c18). One of the two will be used. Which one is undefined.
```
해당 에러가 발생하여 확인해보니 kakaoLogin 프레임 워크 내부에 이미 DebugLogger와 SwiftLog가 구현되어 있어, 해당 프레임워크에 디팬던시를 갖는 객체의 경우 저희가 custom한 logger가 아닌 일단 print 문으로 대체하였습니다🙇‍♀️

추가 의견이 있으면 남겨주세욤!

2024-07-03 01:54 UTC, GREENOVER approved these changes
우선 동작에는 문제가 없으니 어프합니다!
2~3주남은 관계로 먼저 작업부터 쳐내고 추후 리팩토링을 해봐도 좋을것 같아요 😃

2024-07-03 06:43 UTC, zekexros requested changes
Model과 관련하여 논의된 사항을 참고하여 ReqDTO, ResDTO, Entity로 분리 및 네이밍을 수정해주시면 Approve하겠습니다

2024-07-03 07:46 UTC, zekexros approved these changes

2024-07-03 12:54 UTC, merged