[Design] 그룹 상세 및 그룹원 리스트 페이지 UI 구현
mash-up-kr/gabbangzip-iOS pull request #77
Opened 2024-07-03 16:08 UTC by hope1053

## 📌 Related Issue
- #58 

## 🚀 Description
그룹 상세 페이지와 그룹원 리스트 페이지 UI를 구현했습니다.

## ✅ Done
- [x] 그룹 상세 페이지 UI 구현
- [x] 그룹원 리스트 페이지 UI 구현

## 📸 Screenshot
![image](https://github.com/mash-up-kr/gabbangzip-iOS/assets/22907483/792d95e9-57ec-400e-96de-c38169a25602)
![image](https://github.com/mash-up-kr/gabbangzip-iOS/assets/22907483/8fae2248-3a10-4b34-ad5a-ed1a257737d1)

## 📢 Notes
현재 구현해놓은 Model 부분은 API 확인하기 전에 구현해놓은 부분이라 API 붙이는 이슈 생성 및 처리할 때 수정할 예정입니다 ~!
그룹원 리스트 페이지에서 그룹원 수에 따라 링크 복사하기 버튼 활성/비활성화 처리 부분도 API 붙이면서 같이 구현할 예정입니다!
 
## 🧪 Testing(optional)

2024-07-03 23:30 UTC, GREENOVER requested changes, later dismissed
고생하셨습니다 ㅎㅎ
현재 뷰만 있어서 조금 짜잘한 부분까지 리뷰드렸어요.
피그마와 다 대조해보진 않아서, 디자인 수치나 그런거까지 꼼꼼히 보기보다 코드적인 부분만 저는 봤습니다 🙋🏻

2024-07-03 23:30 UTC, GREENOVER commented on Projects/DesignSystem/Resources/Icons.xcassets/Common/share.imageset/Contents.json
> +      "filename" : "Group 5024.svg",
왠만하면 파일 네임도 맞추는게 어떤가요?

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +import NukeUI
요 컨벤션은 다같이 통일되면 좋을것 같습니다.
한번 의견 나눠보시죠~
@zekexros @serena0720

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +public struct EventContainerView: View {
public하지 않아도 될듯 합니다~

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +  let eventDetail: EventDetail
private해도 될듯합니다 🙋🏻

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +
한줄 개행 더 들어간듯

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventProgressView.swift
> +  let eventDetail: EventDetail
private해도 될듯합니다 ㅎㅎ

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventProgressView.swift
> +        }
이미지 불러오기 실패가 되거나 할때 대체 이미지는 필요없는거죠~?
추가로, 해당 image를 불러왔을때 이미지가 수평 72 패딩을 가지면서 그에 맞게 비율이 조정될텐데, 이미지마다 제각각 가로/세로 비율이 다르다면 height가 달라질텐데 그건 괜찮나요?

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventProgressView.swift
> +  var button: some View {
어떤 용도의 버튼인지 네이밍도 명확했으면 좋겠습니다.
코드만 보고 유추하기가 힘듭니다 🥲

그리고 해당 관련 코드들은 다른 파일로 분리해도 괜찮을것 같아요.

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/ShareButton.swift
> +struct ShareButton: View {
공유버튼에서 action을 사용하는곳이 없어보입니다.

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +//  PICListView.swift
주석 파일명과 실제 파일명이 다르네요 🤔

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +  var columns = [GridItem(spacing: 33), GridItem(spacing: 33)]
프로퍼티는 프로퍼티끼리 상단에서 같이 노출시키는게 현재 컨벤션과 가독성에 좋을것 같습니다 ㅎㅎ

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +  var events: [EventItemInfo]
외부에서 접근할 일이 있나요?

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +  var galleryView: some View {
외부에서 접근할 일이 있나요?

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +      Spacer()
개행하면 컨벤션에 맞을것 같아요 ㅎㅎ

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +    ScrollView {
기본적으로 스크롤 인디케이터가 보일텐데 요것도 노출시킬지 미노출시킬지 말씀 나눈게 있나요~?

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +  var columns = [GridItem(spacing: 33), GridItem(spacing: 33)]
디바이스에 따라 양쪽 패딩 값이 증가되는것이 기획인가요?

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventItemView.swift
> +  var eventInfo: EventItemInfo
외부에서 호출될 일이 있나요~?

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
> +    }
파라미터 1개이면 그냥 개행없이 하는것이 컨벤션이였어서 따르시는게 좋을것 같아요ㅎㅎ

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +  @State private var showSheet = true
요것도 추후 코어 State에서 관리되는거라고 볼 수 있나요?
왠만하면 모든 상태 관리를 하는건 State에서 하는것이 좋을것 같습니다.

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +  let store: StoreOf<GroupDetailCore>
외부에서 호출될 일이 있나요?

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +    ScrollView {
요기도 인디케이터 노출할지 논의해보시고 가면 좋을것 같습니다.

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +  var dividerView: some View {
private

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +  var dividerView: some View {
만약 디바이더가 다른곳에서도 비슷한 색상이나 height들로 어느정도 규격으로 사용된다면 DS에 추가하여 사용해도 될듯 합니다.

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +        .scrollIndicators(.hidden)
굳이 뷰 모디파이어로 넣을 필요가 있나요?
해당 EventGridView에서 scrollView 구현 시 showIndicator 파라미터 값을 변경하면되지 않을까 생각이 들어서 남겨봅니다!

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +        .presentationBackgroundInteraction(.enabled(upThrough: .large))
마지막 괄호 개행있으면 좋을것 같습니다.

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +      Spacer()
디자인 피그마 상 + 버튼이 우측에 있는것 같았는데 여긴 없는데 확인 부탁드립니다~

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +}
별도 파일로 분리해주시면 좋을것 같아요~
ViewHeightKey 같은 경우 추후 다른곳에서도 충분히 사용될수도 있습니다.

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +extension UIScreen {
공통된 UIScreen 확장이라면 Common/Extensions에 넣어도 될듯합니다.
그런데 제거할 예정이라면 편하게 하시면 되구요!

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberView.swift
> +  let groupCategory: GroupCategory
private하고 이니셜라이저를 통해 생성하는걸 생활화 해보기~

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberView.swift
> +//  MemberView.swift
MemberListView에 종속된 ChildView라면 확실히 구분될 수 있게 폴더링으로 묶는건 어떤가요?
현재는 MemberListView하고 같은 선상이라 헷갈릴 여지도 있어서요.

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberView.swift
> +      logoImageFrom(
파라미터 하나라 개행없이 해도 충분해 보입니다.

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberView.swift
> +  func logoImageFrom(
파라미터 하나라 개행없이 해도 충분해 보입니다.

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberView.swift
> +  func logoImageFrom(
MemberView에서 groupCategory를 이용하는 단순한 조건으로 보이는데, 연산 프로퍼티를 활용하지 않고 메서드로 하신 이유가 궁금합니다 🙋🏻
(잘못되었다는거 아님)

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberView.swift
> +        if member.isLeader {
한줄 개행하면 좋을듯해요

2024-07-03 23:30 UTC, GREENOVER commented on graph.png
지우고 올려주세요~
아니면 gitignore에 추가해도 되구요!
어차피 계속 바뀔거고, 굳이 리모트에 들고 있을 이유가 없어 용량을 잡아먹을 필요가 없어보입니다!

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +  let store: StoreOf<MemberListCore>
private

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +          .foregroundStyle(DesignSystem.Colors.gray50)
피그마상에는 gray60으로 잡히던데 한번 확인 부탁드립니다~!

2024-07-03 23:30 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +      .padding(.top, 102)
해당 수치는 어떻게 정해진걸까요?
피그마상에선 중구난방이기도 해보여서요 🙋🏻
2명일때와 6명일때 다르고 심지어 102란 수치를 찾을수가 없어서 여쭤봅니다~
![스크린샷 2024-07-04 오전 8 26 40](https://github.com/mash-up-kr/gabbangzip-iOS/assets/72292617/32b346c6-1849-48b7-a834-7f52e2ef0c19)

2024-07-03 23:48 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +import NukeUI
@GREENOVER 아 이거 제가 컨벤션에 맞춘다고 했는데 수정하는걸 깜빡했네요🫠 수정해서 푸시해놓을게요 ~~!!

2024-07-03 23:51 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +public struct EventContainerView: View {
@GREENOVER 템플릿이 다 public으로 선언돼있어서 생성한 그대로 사용해서 public이 붙어있었네여 💦 수정하겠습니다~ 템플릿도 같이 수정할까요?

2024-07-04 00:56 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +public struct EventContainerView: View {
음 public으로 필요한 부분도 파일도 분명 존재할거라, 둘중 택하면 될듯합니다!
- public으로 템플릿하고 필요할때 수정
- internal로 템플릿하고 필요할때 수정
더 끌리는걸루 하시져~

2024-07-04 02:16 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +      Spacer()
@GREENOVER Text랑 Spacer 사이 말씀하시는건가요 ?!

2024-07-04 02:54 UTC, zekexros requested changes
모든 코드에 ctrl+i 누르셨나요? 매개변수가 한 개 혹은 두 개일 경우, 줄바꿈을 하지 않아도 괜찮을 듯합니다

전반적으로 잘 구현된 것 같습니다👍

2024-07-04 02:54 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/ShareButton.swift
> +      .cornerRadius(14)
P5
Button이라고 되어 있지만 Image만 선언되어 있는 것을 보니 `eventCompleted` 케이스 구현 시 한꺼번에 적용하려고 아직 미구현 상태로 두신거죠?

2024-07-04 02:54 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +  @State private var showSheet = true
P1:
코어 State에서 관리되게 수정해주세요

2024-07-04 02:54 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
> +        return .none
P2:
연관값을 state로 명명하면 기존의 state와 혼동될 수 있습니다

2024-07-04 02:54 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +      }
```suggestion
      ForEach(store.memberList, id: \.self) { member in
        MemberView(
          member: member,
          groupCategory: store.groupCategory
        )
      }
```
`Member`가 equatable 대신 hashable을 채택한다면 위와 같이 작성할 수 있습니다. 그럼 멤버의 `id` 속성도 제거가 가능하답니다

2024-07-04 02:54 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +          store.send(.backButtonDidTap)
```suggestion
          store.send(.backButtonTapped)
```
이건 컨벤션 문제인데 버튼 액션에서 Tapped 혹은 DidTap을 자주 사용하는데 여기서 의견을 받아 통일시키면 어떨까요
저는 Tapped가 더 익숙합니다 @GREENOVER  @serena0720

2024-07-04 03:06 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +      Spacer()
YES

2024-07-04 03:09 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +          store.send(.backButtonDidTap)
저도 tapped 스타일로 쓰긴 합니다~
여러분 편하신대로!

2024-07-04 03:13 UTC, serena0720 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +          store.send(.backButtonDidTap)
이전 PR에서 ~~ButtonTapped로 구현해놔서 이쪽으로 통일하는 거에 동의합니다!

2024-07-04 04:04 UTC, serena0720 reviewed
뷰가 너무 예쁘게 잘 나온 거 같아요👍
다만 Figma에 보면 GroupDetailView > NaviagtionBar > rightIconAction에 + 버튼도 있는 듯한데 이 부분에 대한 기능이 명확하지 않아 디자인팀과 협의하시고 수정이 필요할 수도 있을 거 같습니다💪

2024-07-04 04:04 UTC, serena0720 commented on Projects/Core/Models/GroupDetail/GroupCategory.swift
> +import Foundation
P2: 해당 import는 필요없을거 같습니당~

2024-07-04 04:04 UTC, serena0720 commented on Projects/Core/Models/GroupDetail/EventDetail.swift
> +    case .noPastAndCurrentEvent, .noCurrentEvent, .eventCompleted:
P4: 가독성 및 컨벤션 통일을 위해 case 분리하는건 어떤가용?

2024-07-04 04:04 UTC, serena0720 commented on Projects/Core/Models/GroupDetail/MemberList.swift
> +public typealias MemberList = [Member]
P5: typealias를 맨 위에 위치시키는건 어떤가요?

2024-07-04 04:04 UTC, serena0720 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +        .fill(.red)
P5: case 사이 한줄 띄어쓰기해주세용

2024-07-04 04:04 UTC, serena0720 commented on Projects/Core/Models/GroupDetail/EventDetail.swift
> +      date: "2024년 6월 10일",
P2: Figma에 있는 날짜 양식과 다릅니다 확인해주세용

2024-07-04 04:04 UTC, serena0720 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventProgressView.swift
> +            .padding(.horizontal, 72)
P2: Figma에 Image x 간격이 76인 거 같은데 확인해주세용!

2024-07-04 04:04 UTC, serena0720 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventProgressView.swift
> +      return nil
P5: case 사이 개행하면 좋을 거 같아용

2024-07-04 04:20 UTC, serena0720 commented on Projects/Core/Models/GroupDetail/EventDetail.swift
> +      date: "2024년 6월 10일",
이부분 디자인시스템 변경 PR merge되면 구현되어있는 타입 사용하셔도 될 거 같아요

2024-07-04 04:54 UTC, serena0720 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +}
P2: 이전 PR에서 아래와 같이 컨벤션을 맞춰서 store init 시 컨벤션 맞춰주세용❤️
```suggestion
#Preview {
  GroupDetailView(
    store: Store(
      initialState: .init(groupDetail: GroupDetail.emptyMock),
      reducer: GroupDetailCore.init
    )
  )
}

// 이벤트 목록 있는 경우
#Preview {
  GroupDetailView(
    store: Store(
      initialState: .init(groupDetail: GroupDetail.mock),
      reducer: GroupDetailCore.init
    )
  )
}
```

2024-07-04 09:56 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +          store.send(.backButtonDidTap)
넵 그럼 Tapped로 통일하도록 하겠습니다~!

2024-07-04 10:01 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberView.swift
> +  let groupCategory: GroupCategory
스유로 뷰 그리는데 집중하다 보니 이런 기본적인걸 많이 빠트렸네요...💦 다음부턴 잘 챙기도록 하겠습니다 ~!

2024-07-04 10:04 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +      .padding(.top, 102)
제가 보고 구현했을 때랑 디자인이 수정 & 추가된 것 같아요! 해당 레이아웃 관련 논의해서 반영해두록 하겠습니다~!

2024-07-04 10:14 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +  var dividerView: some View {
@GREENOVER 해당 페이지말고 다른 한군데서만 사용되고 있어서 일단 DS로 빼지않고 두겠습니다...^_^

2024-07-04 10:15 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +//  PICListView.swift
나중에 네이밍을 바꾸다보니...🫠 수정해두겠습니다 ㅎㅎ

2024-07-04 10:26 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventProgressView.swift
> +        }
@GREENOVER 넵 그럴 때 그냥 빈 화면으로 두기로 논의했습니다! 그리고 해당 이미지 추후 프레임 씌운 정방향 뷰로 수정될 예정이라 반영하면서 레이아웃 한 번 더 체크하도록 하겠습니다 🫡

2024-07-04 10:29 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/ShareButton.swift
> +struct ShareButton: View {
어이구 이걸 빼먹었네요...반영 완료 👍

2024-07-04 10:32 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +  var columns = [GridItem(spacing: 33), GridItem(spacing: 33)]
@GREENOVER 해당 부분 논의 후 반영해두겠습니다~!

2024-07-04 10:35 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +    ScrollView {
@GREENOVER 요것도 논의 후 반영해두겠습니당^_^

2024-07-04 10:45 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +extension UIScreen {
@GREENOVER 추후 제거할 예정이긴한데 일단 코드 정리를 위해 이동시켜놓겠습니다~!

2024-07-04 10:56 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +}
@GREENOVER 분리를 하게 되면 다른 모듈에서도 사용할 수 있게 Common - Views에 위치 시킬까 하는데 어떻게 생각하시나요?!

2024-07-04 10:59 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +      Spacer()
@GREENOVER 있는 화면, 없는 화면이 지금 혼재돼있어서 확인 후 반영해놓겠습니다!

2024-07-04 11:02 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +}
goood

2024-07-04 11:03 UTC, hope1053 commented on Projects/Core/Models/GroupDetail/EventDetail.swift
> +      date: "2024년 6월 10일",
@serena0720 추후 API 연동 시 수정해서 올리겠습니다!

2024-07-04 11:06 UTC, hope1053 commented on Projects/Core/Models/GroupDetail/EventDetail.swift
> +    case .noPastAndCurrentEvent, .noCurrentEvent, .eventCompleted:
case는 이대로 두는걸로 합의봤습니다~👍

2024-07-04 11:10 UTC, hope1053 commented on Projects/Core/Models/GroupDetail/MemberList.swift
> +public typealias MemberList = [Member]
```suggestion
public typealias MemberList = [Member]

public struct Member: Equatable, Identifiable {
```

이런 식으로 Member 선언 전에 말씀하시는거죠? 혹시 이유가 있을까요 ?!

2024-07-04 11:13 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +        .fill(.red)
싫다면요 ⁉️

2024-07-04 11:15 UTC, chansooo requested changes, later dismissed
.

2024-07-04 11:16 UTC, serena0720 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +        .fill(.red)
구웃

2024-07-04 11:20 UTC, serena0720 commented on Projects/Core/Models/GroupDetail/MemberList.swift
> +public typealias MemberList = [Member]
typealias로 지정한 타입을 찾기 위해 해당 파일로 들어왔을 때 맨 위에 있는 것이 찾기 편할거 같다고 생각해서요! 하지만 현재 tyealias의 경우 User-Defined 타입이기 때문에 Member타입 정의가 완료된 후 선언해야한다고 생각하신다면 그것도 충분히 설득력 있다고 생각해용

2024-07-04 11:26 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListView.swift
> +      }
@zekexros 오 너무 좋은데요~~? 공부 더 해봐야겠습니다...감사합니다 🙇‍♀️

2024-07-04 11:27 UTC, klmyoungyun reviewed
![image](https://github.com/mash-up-kr/gabbangzip-iOS/assets/48887389/6388fcf1-f4eb-4500-80a9-92529cdd61f4)

2024-07-04 11:28 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +}
@serena0720 요고 아마 템플릿에 GroupDetailCore() 이런식으로 돼있을거예요. 혹시 그 부분 수정해주실 수 있나요? 😋 앞으로 만들 프리뷰들을 위해 ㅎㅎㅎㅎ 현재 만들어져있는 부분들은 수정하겠습니다!

2024-07-04 11:31 UTC, serena0720 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventProgressView.swift
> +      return nil
@hope1053 이거도 싫어요?🥹

2024-07-04 11:31 UTC, GREENOVER commented
@namsoo5

2024-07-04 11:34 UTC, hope1053 commented on Projects/Core/Models/GroupDetail/MemberList.swift
> +public typealias MemberList = [Member]
저는 말씀하신 이유 때문에 뒤 쪽에 배치하긴 했습니다! 타입 찾으러 갈 때 command + 클릭으로 찾아가면 어차피 해당 타입 선언된 부분으로 포커스 이동까지 돼서 지금 상태로 두는 것도 나쁘지 않을 것 같다는 의견입니다 😄

2024-07-04 11:35 UTC, serena0720 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +}
싫다면요⁉️

2024-07-04 11:37 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +}
그럼 저도 수정안해요.

2024-07-04 11:38 UTC, serena0720 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +}
싫다면요⁉️

2024-07-04 11:41 UTC, dittoo8 submitted a review, later dismissed
그냥 반려하고 싶은 기분이에요

2024-07-04 11:42 UTC, serena0720 commented on Projects/Core/Models/GroupDetail/MemberList.swift
> +public typealias MemberList = [Member]
![스크린샷 2024-07-04 오후 8 42 31](https://github.com/mash-up-kr/gabbangzip-iOS/assets/101619749/716c6901-7f10-42a2-8ed0-a80d867612e4)
진행시키시죠

2024-07-04 11:43 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/ShareButton.swift
> +      .cornerRadius(14)
@zekexros 사실 깜빡하기도 했습니다 .. ㅎㅎ 근데 말씀하신대로 eventCompleted 케이스 구현도 필요해서 API 연동하면서 관련 기능 구현할 예정입니다~!

2024-07-04 11:43 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventProgressView.swift
> +      return nil
네..

2024-07-04 11:43 UTC, AhnSangHee submitted a review, later dismissed
![CleanShot 2024-07-04 at 20 43 05@2x](https://github.com/mash-up-kr/gabbangzip-iOS/assets/95578975/16bdd43d-407c-4cb3-9ac2-fcbccd95d776)
여러분 윈터 보고 가세요~

2024-07-04 11:56 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +        .presentationBackgroundInteraction(.enabled(upThrough: .large))
어떤 개행 말씀하시는건가요 ?! suggestion 한번만 부탁드립니다 ...

2024-07-04 15:16 UTC, zekexros approved these changes
![image](https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/6bf826c4-6b78-4e7e-bf2e-0200fa69473d)

2024-07-04 15:33 UTC, serena0720 approved these changes
고생했오~~❤️

2024-07-04 16:03 UTC, klmyoungyun reviewed
![image](https://github.com/mash-up-kr/gabbangzip-iOS/assets/48887389/1001e464-c4ab-4c07-9b57-386fb5b216e3)

2024-07-04 16:03 UTC, klmyoungyun commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
> +        return .none
아아 위에 액션 순서 맞춰줘잉

2024-07-04 16:03 UTC, klmyoungyun commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
> +      case let .eventContainerViewButtonTapped(eventState):
```suggestion
      case .eventContainerViewButtonTapped:
        return .none
```

2024-07-04 16:04 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
> +      case let .eventContainerViewButtonTapped(eventState):
나중에 쓸건데요? ㅋㅋ

2024-07-04 16:13 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailCore.swift
> +        return .none
시러잉.

2024-07-04 21:34 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberView.swift
> +  func logoImageFrom(
@hope1053 대답

2024-07-04 23:39 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberView.swift
> +  func logoImageFrom(
아 연산프로퍼티로 처리해도 좋을 것 같네요! MemberView가 카테고리값을 갖고 있는걸 놓친 듯 합니다 ㅎㅎ

2024-07-04 23:49 UTC, JaesungLeee commented
가족같은 분위기라길래 옆집에서 놀러왔습니다 화이링~

<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/51078673/3b596577-f577-45e0-a4d5-c90fa3609bf6" width=300 />

2024-07-04 23:59 UTC, GREENOVER commented
@JaesungLeee 
꼼꼼한 리뷰 부탁드립니다 🙏🏻

2024-07-05 00:10 UTC, hope1053 commented
> @JaesungLeee 꼼꼼한 리뷰 부탁드립니다 🙏🏻

나가주세요...

2024-07-05 00:11 UTC, JaesungLeee reviewed
리뷰어에 대한 배려 좀 부탁드려요 천줄 언제 다 읽어요?

<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/51078673/2055714f-76de-41ad-ab44-5a03ca2a93dc" width=400 />

2024-07-05 00:11 UTC, JaesungLeee commented on Projects/Core/Models/GroupDetail/EventDetail.swift
> +    self.state = state
너무 파이썬 스러워요 우우우

2024-07-05 00:11 UTC, JaesungLeee commented on Projects/Core/Models/GroupDetail/EventDetail.swift
> +  case noCurrentEvent
너무 자바스러워요 우우우

2024-07-05 00:11 UTC, JaesungLeee commented on Projects/Core/Models/GroupDetail/EventDetail.swift
> +      return nil
nil 상당히 짜치네요 우우우

2024-07-05 00:11 UTC, JaesungLeee commented on Projects/Core/Models/GroupDetail/MemberList.swift
> +  public static var mockList: [Member] {
@GREENOVER 는 왜빼요 둘이 사이 안좋아요? 우우우

2024-07-05 00:11 UTC, JaesungLeee commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +    action: @escaping (EventState) -> Void
별 희한한 어노테이션이 있네요? 우우우

2024-07-05 00:11 UTC, JaesungLeee commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +      ForEach(events) { picInfo in
코틀린 따라하지 마세요. 우우우

2024-07-05 00:12 UTC, ddyeon reviewed
고생하셧네요^^
![images](https://github.com/mash-up-kr/gabbangzip-iOS/assets/53086454/c3b40066-9dc9-4761-8682-12a50b6286e7)

2024-07-05 00:14 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/GroupDetailView.swift
> +        .presentationBackgroundInteraction(.enabled(upThrough: .large))
@GREENOVER 대답

2024-07-05 00:15 UTC, ddyeon commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +  private var action: (EventState) -> Void
let보단 val이죠.

2024-07-05 00:18 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +  private var action: (EventState) -> Void
val이 뭐예요 ;;

2024-07-05 00:18 UTC, JaesungLeee commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventContainer/EventContainerView.swift
> +  private var action: (EventState) -> Void
공부좀 하세요 공부좀.

2024-07-05 00:22 UTC, GREENOVER commented on Projects/Core/Models/GroupDetail/MemberList.swift
> +  public static var mockList: [Member] {
그러네;;;;;; 진짜 왜지

2024-07-05 00:22 UTC, hope1053 commented on Projects/Core/Models/GroupDetail/EventDetail.swift
> +    self.state = state
어떤 점에서 그렇게 생각하셨을까요? 🤔

2024-07-05 00:23 UTC, hope1053 commented on Projects/Core/Models/GroupDetail/EventDetail.swift
> +  case noCurrentEvent
어떤 점에서 그렇게 생각하셨을까요? 🧐

2024-07-05 00:23 UTC, hope1053 commented on Projects/Core/Models/GroupDetail/EventDetail.swift
> +      return nil
suggestion 부탁드려요 🙇‍♀️

2024-07-05 00:24 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +      ForEach(events) { picInfo in
코틀린이 스위프트 따라했다고 생각은 안해보셨나봐요?

2024-07-05 00:24 UTC, JaesungLeee commented on Projects/Core/Models/GroupDetail/MemberList.swift
> +  public static var mockList: [Member] {
@hope1053 해명 부탁드려요.

<img width="300" alt="image" src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/51078673/25c9e9d3-f0ef-4ce9-9da7-040a69c9727e">

2024-07-05 00:24 UTC, GREENOVER approved these changes
고통에서 벗어나라

2024-07-05 00:26 UTC, merged

2024-07-05 00:26 UTC, namsoo5 commented
메일이 너무와요 빨리좀 처리해주세요😊

2024-07-05 00:28 UTC, JaesungLeee commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +      ForEach(events) { picInfo in
이 발언에 대해 어떻게 생각하시나요?

@ddyeon @014967 @EvergreenTree97 @Ahn-seokjoo @SEO-J17 @fbghgus123 @sooziini @hj1115hj @Sookhee @ze-zeh @oreocube @JeonK1

2024-07-05 00:34 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/GroupDetail/EventGrid/EventGridView.swift
> +      ForEach(events) { picInfo in
![스크린샷 2024-07-05 오전 9 34 38](https://github.com/mash-up-kr/gabbangzip-iOS/assets/72292617/3af2ea7f-af17-4737-8e02-2044b378cfc8)
라고 하는데 검증은 여러분들이~