[Feat] 마이페이지, 로그아웃, 회원탈퇴 , UNUserNotificationCenterClient, UIApplicationClient 구현
mash-up-kr/gabbangzip-iOS pull request #84
Opened 2024-07-06 17:07 UTC by serena0720

## 📌 Related Issue
- #46 

## 🚀 Description
- 마이페이지 UI 구현하였습니다.
- 로그아웃, 회원탈퇴 구현하였습니다.
- UNUserNotificationCenterClient 구현하였습니다.
- UIApplicationClient 구현하였습니다.

## ✅ Done
- 마이페이지 UI 구현하였습니다.
> 앱 알림 버튼 클릭 시 앱 설정으로 이동됩니다.
> 로그아웃, 회원탈퇴 PopupView를 구현하였습니다.
- 기존 PopupViewModifier 수정하였습니다.
- 로그아웃 시 KakaoLogin에서 로그아웃, KeyChain, UserDefault에 저장된 유저 정보 삭제됩니다.
- 회원탈퇴 시 KakaoLogin에서 로그아웃, KeyChain, UserDefault에 저장된 유저 정보 삭제, DeleteUser 서버 통신으로 유저 정보 삭제됩니다.

## 📢 Notes
 - 로그아웃, 회원탈퇴 완료 시 임시 뷰(NextView)로 이동 -> Coordinator로 로그인 뷰로 옮겨야합니다.

2024-07-07 23:56 UTC, GREENOVER requested changes
수고하셨씁니다~~
코멘트들 한번 최종 확인 부탁드려요ㅎㅎ
비슷한 결의 코멘트는 하나로만 남겼으니 같이 점검 부탁드립니다!

2024-07-07 23:56 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/Popup/PopupView.swift
> +    .contentShape(.rect)
붙이신 이유가 궁금합니다 🙋🏻

2024-07-07 23:56 UTC, GREENOVER commented on Projects/App/Sources/RootView.swift
> +        MyPageView(
테스트용이라면 수정되어야 할 듯 합니다~

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Core/Services/UserDefaults/UserDefaultsClient.swift
> +  public enum Key: String {
key도 String을 채택하고 있는데 굳이 type을 또 만들어 사용한 이유가 있나요?
불필요한 중복 구현인것같아 한 방향으로 가면 어떨까 합니다~

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +  fileprivate struct LoginViewNameSpace {
네임스페이스 구현시 struct보다 enum을 대게 사용하는데, 왜 enum을 더 많이 사용할까요?

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    public var isUnregisterPresented: Bool
unregister이라는 단어는 없을거라, 회원탈퇴면 withdraw와 같은 워딩을 많이 사용합니다.

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    public var alarmStatus: String
해당 타입이 on / off 두가지밖에 없다면 enum으로 타입을 별도로 만들어도 되지 않나요?

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +          if deleteUserInfo == nil {
if문 부터 타야하지 않을까요?

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +public struct MyPageCoreError: GabbangzipError {
에러 로그 처리와는 별개로 에러 상황 시 사용자에게 별도 UI/UX적으로 조치는 기획에 없는거죠~?

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    Group {
꼭 필요한건가요? 없으면 어떻게 되나요~?

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +          Button(action: {
action 파라미터도 개행하면 어떨까요?

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +extension MyPageView {
굳이 extension하지 않아도 private 구조체이기에 어차피 다른쪽에서 접근할 수 없어 보입니다.

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    var horizontalPadding: CGFloat
프로퍼티들도 private해야 합니다.
그렇지 않다면 해당 MyPageView에서 private으로 객체가 생성되었어도 해당 프로퍼티들을 접근할 수 있어요.

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    init(text: String,
fileprivate

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    var body: some View {
fileprivate

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    init(text: String,
+ text 파라미터 괄호 개행

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    init(height: CGFloat, padding: CGFloat) {
위와 마찬가지로 접근제어자 점검이 필요합니다~

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +  private struct MyPageNameSpace {
위 코멘트와 동일하게 네임스페이스에 struct를 사용할때의 효율이 있을까요?

2024-07-07 23:56 UTC, GREENOVER commented on Projects/App/Sources/RootCore.swift
>    public var body: some Reducer<State, Action> {
리듀서에서 노란색 warning나는 부분 한번 실행하셔서 체크해주세요~

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Core/Services/UIApplication/UIApplicationClient.swift
> +  public var openURL: @Sendable () async throws -> Void
내부 로직을 보니 아무 URL이나 오픈하는게 아닌 특정하게 설정 URL을 오픈하는거라 네이밍도 openSetting과 같은 뉘앙스로 변경되는게 맞을것 같아요 🙋🏻

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Core/Services/UIApplication/UIApplicationClient.swift
> +            UIApplication.shared.open(url)
```suggestion
            UIApplication.shared.open(url) { success in
              if success {
               continuation.resume(returning: ())
              } else {
                continuation.resume(throwing: UIApplicationClientError(code: .failToGetUrl))
              }
            }
```

open 시, completionHandler 인자가 존재할텐데 그렇다면 open에 대해 성공, 실패가 존재한다는 의미일것 같아요.
성공 실패에 대해서도 처리해놓는게 어떨까요?

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Core/Services/UNUserNotificationCenter/UNUserNotificationCenterClient.swift
> +          UNUserNotificationCenter.current().requestAuthorization { status, error in
매번 해당 푸시 알림 권한에 대해 체크하는것이면 getNotificationSettings로 권한을 확인하고 처리하는게 맞지 않을까 생각합니다 🙋🏻
물론, request로 해도 동작을 안하는건 아니지만 목적이 조금 달라보여서요.

2024-07-07 23:56 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/Popup/PopupView.swift
> +    .onTapGesture(perform: action)
LGTM 👍

2024-07-07 23:56 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/Popup/PopupViewModifier.swift
> +      content
놓친 부분까지 잘 넣어주셨네요 👍👍👍

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    public var isNextPage: Bool
조금 더 명확하게 위의 네이밍처럼 moveNextPage나 isNextPagePresented와 같은건 어떤가요?

2024-07-07 23:56 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    case showNext
현재 마이페이지에서 next로 갈곳이 로그아웃 / 회원탈퇴로 인해 로그인 뷰로 가는것이니 조금 더 명확한 네이밍과 로직 처리는 어떨까요.

2024-07-08 00:38 UTC, serena0720 commented on Projects/DesignSystem/Sources/Views/Popup/PopupView.swift
> +    .contentShape(.rect)
container에 onTapGesture를 붙여 동작을 추가할 때 Spacer 영역이 터치가 안되는 경우를 방지하고자 터치 영역을 다시 한번 잡았습니다!

2024-07-08 00:41 UTC, serena0720 commented on Projects/App/Sources/RootView.swift
> +        MyPageView(
이전과 동일하게 Text뷰로 돌려놓겠습니다!

2024-07-08 00:41 UTC, serena0720 commented on Projects/Core/Services/UserDefaults/UserDefaultsClient.swift
> +  public enum Key: String {
KeyChain 내부에도 key 로 관리하여 생성하였는데, 불필요한 중복이라고 느낄 수 있을 거 같습니다! 이전과 동일하게 String으로 변경하겠습니다!

2024-07-08 00:51 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +  fileprivate struct LoginViewNameSpace {
아 제가 enum으로 한다는 것을 놓쳤습니다🥹 enum을 사용하면 뜻하지 않은 초기화를 막을 수 있어 더 많이 사용하는 것으로 알고 있습니다🧐

2024-07-08 00:58 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    public var isUnregisterPresented: Bool
조언 감사합니당~!

2024-07-08 01:04 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/Popup/PopupView.swift
> +    .contentShape(.rect)
굿~~ 그럼 그냥 버튼으로 리팩토링 하는게 어떨까요?
왜냐면 현재처럼 뷰에 onTapGesture를 붙이면 동작은 되지만, 버튼처럼 눌릴때 희미해지거나 하는 등 효과는 없을것 같아서요.

2024-07-08 01:07 UTC, GREENOVER commented on Projects/Core/Services/UserDefaults/UserDefaultsClient.swift
> +  public enum Key: String {
아하 Key 타입을 만들지 말라는게 아니라, enum key에 String을 채택하셨잖아요?
근데 아래에서 type도 String 연산 프로퍼티로 만들어주셔서 그 부분이 중복이라고 말씀드린겁니다ㅎㅎ
type 연산 프로퍼티로 이용할거면 enum key에 String을 채택하지 않아도되고, type 연산 프로퍼티를 사용하지 않는다면
key case에 rawValue나 그 자체로 활용할 수도 있어서요.

2024-07-08 01:12 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +public struct MyPageCoreError: GabbangzipError {
네 일단 현재 디자인 상태에서는 별도의 에러 처리가 없는 상태입니다🥲

2024-07-08 01:13 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +extension MyPageView {
아 그냥 가독성을 위해 별도로 분리한것입니다! 합칠까요?

2024-07-08 01:17 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    var horizontalPadding: CGFloat
와 이부분은 생각 못했습니다👀 조언 감사합니다~!

2024-07-08 01:20 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    init(text: String,
와.. 꼼꼼한 리뷰 감사합니다👍

2024-07-08 01:22 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    var body: some View {
body도 fileprivate을 사용할 수 있군요.. 단순히 private이 안되기 때문에 접근제어자를 쓰기 어려울 거라고만 생각했어요🥹 또 배워갑니다!

2024-07-08 01:23 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +  private struct MyPageNameSpace {
위 코멘트와 함께 수정하였습니다!

2024-07-08 01:25 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    case showNext
아하 넵! 추후 작업을 위해 showLoginView로 네이밍 수정 및 LoginView를 넣어놓도록 하겠습니다!

2024-07-08 01:34 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    public var isNextPage: Bool
다음화면이 LoginView라는 것또한 명시하기 위해 isLoginViewPresented로 수정하였습니당~!

2024-07-08 01:39 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +          Button(action: {
넹~!

2024-07-08 01:42 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    Group {
아 필요없는 Group입니다!🥹

2024-07-08 01:51 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +          if deleteUserInfo == nil {
해당 로직은 저희 서버에 있는 User를 삭제 시 User의 코드 번호를 반환받으면 Error없이 서버에서 삭제가 완료된 것이기 때문에 KakaoAPIClient.delete를 통해 값이 없다면 Error를 로그하겠금 처리한 것입니다!

제 추측으론 에러가 2개여서 혼돈이 생긴것일 수도 있겠다 싶어 정리드립니당💪
failToGetDeleteUserInfo에러는 서버로부터 유저 삭제를 실패한 경우,
failToDeleteUser에러는 서버와의 통신에서 실패한 경우로 보시면 될 거 같습니다!

2024-07-08 02:16 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +          if deleteUserInfo == nil {
아 그러네요!
세레나가 맞습니다 👍

2024-07-08 02:17 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +extension MyPageView {
편하신대로 하셔도 되는데, 해당 하위 뷰들이 굳이 MyPageView에 종속되어 있을 필요는 없어보여서요!
MyPageView를 나중에 만들더라고 하위 뷰를 사용안할 일은 없겠지만?
확장 시 하위 뷰들의 메모리도 모두 들고 있는 형태라서 말씀드립니다.

2024-07-08 05:34 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +          if deleteUserInfo == nil {
👀감사합니다 그린🌳

2024-07-08 12:38 UTC, hope1053 requested changes
수고하셨습니다 👍 코멘트 확인 부탁드려요~!

2024-07-08 12:38 UTC, hope1053 commented on Projects/App/Sources/RootView.swift
> +import MyPage
여기서 MyPage 모듈이 필요한가요?

2024-07-08 12:38 UTC, hope1053 commented on Projects/Core/Services/UNUserNotificationCenter/UNUserNotificationCenterClient.swift
> +  public var isPushOn: @MainActor @Sendable () async throws -> Bool
P5: isPushEnabled가 조금 더 직관적인 것 같아요! 아주 사소한 의견입니다^_^

2024-07-08 12:38 UTC, hope1053 commented on Projects/Core/Services/UNUserNotificationCenter/UNUserNotificationCenterClient.swift
> +          UNUserNotificationCenter.current().requestAuthorization { status, error in
찬우님 말대로 현재 상태를 확인하고 거기에 따라서 처리를 하는게 더 맞는 것 같습니다~!

2024-07-08 12:38 UTC, hope1053 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +
👍

2024-07-08 12:38 UTC, hope1053 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +import KakaoLogin
P4: 그냥 갑자기 든 생각 & 뒷북이라 넘어가셔도 되긴하다만 LoginScene 자체 이름이 지금 KakaoLoginScene으로 돼있는데 Kakao를 떼는건 어떻게 생각하시나요? 이렇게 import KakaoLogin으로 봤을 때 KakaoSDK랑 조금 헷갈리기도 하고 (아마 일어나지 않을 일일 것 같지만) 카카오 로그인 외에 다른 로그인이 붙을 수도 있어서 그런 생각이 들었습니다

2024-07-08 12:38 UTC, hope1053 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +import KakaoLogin
P1: 그리고 MyPage 모듈이 KakaoLogin 모듈에 대한 dependency 추가가 필요한 것 같은데 확인 부탁드려요! 지금 빌드가 안되고 있어욥

2024-07-08 12:38 UTC, hope1053 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    public var alarmStatus: String
공감합니당

2024-07-08 12:38 UTC, hope1053 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +          await send(.showLoginView)
P4: 동일한 내용 case .logout에서 반복되는 것 같은데 꼭 한 번 더 실행해줘야하는건가요? 만약 아니더라도 해당 부분 함수로 분리해도 좋을 것 같아요~!

2024-07-08 12:38 UTC, hope1053 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +      case .getAccessToken:
P2: 키체인에서 accessToken을 읽어오는 것 뿐만 아니라 deleteUser action까지 호출하고 있는데 getAccessToken이라는 액션 이름이 조금 안 어울리는 것 같아요. deleteUser action까지 포함할 수 있는 네이밍으로 변경해주시면 좋을 것 같습니다 👍

2024-07-08 12:38 UTC, hope1053 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    static let currentVersion = "1.0.0"
P1: 이거 버전을 string으로 갖고 있을게 아니라 번들에 접근해서 현재 앱 정보를 가져오는게 좋을 것 같아요~! 그렇게 안하면 앱 업데이트 진행할 때마다 문자열을 변경해줘야하는데 번거로울 수도 있을 것 같습니다 🫡

2024-07-08 15:42 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    static let currentVersion = "1.0.0"
저희 현재 MVP에서는 1.0.0 텍스트로 통일하기로 했었습니다🥹

2024-07-08 15:44 UTC, serena0720 commented on Projects/App/Sources/RootView.swift
> +import MyPage
아 MyPageView를 삭제하면서 함께 삭제되었어야하는데 놓쳤습니당! 꼼꼼한 리뷰 감사합니다🥰

2024-07-08 15:52 UTC, serena0720 commented on Projects/Core/Services/UNUserNotificationCenter/UNUserNotificationCenterClient.swift
> +  public var isPushOn: @MainActor @Sendable () async throws -> Bool
오오 좋은 의견 감사합니다~!

2024-07-08 15:54 UTC, serena0720 commented on Projects/Core/Services/UserDefaults/UserDefaultsClient.swift
> +  public enum Key: String {
아 이해했습니당..😇 해당 부분 수정했습니다!💪

2024-07-08 16:15 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +import KakaoLogin
> P4: 그냥 갑자기 든 생각 & 뒷북이라 넘어가셔도 되긴하다만 LoginScene 자체 이름이 지금 KakaoLoginScene으로 돼있는데 Kakao를 떼는건 어떻게 생각하시나요? 이렇게 import KakaoLogin으로 봤을 때 KakaoSDK랑 조금 헷갈리기도 하고 (아마 일어나지 않을 일일 것 같지만) 카카오 로그인 외에 다른 로그인이 붙을 수도 있어서 그런 생각이 들었습니다

좋은 의견인 거 같습니다! 다른 분들도 동의하시면 LoginScene > Login > LoginCore, LoginView로 수정하겠습니다! @GREENOVER @ChuuMong 

> P1: 그리고 MyPage 모듈이 KakaoLogin 모듈에 대한 dependency 추가가 필요한 것 같은데 확인 부탁드려요! 지금 빌드가 안되고 있어욥

MyPage에서 넘어가는 화면을 TextView에서 LoginView로 수정하면서 생긴 문제인거 같네요! 꼼꼼한 리뷰 감사합니다👍

2024-07-08 16:26 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +      case .getAccessToken:
getAccessTokenToDelete로 수정하였습니다~!

2024-07-08 16:33 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +          await send(.showLoginView)
와 이런 실수를....!!! `await send(.logout)`이 아닌 `try await kakaoLoginClient.logout()`을 호출하는 것이 로직 상 맞습니다😇
하여 로직 순서상 별도의 함수로 분리하기엔 함수 호출 순서가 달라 어려운 부분이 있습니다🥹

2024-07-08 21:48 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    static let currentVersion = "1.0.0"
초기 배포가 1.0.0이여도 그것도차 어차피 번들에서 가져다 사용하면 되지 않나요?
MVP 이후에 업데이트 시 여길 더 수정할 필요도 없어보이구여..!

2024-07-08 23:51 UTC, hope1053 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +import KakaoLogin
@serena0720 다음에는 PR 올리시기 전에 빌드 되는지 먼저 확인 한 번 해주시면 더 좋을 것 같슴당 🫡

2024-07-09 00:11 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +import KakaoLogin
PR 수정 시 좀더 꼼꼼하게 보겠습니당~!💪

2024-07-09 00:55 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +    static let currentVersion = "1.0.0"
BundleClient에 getCurrentVersion 세팅 및 MyPageCore에 currentVersion을 만들어 MyPageView를 생성할때 외부에서 주입한 후 뷰를 띄울 수 있도록 하였습니다💪
@hope1053 @GREENOVER 좋은 의견 감사합니다🥰

2024-07-09 01:06 UTC, zekexros requested changes

2024-07-09 01:06 UTC, zekexros commented on Projects/App/Sources/RootCore.swift
> +          )
P2:
한 줄로 작성하는 것이 가독성에 더 유리하다고 생각하는데 어떤가요?

2024-07-09 01:06 UTC, zekexros commented on Projects/App/Sources/RootCore.swift
> +        logger.error("RootCore Error: \(String(describing: error))")
P1:
Side Effect에 해당하므로 `Effect(run을 말하는 것임)`를 활용하도록 수정해주세요

2024-07-09 01:06 UTC, zekexros commented on Projects/App/Sources/RootCore.swift
>        case .login(.delegate(.checkLogin(let isLogin))):
P3:
enum의 associate value를 사용할 때 let을 보통 case의 바로 뒤에 두었는데 여긴 다르게 사용하셨네요! 기존에 사용하던 방법을 계속해서 사용하면 어떨까 합니다

2024-07-09 01:06 UTC, zekexros commented on Projects/Core/Services/UIApplication/UIApplicationClient.swift
> +          if let url = URL(string: UIApplication.openSettingsURLString) {
P2:
설정앱으로 가는 URL만 특정하여 사용하는 것보단 urlString을 입력받아 제네릭하게 사용하는 것은 어떨까요?

2024-07-09 01:06 UTC, zekexros commented on Projects/Core/Services/UNUserNotificationCenter/UNUserNotificationCenterClient.swift
> +          UNUserNotificationCenter.current().requestAuthorization { status, error in
P2:
메서드의 이름을 작성한다고 생각하면 requestAuthorization가 엔드포인트 이름으로 더 적합하다고 생각하는데 어떤가요?
마찬가지로 사용자의 푸시 알림 상태를 읽어오는 엔드포인트의 이름은 getNotificationSettings가 되겠군여

2024-07-09 01:06 UTC, zekexros commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +          }
P1:
사용자 정보를 UserDefaults에 저장하는 행위를 하지 않았는데 .saveUserInUserDefaults 액션에 이미 success를 입력하는 플로우가 부자연스럽습니다. Result문을 사용하지 않는 것이 어떨까요?

2024-07-09 01:06 UTC, zekexros commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
>          logger.error("Fail to save Token in KeyChain \(error)")
P1:
Effect로 빼주세요

2024-07-09 01:06 UTC, zekexros commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +        logger.error("Fail to save User in UserDefaults \(error)")
P1:
Effect로 빼주세요

2024-07-09 01:06 UTC, zekexros commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +      Text(LoginViewNameSpace.loginTitle)
P5
`우리가 픽! 하는 우리끼리 네컷앨범`이라는 문구가 다른 곳에서도 사용되나요? 네임스페이스의 효용 가치가 낮아 오버 엔지니어링 아닌가? 라는 개인적인 의견입니다

2024-07-09 01:06 UTC, zekexros commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +          }
P2:
run내부에서 do-catch문을 활용하는 것보다는 run의 catch handler를 사용하시거나 Result문 활용하면 어떨까요?

2024-07-09 01:06 UTC, zekexros commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +        }
P2:
run내부에서 do-catch문을 활용하는 것보다는 run의 catch handler를 사용하시거나 Result문 활용하면 어떨까요?

2024-07-09 01:06 UTC, zekexros commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +        return .none
P1:
Effect로 빼주세요

2024-07-09 02:32 UTC, serena0720 commented on Projects/Core/Services/UIApplication/UIApplicationClient.swift
> +            UIApplication.shared.open(url)
와 놓쳤던 부분입니다..! Bool값을 반환하여 실패 시 ToastView를 띄우도록 하겠습니다!

2024-07-09 17:03 UTC, klmyoungyun commented
<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/48887389/e41e9349-0206-4179-a784-7a3c7e1c2324" width=400/>

2024-07-09 17:07 UTC, AhnSangHee commented
> <img alt="" width="400/" src="https://private-user-images.githubusercontent.com/48887389/347050131-e41e9349-0206-4179-a784-7a3c7e1c2324.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NDQ5MDksIm5iZiI6MTcyMDU0NDYwOSwicGF0aCI6Ii80ODg4NzM4OS8zNDcwNTAxMzEtZTQxZTkzNDktMDIwNi00MTc5LWE3ODQtN2EzYzdlMWMyMzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDE3MDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NzI4ZjNkZjhkN2IwZDY5N2JhNDM1NGExODgzNWMxMTI3ZWE2YmY5YmM2OGU5NmM4MTNmYTMxMWJiODRmNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SlLJBYskFT2eeZRpE4zMIpeoWLnvi5h_G8P4tf0-tgM">
들렸다가요~♡
<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/95578975/4e4146df-06e2-4812-bbe2-440b1f5d0471" width="400"/>

2024-07-09 22:55 UTC, GREENOVER commented
작업 모두 마무리 후 리뷰 재요청 주시기전에 컨플릭도 처리 부탁드립니다 🙏🏻

2024-07-10 03:40 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +public struct MyPageCoreError: GabbangzipError {
@GREENOVER @hope1053 @zekexros 
안드팀이랑 논의한 결과
- 설정으로 움직일때 에러 토스트뷰
- 회원탈퇴 시 에러 토스트뷰
이렇게 2가지만 하기로 했습니다~

2024-07-10 03:48 UTC, 210-reverof commented
Look Green To Me!
[1718181761738.gif](https://github.com/mash-up-kr/gabbangzip-iOS/assets/74983448/29252c58-957a-48ec-b718-cb364a580bee)

2024-07-10 03:49 UTC, 210-reverof commented
![1718181761738.gif](https://github.com/mash-up-kr/gabbangzip-iOS/assets/74983448/e29765b9-d40b-4cf2-9771-8e91a142c14c)

Look Green To Me

2024-07-10 04:25 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginView.swift
> +      Text(LoginViewNameSpace.loginTitle)
오버 엔지니어링 고민도 했으나, 뷰에 사용되는 텍스트들을 통일되게 한 곳에서 관리하는 것이 휴먼 에러를 줄일 수 있지 않을까 생각했습니다😊

2024-07-10 04:31 UTC, serena0720 commented on Projects/App/Sources/RootCore.swift
>    public var body: some Reducer<State, Action> {
아 확인했습니다~! 감사합니다🙇‍♀️

2024-07-10 04:41 UTC, serena0720 commented on Projects/App/Sources/RootCore.swift
> +          )
@zekexros 
해당 줄만 말씀하시는 걸까요? 아니면 유사한 케이스 모두 말하는 걸까요?

수정한다면 아래와 같은 컨벤션을 말씀하시는걸까요?
```swift
await send(.getUser(Result { try await kakaoLoginClient.checkUserInformation() }))
```

2024-07-10 04:42 UTC, serena0720 commented on Projects/App/Sources/RootCore.swift
> +        logger.error("RootCore Error: \(String(describing: error))")
와 놓쳤던 부분입니다👍 비슷한 케이스 모두 수정하겠습니다!

2024-07-10 04:45 UTC, serena0720 commented on Projects/App/Sources/RootCore.swift
>        case .login(.delegate(.checkLogin(let isLogin))):
통일되게 수정하겠습니다~!

2024-07-10 06:10 UTC, serena0720 commented on Projects/Core/Services/UIApplication/UIApplicationClient.swift
> +          if let url = URL(string: UIApplication.openSettingsURLString) {
넵~!

2024-07-10 06:33 UTC, zekexros commented on Projects/App/Sources/RootCore.swift
> +          )
> 해당 줄만 말씀하시는 걸까요? 아니면 유사한 케이스 모두 말하는 걸까요?

YES!😊

> 수정한다면 아래와 같은 컨벤션을 말씀하시는걸까요?

YES!🤠

2024-07-10 06:36 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +          }
일관되게 수정한다고 했는데 놓친게 있었네요😇 꼼꼼한 리뷰 감사합니다~!

2024-07-10 06:39 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
>          logger.error("Fail to save Token in KeyChain \(error)")
다른 Reducer와 동일하게 logError case를 생성하여 사용하도록 수정하였습니다~!

2024-07-10 06:42 UTC, zekexros commented
템플릿에 적혀있던 📸 Screenshot 을 지우고 첨부를 안 한 이유가 궁금합니다

</br>

스크린샷은 리뷰어가 한눈에 쉽게 이해하고, 직접 코드를 실행해보지 않아도 변경 사항을 쉽게 파악할 수 있다는 측면에서 리뷰 시간이 단축될 수 있습니다. 가급적이면 화면 구현이 포함된 작업에서는 📸 Screenshot에 미디어 파일을 첨부해 주세요🤩

</br>
이와 관련하여 다양한 의견이 있다면 언제든지  말씀해 주세요

2024-07-10 06:55 UTC, serena0720 commented on Projects/Features/Scene/KakaoLoginScene/KakaoLogin/LoginCore.swift
> +          }
`User`를 가져오고 이를 `LoginResponse`에 넣고, `LoginResponse`내부에서 `Nickname`을 찾는 순서이기 때문에 `User`가 없을 시 `nickname`을 가져오는 것 또한 불가능하기때문에 `Result`타입을 사용한 것입니다.
`User`의 `Nickname`을 가져올 수 있으면 `saveUserInUserDefaults`를 통해 `UserDefaults`에 저장하는 시도를 하고 이의 결과를 `Result`타입으로 반환하여 `UserDefaults에 저장이 success`가 되는 최종 경로에 도달하는 플로우이기 때문에 각 과정의 success, failure 구분이 필요하다 생각합니다!

제가 추측하기에 현재 실패 시 `saveUserInUserDefaults`에 `failure`값을 넘기는 거때문에 플로우가 어색하다고 느낄 수 있다 생각하여, `failure`발생 시 `logError`로 넘기는 방식으로 수정하면 어떨까 싶은데 의견 부탁드립니다!💪 @zekexros 

```swift
  if let nickname = user?.nickname {
    await send(.saveUserInUserDefaults(.success((.nickname, nickname))))
  } else {
    await send(.logError(LoginCoreError(code: .failToGetUser)))
  }
```

2024-07-10 07:18 UTC, serena0720 commented on Projects/App/Sources/RootCore.swift
> +          )
왜 마음이 변하셨나요🥹
![img](https://github.com/mash-up-kr/gabbangzip-iOS/assets/101619749/a089f903-0e05-45ae-9468-7fb3727d8a13)

2024-07-10 08:13 UTC, serena0720 commented on Projects/Core/Services/UNUserNotificationCenter/UNUserNotificationCenterClient.swift
> +          UNUserNotificationCenter.current().requestAuthorization { status, error in
감사합니다 여러분~~~

2024-07-11 04:25 UTC, GREENOVER requested changes
리베이스 혹은 병합하시는 과정에서 기존 develop의 변경사항이 무시되고 롤백된것 같네요.
GabbangzipAPIClientDelegate에 구현되있는것들도 그렇고..?
리뷰 재요청을 주실때는 항상 현재 최신 develop 기준을 병합하거나 컨플릭 나는게 없는지 확인하고, 동작도 정상적인지 빠뜨린거 없는지 최종 확인하시고 요청주셔야 서로 공수를 줄일 수 있습니다 🥲
현재로써는 PR 협업이 오히려 서로 힘든 방식으로 진행되는것 같아 이 부분 유념해주시면 좋을것 같아요 😃
고로.. 다시

2024-07-12 01:07 UTC, GREENOVER requested changes
간단히 몇가지 코멘트들과 함께 드려봅니다~
어프로브하고 다음번 개선하거나 선택적 개선하여도 되지만, 챌린지를 원하셔서 리퀘스트 체인지로 드려봅니다!
언제든 조정 가능하니 편하게 해보세요 😃

2024-07-12 01:07 UTC, GREENOVER commented on Projects/App/Sources/RootCore.swift
> +    public var nickname: String = ""
어디선 init으로 초기값 주는곳도 있고 지금처럼 사용되는곳도 있어서, 한방향으로 통일되면 어떨까 합니다 🙋🏻

2024-07-12 01:07 UTC, GREENOVER commented on Projects/App/Sources/RootCore.swift
> +    case logError(RootCoreError)
요건 왜 뷰 액션으로 볼 수 있는건가요?
View와 상호작용하는일이 전혀 없어보여서요.

2024-07-12 01:07 UTC, GREENOVER commented on Projects/Core/Services/UNUserNotificationCenter/UNUserNotificationCenterClient.swift
> +  public var requestAuthorization: @MainActor @Sendable () async throws -> Bool
get이 더 적절하지 않나요?

2024-07-12 01:07 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    public enum Status: String {
명확하게 AlarmStatus로 하면 더 나을것 같습니다😃

2024-07-12 01:07 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    case checkPushOn
이것도 내부 액션이라 볼 수 있지 않을까요?

2024-07-12 01:07 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +      )
하나로 합쳐도 되지 않을까요?
즉, Core에서 토스트를 띄워주는 변수 하나면 충분하고 토스트 메시지 또한 state로 관리하여 넣어주면 일원화하여 관리될 수 있을것 같아요.

2024-07-12 01:07 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +          SettingTextView(text: MyPageNameSpace.version)
보통 이런 상황의 뷰에선 TextView라는 이름보다 TitleView라는 네이밍을 많이 가져가긴 합니다~!
Text는 너무 포괄적이라서요.

2024-07-12 01:07 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +      )
popup도 뷰 모디파이어는 하나만 사용하고, 
충분히 팝업으로 나타날 title부터 action들을 Core에서 내부 타입으로 만들거나하여 사용할 수 있을것 같아요.
현재는 팝업을 나타내야하는 조건이 100개가 된다면 100번 다 구현해야되니, 조금 더 일원화 되는 방향으로 고민해보면 좋을것 같습니다!

2024-07-12 01:07 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +// MARK: - CustomView
MARK 주석으로 해당 SettingTextView가 어떤것인지 명확하게 기재하면 어떨까요?
커스텀뷰라는건 정보가 되지 않아보입니다.

2024-07-12 01:33 UTC, zekexros requested changes
MyPageView.swift에서 `import KakaoLogin`에 `No such module 'KakaoLogin'`라는 컴파일 에러가 발생합니다. 확인해주세요

2024-07-12 01:33 UTC, zekexros commented on Projects/Core/Services/UNUserNotificationCenter/UNUserNotificationCenterClient.swift
> +  }
P1:
UserNotification framework와 관련된 객체 `UserNotificationClient`를 이미 사용중인데 `UNUserNotificationCenterClient `를 한 번 더 만드신 것 같아요. 하나로 사용하는 것이 어떨까요?

2024-07-12 01:33 UTC, zekexros commented on Projects/Features/Scene/LoginScene/Login/LoginCore.swift
> +    case logError(LoginCoreError)
P1:
View로 부터 받는 action이 아닙니다

2024-07-12 01:33 UTC, zekexros commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    case deleteUserInfo
P1:
View Action은 View로 부터 받는 액션이고
Internal Action은 Reducer 내에서 전달받는 액션입니다
이에 맞춰 전체적으로 정리가 필요합니다

2024-07-12 02:17 UTC, serena0720 commented on Projects/App/Sources/RootCore.swift
> +    public var nickname: String = ""
init 으로 통일하겠습니당~!

2024-07-12 02:19 UTC, serena0720 commented on Projects/App/Sources/RootCore.swift
> +    case logError(RootCoreError)
준혁님이 조언주신 방향으로 전체적으로 수정하겠습니다~!
> View Action은 View로 부터 받는 액션이고
Internal Action은 Reducer 내에서 전달받는 액션입니다

2024-07-12 02:38 UTC, serena0720 commented on Projects/Core/Services/UNUserNotificationCenter/UNUserNotificationCenterClient.swift
> +  public var requestAuthorization: @MainActor @Sendable () async throws -> Bool
UserNotificationClient 중복으로 인해 전체적으로 코드 수정하겠습니다~!

2024-07-12 02:45 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    public enum Status: String {
오오 감사합니당~!

2024-07-12 02:47 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +          SettingTextView(text: MyPageNameSpace.version)
오 조언 감사합니다~!😊

2024-07-12 02:54 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +// MARK: - CustomView
SettingTitleView와 SeparatorView을 모두 포함하는 개념으로 커스텀뷰라고 mark한건데 오히려 혼란이 생기나 봅니다🧐
MARK를 SettingTitleView와 SeparatorView 각각 다는쪽으로 수정하면 괜찮을까욤?

2024-07-12 02:54 UTC, serena0720 commented on Projects/Core/Services/UNUserNotificationCenter/UNUserNotificationCenterClient.swift
> +  }
아하 세상에 괜히 생성했네요😅
기존에 구현되어있는 Client로 합치겠습니다~!

2024-07-12 03:17 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    case checkPushOn
checkPushOn을 Internal Action쪽으로 빼도록 하겠습니다~!

2024-07-12 03:22 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    case deleteUserInfo
MyPageCore에는 ViewAction으로 적합한 케이스가 없는 듯하여 Internal Action으로 모두 수정하였습니다!

2024-07-12 04:13 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +// MARK: - CustomView
네네 좋습니다!
단순 컴포넌트 이름으로 다는것보다 어떤 컴포넌트인지 예를들어, 설정 항목 타이틀 뷰 같은걸로 명확히 달면 더 좋을것 같아요~!
(정말 예시)

2024-07-12 04:42 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +      )
와 조언 감사합니다~! MyPageError로 에러 메세지를 MyPageCore에서 관리하게 했습니다!

2024-07-12 04:46 UTC, GREENOVER commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +      )
@serena0720 
옵셔널 타입으로 가져가는게 더 적절해보입니다 🙋🏻
외부에서 설정해줄 필요가 없어서 기본 초기값으로 이니셜라이저에서 nil로 가져가는게 어떨까요?

2024-07-12 04:54 UTC, zekexros commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    case deleteUserInfo
`showLogout`, `showWithdraw`, `checkPushOn`, `withdraw`, `openSetting`는 어디서 보내나요?

2024-07-12 05:36 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +// MARK: - CustomView
마이페이지 내부 타이틀 뷰같은... 네이밍을 생각했는데 감사합니다😂

2024-07-12 05:39 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    case deleteUserInfo
아...!! 이해했습니다!! 감사합니다ㅜㅜ

2024-07-12 05:46 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +      )
오오 네!! 꼼꼼한 리뷰 감사합니다~!

2024-07-12 06:19 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
> +      )
넵~ 수정했습니다!

2024-07-12 06:22 UTC, serena0720 commented on Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
> +    case deleteUserInfo
뷰에서 send하는 case를 View Action으로 옮겼습니다!

2024-07-12 07:20 UTC, GREENOVER approved these changes
수고하셨습니다 👍
성장세가 무섭습니다 👍👍👍

2024-07-12 08:00 UTC, zekexros approved these changes
![5263012](https://github.com/user-attachments/assets/292ce9a1-2d07-4fb4-a46f-7b60953dbd8b)

2024-07-12 08:43 UTC, hope1053 approved these changes

2024-07-12 08:45 UTC, merged