[Feat] 그룹 만들기 구현(1)
mash-up-kr/gabbangzip-iOS pull request #86
Opened 2024-07-09 15:01 UTC by zekexros

## 📌 Related Issue
- #42 

## 🚀 Description
- 양이 많아 그룹 만들기 기능을 나눠서 구현
  - 그 중 첫 번째 작업

## ✅ Done
- [x] 그룹만들기 구현
- [x] 그룹 이름 정하기 구현
- [x] 그룹 키워드 선택 구현
- [x] 그룹 사진 선택 구현
- [x] 로티 에셋 추가
- [x] 디자인 시스템 기능 일부 수정 및 리팩토링
- [x] 템플릿 수정(Action주석 추가)

## 📸 Screenshot
- 그룹 만들기 시작
  <img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/2b1cf8d8-4043-4bc4-9008-6539a2f8c893" width="200" height="450">
- 그룹 이름 정하기
  <img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/bc3a3eac-8b74-4309-b609-27b511fa0be6" width="200" height="450">
- 그룹 키워드 정하기
  <img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/798b49c6-1802-4151-955d-f2e85ccde454" width="200" height="450">
- 그룹 사진 정하기
  <img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/bbbeb9c7-98fc-4442-b782-2de1cc0df358" width="200" height="450"><img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/68fc0e73-2a33-454d-a62e-2106375df3fe" width="200" height="450">

## 📢 Notes
- `API연동` 및 `그룹 만들기 완료`, `코디네이터 연동 작업`은 다음 PR에 포함하겠습니다
- TCACoordinator 추가를 고려하여 `moveTo~`, `backTo~` 액션을 추가했습니다
 
## 🧪 Testing(optional)

2024-07-09 22:54 UTC, GREENOVER requested changes
수고하셨습니다~
몇가지 의견들 코드 코멘트로 남겨놔서 의견 부탁드려요 😃

2024-07-09 22:54 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/Button/GabbangzipButton.swift
> +  private var type: ButtonType
Binding으로 초기 넣어둔것은 해당 버튼이 활성화 버튼 / 비활성화 버튼 / 또 하나 뭐 있던것 같은데.. 컴플리션 액션에 의해 해당 버튼 자체의 타입이 변할 수 있어서 두었는데 현재 기획에서 필요 없나요?

2024-07-09 22:54 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/Button/KeywordButton.swift
> +        if !isSelected {
선택된 상태에서 다시 미선택으로 하는것도 기획에서 없나요?

2024-07-09 22:54 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/Lottie/LottieView.swift
>    case confetti
요거 이제 지우셔도 될듯!? 임시용이였어서

2024-07-09 22:54 UTC, GREENOVER commented on Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordCore.swift
> +    case hobbyKeywordButtonTapped(Bool)
너무 동일한 액션들인데 하나로 합치는건 어떤가요?
해당 버튼들마다 다른 동작을 할 일은 없어보여서요.
```swift
case keywordButtonTapped(keyword, isSelected)

case let .keywordButtonTapped(keyword, isSelected):
  return .send(.updateKeywordSelection(keyword, isSelected)
```

2024-07-09 22:54 UTC, GREENOVER commented on Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordCore.swift
> +        state.hobbyKeywordButtonSelected = (keyword == .hobby) && isSelected
여기도 좀 더 심플하게 갈 수 있을것 같아보입니다.
```swift
case let .updateKeywordSelection(keyword, isSelected):
  switch keyword {
  case .school:
    state.schoolKeywordButtonSelected = isSelected
  ...
  }
```

2024-07-09 22:54 UTC, GREENOVER commented on Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordView.swift
> +          )
ForEach로 돌리면 안되나요?
```swift
ForEach(GroupData.keyword.allCases, id: \.self) { keyword in
  KeywordButton(
    type: keyword,
    isSelected: Binding(
     get: {
        switch keyword {
        case .school:
          return store.schoolKeywordButtonSelected
        ...
        }
    },
    set: { isSelected in
      store.sesnd(.keywordButtonTapped(~)
    }
  )
  }
)
```
대충 이런식으로?

2024-07-09 22:54 UTC, GREENOVER commented on Projects/Features/Scene/CreateGroupScene/SetGroupName/SetGroupNameCore.swift
> +
두칸 줄바꿈이 되어있네유!

2024-07-09 22:54 UTC, GREENOVER commented on Projects/Features/Scene/CreateGroupScene/Views/PICProgressView.swift
> +fileprivate struct ProgressBarSizePreferenceKey: PreferenceKey {
이거 Core > Common > Views > ViewHeightKey에 동일하게 구현되어 있는데, 매번 뷰에서 구현할 필요없이 가져다 써도 괜찮을것 같아요~~

2024-07-11 05:23 UTC, zekexros commented on Projects/DesignSystem/Sources/Views/Button/GabbangzipButton.swift
> +  private var type: ButtonType
이번 작업에 GabbangzipButton 안에서 type이 바뀌는 동작은 하지 않는 것으로 보여 binding타입을 제거하였는데 찬우님 코멘트를 보고 재차 커밋 이력을 찾아 다시 확인해보니, GabbangzipButton 안에서 type이 바뀌지 않아 binding타입을 제거해도 무방해 보이는 것으로 재차 확인했습니다.

혹시 제가 여전히 놓친 부분이 있다면 알려주세용🤠

2024-07-11 05:30 UTC, zekexros commented on Projects/DesignSystem/Sources/Views/Button/KeywordButton.swift
> +        if !isSelected {
키워드 버튼이 사용되는 곳은 오직 한 곳(그룹 만들기 내 키워드 선택 화면)뿐인데요, 미선택이 가능한지 아닌지에 대해선 기획적으로 정해진 바가 없으나 미선택으로 하는 것이 더 익숙한 사용자 경험이라는 제 주관에 비롯되어 로직을 수정하였습니다

이 방안은 다음 회의에서 어젠다로 지정하여 의견을 제시한 후 기획을 확정하겠습니다

2024-07-11 05:41 UTC, zekexros commented on Projects/DesignSystem/Sources/Views/Lottie/LottieView.swift
>    case confetti
기존에 작성된 confetti가 임시용이어서 지웠었는데, 디자인 문서를 확인해보니 저희가 사용하는 로티 중에 confetti 파일이 있더라고요🫨

2024-07-11 07:05 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/Button/GabbangzipButton.swift
> +  private var type: ButtonType
네네 DS가 나올때 명확히 어떤 상태인지 몰라 일단 다 넣어둔것으로, 현재 기획에서 사용되지 않고 필요없다면 빼면 됩니다~ 👍

2024-07-11 07:06 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/Lottie/LottieView.swift
>    case confetti
ㅇㅎㅇㅎ 해당 confetti로 들어가있는 로티 파일이 초기 임시로 둔 파일이 아닌 현재 가빵집에 맞게 교체되있는 파일로 되어있나요?

2024-07-11 07:51 UTC, zekexros commented on Projects/DesignSystem/Sources/Views/Lottie/LottieView.swift
>    case confetti
네 맞습니당😊

2024-07-11 08:06 UTC, zekexros commented on Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordCore.swift
> +    case hobbyKeywordButtonTapped(Bool)
오옹 너무 좋은 아이디어라 실제로 가능한 방법인지 확인하기 위해 한번 시도해봤는데,


오직 Bool타입을 연관값으로 가지는 action만 CaseKeyPath로 사용할 수 있네요 `case keywordButtonTapped(keyword, isSelected)`와 같은 형태를 파라미터로 사용할 시,


`Cannot convert value of type 'KeyPath<Case<SelectKeywordCore.Action>, Case<(GroupData.Keyword, Bool)>>' to expected argument type 'KeyPath<Case<SelectKeywordCore.Action>, Case<Bool>>'`


라는 컴파일 에러가 발생합니다🫨

2024-07-11 08:19 UTC, GREENOVER commented on Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordCore.swift
> +    case hobbyKeywordButtonTapped(Bool)
아니면 별도 메서드로 분리하는건 어떤가요?
다른 방법으로 우회해서 사용하는것이 더 적절해보일것도 같아서요ㅠ
해당 로직 자체는 유지보수 측면에서 아예 배제되었다고 봐서 좀 더 다른 방향이 필요해보이긴합니다 🤔

2024-07-11 08:27 UTC, GREENOVER commented on Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordCore.swift
> +    case hobbyKeywordButtonTapped(Bool)
음 제가 간단히 해보니까 컴파일은 되는것 같아서 공유드려봐요 🙋🏻
```swift
case keywordButtonTapped(GroupData.Keyword, Bool)

case let .keywordButtonTapped(keyword, isSelected):
        return .send(.updateKeywordSelection(keyword: keyword, isSelected: isSelected))
```

```swift
KeywordButton(
    type: .school,
    isSelected: Binding(
      get: { store.schoolKeywordButtonSelected },
      set: { isSelected in
        store.send(.keywordButtonTapped(.school, isSelected))
      }
    )
  )
```

2024-07-11 09:12 UTC, zekexros commented on Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordCore.swift
> +    case hobbyKeywordButtonTapped(Bool)
[TCA문서](https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/bindings)에서 나와있는 `Ad hoc bindings`이나 `Binding actions and reducers`방법 외에도 이러한 방법을 사용할 수 있군요!
새로 알아갑니다 굿!!👍

2024-07-11 09:14 UTC, zekexros commented on Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordCore.swift
> +        state.hobbyKeywordButtonSelected = (keyword == .hobby) && isSelected
입력된 키워드 외에는 모두 선택을 해제해야 하므로 `(keyword == .school) && isSelected`와 같은 로직들은 살려야 합니다🙋‍♂️

2024-07-11 09:46 UTC, zekexros commented on Projects/Features/Scene/CreateGroupScene/Views/PICProgressView.swift
> +fileprivate struct ProgressBarSizePreferenceKey: PreferenceKey {
하나의 PreferenceKey를 여러 곳에서 사용하면, 여러 뷰에서 해당 키에 대한 값을 reduce하는 과정에서 예상치 못한 값이 사용되는 곳이 생길 거라 생각되어 PreferenceKey는 필요한 곳에서 새로 타입을 생성하여 사용하면 어떨까 생각합니다🤔

잘못 알고 있는 부분이 있으면 지적해 주세요🙇‍♂️

2024-07-11 10:16 UTC, GREENOVER commented on Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordCore.swift
> +        state.hobbyKeywordButtonSelected = (keyword == .hobby) && isSelected
아하 오 그렇군요!
기획을 몰라서 죄송함다 ㅎㅎ..

2024-07-11 10:17 UTC, zekexros commented on Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordView.swift
> +          )
가능합니다! 말씀하신 대로 리팩토링을 진행하면 키워드의 수가 증가할수록 절감되는 코드의 양이 더 많아지겠네요
좋습니다👍

2024-07-11 10:18 UTC, GREENOVER commented on Projects/Features/Scene/CreateGroupScene/Views/PICProgressView.swift
> +fileprivate struct ProgressBarSizePreferenceKey: PreferenceKey {
ㅇㅎ 어차피 뷰는 독립되어 있고 한 화면에서 두번 쓸 경우는 없다고 생각되어서 뷰 전환이 되면 메모리 해제가 되서 사이드이펙트가 없다고 느껴지긴했는데 테스트는 안해봤습니다ㅋㅋ
지금처럼 우선 가시죠~!

2024-07-11 10:52 UTC, zekexros commented on Projects/Features/Scene/CreateGroupScene/Views/PICProgressView.swift
> +fileprivate struct ProgressBarSizePreferenceKey: PreferenceKey {
![kqqu27lrlg4le3fwky9armxy6hse](https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/81eecf12-02da-4b1a-8a07-d0a2e53b74fe)

2024-07-11 22:42 UTC, GREENOVER approved these changes
수고하셨습니다~~!

2024-07-12 11:49 UTC, merged