[Design] 투표 완료 페이지, 이미지 뷰어 UI 구현
mash-up-kr/gabbangzip-iOS pull request #87
Opened 2024-07-14 07:39 UTC by hope1053

## 📌 Related Issue
- #82 
## 🚀 Description
투표 완료 페이지, 이미지 뷰어 UI를 구현합니다.
## ✅ Done
- [x] 투표 완료 페이지
- [x] 이미지 뷰어

## 📸 Screenshot
<img width="336" alt="image" src="https://github.com/user-attachments/assets/726ec0d4-e75f-448e-9769-85ad1b54671c">
<img width="369" alt="image" src="https://github.com/user-attachments/assets/86bc8bfa-d65a-4e49-ae09-b487d7dc5443">

## 📢 Notes
네컷 이미지들은 API 붙이면서 추가하겠습니다~
 
## 🧪 Testing(optional)

2024-07-14 12:15 UTC, GREENOVER approved these changes
LGTM

2024-07-14 15:53 UTC, zekexros requested changes
수고하셨습니다

2024-07-14 15:53 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/EventDetail/EventDetailView.swift
> +        .ignoresSafeArea()
P4:
```suggestion
      DesignSystem.Colors.gray100
        .ignoresSafeArea()
```
Background color을 Suggestion처럼 직접 사용하지 않고 변수로 선언하여 사용하신 이유가 궁금합니다

2024-07-14 15:53 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/EventDetail/EventDetailView.swift
> +struct EventDetailView: View {
```suggestion
public struct EventDetailView: View {
```
이후 만들어질 코디네이터 모듈에서 접근할 수 있도록 접근제어자를 public으로 수정해야 합니다

2024-07-14 15:53 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteView.swift
> +struct VoteCompleteView: View {
```suggestion
public struct VoteCompleteView: View {
```
이후 만들어질 코디네이터 모듈에서 접근할 수 있도록 접근제어자를 public으로 수정해야 합니다

2024-07-14 15:53 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteView.swift
> +      .padding(.horizontal, 21)
P3:
피그마에서는 버튼 아래에 패딩이 적용되어 있으나 코드에서는 반영되지 않았습니다. 확인 부탁드려요

2024-07-14 15:53 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteView.swift
> +    VStack {
P2:
```suggestion
    VStack(spacing: 0) {
```
Spacing을 0으로 설정하지 않은 것은 의도된 것일까요?

2024-07-14 15:53 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteView.swift
> +      Spacer()
P4:
한 줄 띄어써도 좋을 것 같습니다
```suggestion
      Spacer()
      
      Spacer()
```

2024-07-14 15:53 UTC, zekexros commented on Workspace.swift
>      ),
P2:
`.scheme(`  들여쓰기가 맞지 않는 것 같아요

2024-07-16 04:05 UTC, hope1053 commented on Workspace.swift
>      ),
@zekexros 
![image](https://github.com/user-attachments/assets/a924bdf5-73a1-451f-a805-29c561439fe4)
tuist edit으로 진입해서 보면 괜찮은 것 같은데...왜 이럴까요...? 🥲

2024-07-16 04:06 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteView.swift
> +    VStack {
@zekexros 앗 아뇨 깜빡한 것 같습니다! 반영할게요!

2024-07-16 04:13 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteComplete/VoteCompleteView.swift
> +      .padding(.horizontal, 21)
@zekexros 수정 반영했습니다! [77f6c0e](https://github.com/mash-up-kr/gabbangzip-iOS/pull/87/commits/77f6c0e21cc2f99b13fc23f334cc3e824ebee659)

2024-07-16 04:16 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/EventDetail/EventDetailView.swift
> +        .ignoresSafeArea()
@zekexros background라는 변수로 선언해서 어떤 역할을 하는지 조금 더 명확하게 보여주고 싶었습니다! suggestion 주신 것 처럼 작성해도 괜찮을 것 같네욥

2024-07-16 06:39 UTC, zekexros requested changes
코드 수정 후 빌드가 잘 되나요?

2024-07-18 13:20 UTC, zekexros approved these changes

2024-07-21 23:36 UTC, merged