[Design] 투표하기 Swipe UI 구현
mash-up-kr/gabbangzip-iOS pull request #90
Opened 2024-07-23 07:03 UTC by hope1053

## 📌 Related Issue
- #53 

## 🚀 Description
투표 화면 UI 구현했습니다!

## ✅ Done
- [x] 양 옆으로 스와이프해서 투표를 할 수 있습니다.
- [x] 하단 버튼 클릭을 통해 투표를 할 수 있습니다.  

## 📸 Screenshot
https://github.com/user-attachments/assets/1472319a-3f6b-47d0-b0eb-c96aef7cdcb7

## 📢 Notes
 
## 🧪 Testing(optional)

2024-07-23 08:50 UTC, GREENOVER commented
작업을 develop에서 안따고 이전 PR올린 브랜치에서 따서 하신건가...
해결방법은 체리픽해서 필요한것만 가져가는 방법이 있을것 같아요~
뭐 상관은 없어서 걍 ㄱㄱ

2024-07-23 12:37 UTC, zekexros requested changes
전반적으로 잘 구현된 것 같아요👍 리뷰하면서 궁금한 점과 의견이 각각 1개씩 생겼습니다
- 카드를 swipe했을 때 버튼의 상태가 바뀌지 않는데 바뀌어야 하지 않나요?
- 카드를 스와이프하여 임계값을 넘지 않았을 경우 애니메이션과 함께 화면 중앙으로 되돌아오는데, 임계값을 넘었을 땐(투표할 때) 애니메이션 없이 자리에서 즉시 없어집니다. 시간되시면 투표할 때에도 애니메이션이 적용되면 어떨까요?

빌드가 안 됩니다. 에러가 발생하는 부분을 확인하여 수정 부탁드립니다

2024-07-23 12:37 UTC, zekexros commented on Projects/Core/Common/Views/DraggableViewModifier.swift
> +  private let threshold: CGFloat = 100.0
P5
```suggestion
  @Binding private var isActive: (Bool, SwipeDirection)
  @State private var translation: CGSize = .zero
  private let threshold: CGFloat = 100.0
  
  public init(isActive: Binding<(Bool, SwipeDirection)>) {
    self._isActive = isActive
  }
```

2024-07-23 12:37 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteCore.swift
> +          }
P2:
등록된 Dependency를 사용하지 않고 구체 타입을 직접 호출하는 것은 테스트를 어렵게 만듭니다
@Dependency(\.mainQueue) var mainQueue를 이용하여 원하는 동작을 똑같이 구현할 수 있습니다

2024-07-23 12:37 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteButton/VoteButton.swift
> +  @Binding var state: VoteButtonState
P2:
Binding 타입일 필요가 없어 보입니다

2024-07-23 12:37 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteSwipeView/VoteSwipeView.swift
> +  @Binding var imageURLs: [URL?]
P2:
Binding 타입일 필요가 없어 보입니다

2024-07-23 12:37 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteSwipeView/VoteSwipeView.swift
> +  @Binding var swipeDirection: SwipeDirection
P2:
Binding 타입일 필요가 없어 보입니다

2024-07-23 12:37 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteSwipeView/VoteSwipeView.swift
> +            .animation(.easeInOut(duration: 0.3), value: angle)
P2:
지워도 동작은 똑같네요. 필요하지 않을 것 같습니다!

2024-07-23 12:37 UTC, zekexros commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteCore.swift
> +    public var passsButtonState: VoteButtonState
P1:
```suggestion
    public var passButtonState: VoteButtonState
```

2024-07-23 12:59 UTC, serena0720 reviewed
고생하셨습니다~!👍

2024-07-23 12:59 UTC, serena0720 commented on Projects/Core/Common/Views/DraggableViewModifier.swift
> +  @State private var translation: CGSize = .zero
`@State`를 붙인 이유가 있을까요?

2024-07-23 22:37 UTC, GREENOVER requested changes
![스크린샷 2024-07-24 오전 7 37 10](https://github.com/user-attachments/assets/cc6bcf0d-5a90-4091-a64d-4ab209dfdb57)
이상은 없지만, 최종 체크와 더 나은 방향 고민을 위해 몇가지 코멘트 남깁니도~

2024-07-23 22:37 UTC, GREENOVER commented on Projects/DesignSystem/Resources/Icons.xcassets/Vote/bad.imageset/Contents.json
> +      "filename" : "Group 5236.svg",
filename도 왠만하면 에셋내 이름하고 맞추시는게 좋을것 같아요~

2024-07-23 22:37 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteCore.swift
> +        state.voteButtonState = .deactivate
액션들에서 반복되는것 같은데 공통적인 액션 하나 두는것도 괜찮아 보입니다 🤔

2024-07-23 22:37 UTC, GREENOVER commented on Projects/Core/Common/Views/DraggableViewModifier.swift
> +  private let threshold: CGFloat = 100.0
p4 초기값들도 왠만하면 이니셜라이저에서 하면 좋을것 같네요~

2024-07-23 22:37 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteButton/VoteButton.swift
> +        ZStack {
p3 ZStack을 안쓰고도 background를 이용해 충분히 가능할것 같아보입니다.
불필요한곳에서 ZStack을 지양하는게 어떨까요?
뷰 계층이 두개 만들어져서 좋을건 없을것 같아요.

2024-07-23 22:37 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteCore.swift
> +    public var pickedImageIndex: [Int]
p5 네이밍이 단수형으로 보입니다.

2024-07-23 22:37 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteSwipeView/VoteSwipeView.swift
> +      ForEach(0..<imageURLs.count, id: \.self) { index in
view에서 count를 계산하는것보다 core에서 연산 프로퍼티로 count를 가지고 있는게 성능상 이점을 가져갑니다 🙋🏻
뷰에서는 왠만하면 계산 로직을 태우지 않는것이 좋아요.

2024-07-23 22:37 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteSwipeView/VoteSwipeView.swift
> +struct CardView: View {
여기서만 사용된다면 private해도 되지 않을까요?

2024-07-23 22:37 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteSwipeView/VoteSwipeView.swift
> +          .frame(width: 330, height: 440)
해당 수치는 디바이스별로도 고정인가요?
디자인에서 원하는게 양쪽 패딩이 고정이고 사진 사이즈가 다른걸 원하는지 아님
지금처럼 이미지의 사이즈가 고정인지 궁금해요~
사진 사이즈 고정이라면, 디바이스마다 어색할 수 있는 부분이 우려됩니다.

2024-07-23 22:37 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteView.swift
> +            .font(.head18)
font color는 필요없나요?
왠만하면 명시적으로 가져가는게 좋습니다.
추후, 앱내 기본 컬러나 상위에서의 컬러 자체가 변경되면 리팩토링이 수정이 불가피해요ㅠ

2024-07-23 22:37 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteView.swift
> +            .foregroundStyle(.clear)
ZStack말고 다른 방법은 없나요~?

2024-07-23 22:37 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteView.swift
> +  public var body: some View {
해당 body안에 뷰들을 해당 파일에서 struct로 적절히 나눠보는건 어떤가요?

2024-07-23 22:37 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteView.swift
> +    )
p5. 그냥 의견
나중에 팝업이 여러개가되면 해당 뷰 모디파이어를 재사용하기 힘들어보이는데,
여러 팝업을 띄울 수 있도록 추후 core에서 popup title부터 들어가는 데이터들을 관리해서 띄워주어도 좋을것 같네요ㅎㅎ

2024-07-23 22:37 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/VoteComplete/VoteCompleteView.swift
> +      Spacer()
두개를 넣은 이유가 어떤건가요~?

2024-07-25 23:49 UTC, hope1053 commented
> * 카드를 swipe했을 때 버튼의 상태가 바뀌지 않는데 바뀌어야 하지 않나요?
해당 부분에 대해 디스크립션이 없어서 문의 후 반영하도록 하겠습니다!

> * 카드를 스와이프하여 임계값을 넘지 않았을 경우 애니메이션과 함께 화면 중앙으로 되돌아오는데, 임계값을 넘었을 땐(투표할 때) 애니메이션 없이 자리에서 즉시 없어집니다. 시간되시면 투표할 때에도 애니메이션이 적용되면 어떨까요?
넵 반영해보겠습니다!! 🫡

2024-07-26 00:03 UTC, hope1053 commented on Projects/Core/Common/Views/DraggableViewModifier.swift
> +  private let threshold: CGFloat = 100.0
초기값 이니셜라이저에서 주입하는 것까지 반영했습니다! [9e6c7f8](https://github.com/mash-up-kr/gabbangzip-iOS/pull/90/commits/9e6c7f86523b16f8904d782b5236bb3980f82a8c)

2024-07-26 00:05 UTC, hope1053 commented on Projects/Core/Common/Views/DraggableViewModifier.swift
> +  @State private var translation: CGSize = .zero
그래야 DragGesture로 인해 translation이 변했을 때 content에 offset 및 rotation이 적용되지 않을까요 ?!

2024-07-26 00:08 UTC, GREENOVER commented
+ 추가로, Drag 제스쳐를 직접 사용하실때 혹시 모르니 iOS 18 베타로도 테스트 해보시길 바랍니다.
현재 Xcode 16 / iOS 18이 정식 릴리즈가 아닌 베타이긴하지만, SwiftUI의 DragGesture를 기존처럼 사용할때 이슈가 있을수 있더라구요.
추후 릴리즈 버전이 출시되면 괜찮을수도 있는데, 아닐수도 있으니 대응은 해야되긴하기에 테스트는 해보셔야합니다.
앱 출시시점 직후에 바로 iOS 18이 릴리즈될거라 대응이 필요합니다.

2024-07-26 00:28 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteButton/VoteButton.swift
> +        ZStack {
ZStack을 지양해야된다는 부분에 대해 인지하고 있지 못했네요! 짚어주셔서 감사합니다 🙇‍♀️

2024-07-26 00:28 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteButton/VoteButton.swift
> +  @Binding var state: VoteButtonState
Binding 개념을 제가 착각해서 사용했네요!! 수정했습니다 👍

2024-07-26 00:30 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteCore.swift
> +    public var passsButtonState: VoteButtonState
헉 이런 오타가 ,,

2024-07-26 00:33 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteCore.swift
> +    public var pickedImageIndex: [Int]
그르네요.. 근데 이 부분 API 붙이면서 index가 아닌 관련 id값을 가지게 수정될 것 같아서 TODO 작성해두고 추후 수정하겠습니다!

2024-07-26 01:08 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteSwipeView/VoteSwipeView.swift
> +      ForEach(0..<imageURLs.count, id: \.self) { index in
오 그런 부분까지 뺄 생각을 못했네요! 감사합니다 👍

2024-07-26 01:13 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteSwipeView/VoteSwipeView.swift
> +struct CardView: View {
맞습니다^_^

2024-07-26 01:14 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteSwipeView/VoteSwipeView.swift
> +          .frame(width: 330, height: 440)
이 부분 확인 후 반영하겠습니다!

2024-07-26 01:25 UTC, hope1053 commented
> * 추가로, Drag 제스쳐를 직접 사용하실때 혹시 모르니 iOS 18 베타로도 테스트 해보시길 바랍니다.
>   현재 Xcode 16 / iOS 18이 정식 릴리즈가 아닌 베타이긴하지만, SwiftUI의 DragGesture를 기존처럼 사용할때 이슈가 있을수 있더라구요.
>   추후 릴리즈 버전이 출시되면 괜찮을수도 있는데, 아닐수도 있으니 대응은 해야되긴하기에 테스트는 해보셔야합니다.
>   앱 출시시점 직후에 바로 iOS 18이 릴리즈될거라 대응이 필요합니다.

넵 확인해보겠습니다 🫡

2024-07-26 01:27 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteView.swift
> +  public var body: some View {
최대한 분리해봤는데 더 분리하면 좋겠다 ~ 하는 부분 있으면 알려주세요 ! [80bf029](https://github.com/mash-up-kr/gabbangzip-iOS/pull/90/commits/80bf029483f8913a12a340caad85602d1ca17492)

2024-07-26 01:29 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteView.swift
> +    )
재사용성 생각하면 그게 좋을 것 같네요! 반영하겠습니다!

2024-07-26 01:48 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/VoteComplete/VoteCompleteView.swift
> +      Spacer()
참고 자료 첨부합니다 말도 안되는 방법이다 생각하시면 알려주세요...^_^
<img width="365" alt="KakaoTalk_Snapshot_20240726_104721" src="https://github.com/user-attachments/assets/95dfaede-6b13-4f6b-8236-21103fdf0653">

2024-07-26 01:52 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteView.swift
> +            .foregroundStyle(.clear)
VoteSwipeView는 ZStack을 이미 사용하고 있어서 그 구조를 활용하는게 더 나은 것 같아서 해당 View VoteSwipeView 내부로 이동시켜서 수정했습니다!

2024-07-26 01:53 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteView.swift
> +            .font(.head18)
적용해두겠습니다!

2024-07-26 02:01 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteCore.swift
> +        state.voteButtonState = .deactivate
[809bbab](https://github.com/mash-up-kr/gabbangzip-iOS/pull/90/commits/809bbab7ea2141c85c9e383b5922ec694b44260f) 이렇게 리팩토링 해봤는데 이런 방향 생각하신게 맞을까요~?!

2024-07-26 02:26 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteCore.swift
> +          }
제가 이 부분까지 고려를 못했네요 😅 수정했습니다!

2024-07-26 02:33 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/VoteComplete/VoteCompleteView.swift
> +      Spacer()
나중에 디바이스나 환경별로 틀어질수 있어요.
어쩌다 아다리 맞게 된거라 예측 불가능한 코드라고 보입니다.
Spacer를 height를 주지 않는한 예측할 수 없습니다.
말도 안되는건 아닌데, 올바른 접근 방법은 아니라고는 보입니다~ 
상대적 위치는 geometry도 가능하고 UISCreen으로 조정해서도 가능하고 뭐 다른식으로도 충분히 가능할것 같아보입니다.

2024-07-26 02:39 UTC, GREENOVER approved these changes
수고하셨습니다~
이따 봅시다 🙋🏻

2024-07-26 02:39 UTC, GREENOVER commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteView.swift
> +      VStack(spacing: 0) {
요게 왜 ZStack으로 쌓여야하는지 모르겠어요.
VStack, HStack으로 적절히 한 계층에서 다룰 수 있지 않나요?

2024-07-26 04:18 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/VoteComplete/VoteCompleteView.swift
> +      Spacer()
넵 그럼 이 부분도 수정해두겠습니다!

2024-07-26 04:26 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/Vote/VoteView.swift
> +      VStack(spacing: 0) {
x 버튼의 위치가 애매하다고 생각해서 ZStack으로 구현했는데 지금 다시 생각해보니 한 계층 안에서 충분히 구현가능할 것 같네요! 요 부분도 수정해보겠습니다 🫡

2024-07-26 04:51 UTC, zekexros approved these changes
![](https://raw.githubusercontent.com/onevcat/lgtm-images/master/images/DVvXogX.jpg)

2024-07-28 23:30 UTC, merged