[Feat] FCM 구현
mash-up-kr/gabbangzip-iOS pull request #96
Opened 2024-07-30 19:18 UTC by serena0720

## 📌 Related Issue
- #85 
## 🚀 Description
- FirebaseClient를 생성하였습니다.
- AppDelegate Core에 FirebaseClient 코드를 적용하였습니다.

## ✅ Done
- FirebaseClient 생성
- AppDelegateCore에 FirebaseClient 적용 및 refactoring

## 📸 Screenshot
<img src="https://github.com/user-attachments/assets/ceb08a8d-53d0-4b19-99f8-604c0b8962d9" height="450"/>
<img src="https://github.com/user-attachments/assets/29e7c703-7486-4fe1-aeae-544d7583740c" height="450"/>

> 왜인지 모르겠지만 한번에 우다다오네욤..

## 📢 Notes
- 기나긴 저의 FCM 여정을 묵묵히 기다려주시고, 도움을 주신 저희 팀원들,,, 사,, 사는동안 많이 버세요❤️
- 현재 KakaoSDK관련 에러가 존재하지만 동작에는 영향을 주고 있진 않습니다만 이 부분 의견 혹은 조언 부탁드립니다.
 > objc[38130]: Class _....KakaoSDK... is implemented in both /private/var/containers/Bundle/Application/.../Prod_Gabbangzip.app/Frameworks/Services.framework/Services and /private/var/containers/Bundle/Application/.../Prod_Gabbangzip.app/Frameworks/Login.framework/Login. One of the two will be used. Which one is undefined.

> 현재 추측으론 KakaoSDK와 Firebase가 동일 모듈에 있는 상태에서 Firebase는 정적으로 타입을 정의한 것이 영향을 준 것이 아닌가하는 생각도 해봤습니다🧐

-----
## 🔥 Trouble Shooting
### ✅ TCA의 구조에 맞추어 delegate를 Dependency 내부에서 설정
> [🔗 참고 자료: FCM 등록 토큰 액세스](https://firebase.google.com/docs/cloud-messaging/ios/client?hl=ko#access_the_registration_token)

Firebase의 등록 토큰을 수신하기 위해선 `AppDelegate`에서 `MessagingDelegate`를 채택하여 구현해야합니다.
하지만 `MessagingDelegate`는 `TCA` 구조에 맞추어 생각했을 때, `FirebaseClient` 즉 `Dependency` 내부에서 관리하는 것이 맞다고 판단하였습니다. 
하여 `AppDelegate`가 아닌 `Dependency`내부에서 대리자 설정을 하고자는 문제가 발생하였습니다.

[TCA의 UsernotificationClient 예시](https://github.com/pointfreeco/isowords/blob/f132bd03cf557d99e01fec118b4224b078e9f4e8/Sources/ComposableUserNotifications/Live.swift)를 보면 `Delegate` 객체를 생성하여 `AsyncStream`을 활용하면 `Dependency` 내부에서 대리자를 설정하는 방법을 참고할 수 있었습니다.
이를 참고하여 `MessagingDelegate` 객체를 `Dependency` 내부에서 생성하여 필요에 따라 호출되어 사용될 수 있도록 만들었습니다.

<details>
<summary>기존 MessagingDelegate 코드</summary>

```swift
class AppDelegate: UIResponder, UIApplicationDelegate, MessagingDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        Messaging.messaging().delegate = self

        return true
    }
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
        ...
    }
}
```
</details>

<details>
<summary>TCA Dependency내 MessagingDelegate 코드</summary>

 ```swift
@DependencyClient
public struct FirebaseClient: Sendable {
  public var delegate: @Sendable () -> AsyncStream<DelegateEvent> = { .finished }
  
  public enum DelegateEvent {
    case messaging(
      _ messaging: Messaging,
      fcmToken: String?
    )
  }
}

extension FirebaseClient: DependencyKey {
  public static var liveValue: FirebaseClient {
    return FirebaseClient(
      delegate: {
        AsyncStream { continuation in
          let delegate = MessageDelegate(continuation: continuation)
          Messaging.messaging().delegate = delegate
          continuation.onTermination = { _ in
            _ = delegate
          }
        }
      }
    )
  }

extension FirebaseClient {
  final class MessageDelegate: NSObject, MessagingDelegate, Sendable {
    let continuation: AsyncStream<DelegateEvent>.Continuation
    
    init(continuation: AsyncStream<DelegateEvent>.Continuation) {
      self.continuation = continuation
    }
    
    func messaging(
      _ messaging: Messaging,
      didReceiveRegistrationToken fcmToken: String?
    ) {
      continuation.yield(.messaging(messaging, fcmToken: fcmToken))
    }
  }
}
```
</details>

### ✅ Firebase Library 충돌 문제

FirebaseClient로 Firebase Library와 Dependency를 생성하니 아래와 같은 에러가 발생하였습니다.

> 에러: `'NSInvalidArgumentException', reason: '-[FIRInstallationsItem registeredInstallationWithJSONData:date:error:]:`

이는 정적 라이브러리와 Objective-C의 동적 특성 간의 충돌로 인해, 정적 라이브러리에 있는 카테고리 메서드가 앱에 링크되지 않기 때문에 에러가 발생한 케이스입니다.
해당 에러는 `registeredInstallationWithJSONData:date:error:`메서드가 호출 되었지만 해당 메서드가 `FIRInstallationsItem` 클래스 내부에 존재하지 않는 것을 뜻합니다.
Objective-C는 메서드를 호출하기 전까지 메서드의 구현 코드를 결정하지 않으며, 메서드에 대한 링커 심볼을 정의하지 않고 클래스에 대한 심볼만 정의합니다. 카테고리는 메서드들의 모음이므로 카테고리의 메서드는 심볼을 생성하지 않습니다. 따라서 클래스가 이미 정의된 경우, 링커는 카테고리에 정의된 메서드를 로드하지 않습니다.

-ObjC 링커 플래그는 링커가 정적 라이브러리에 있는 모든 Objective-C 클래스와 카테고리를 로드하도록 합니다. 하여 FirebaseClient에 의존하는 Service 모듈의 setting에 `"OTHER_LDFLAGS": "-ObjC"`를 추가하여 해결하였습니다.

> 🧐 재밌는건 FirebaseAnalytics는 정적 프레임워크로만 배포된다는 점입니다.
The 7.x update applies to all Firebase libraries except FirebaseAnalytics, which continues to be distributed as a binary static framework.
[이렇게](https://firebase.google.com/docs/reference/swift/modules?_gl=1*kus68r*_up*MQ..*_ga*MTQ0NTczMDU2MC4xNzIyMzYyNTM2*_ga_CW55HF8NVT*MTcyMjM2MjUzNi4xLjAuMTcyMjM2MzIwNy4wLjAuMA..) 제공되는 모듈이 많은데 말이죠..
자세한 이유는 [여기](https://github.com/firebase/firebase-ios-sdk/blob/main/docs/firebase_in_libraries.md)에서 보실 수 있습니다.

> 참고
> [🍎 Technical Q&A](https://developer.apple.com/library/archive/qa/qa1490/_index.html)
> [🔗 블로그 링크](https://syjdev.tistory.com/27)
> [🔗 블로그 링크](https://sy-catbutler.tistory.com/60)
> [🔗 Firebase git issues](https://github.com/firebase/firebase-ios-sdk/issues/4711)

### ✅ Push Notification을 Tuist에서 설정
Tuist를 사용하면 `Info.plist`와 `Build Setting`을 코드로 간단히 설정할 수 있습니다.
하지만 Tuist를 사용하여 Xcode 프로젝트에서` App > Capabilities > Push Notifications`를 활성화를 하기 위해선 별도의 `entitlements` 파일이 필요하였습니다.
이는 `Bundle Resources`의 `Entitlements`, `Information Property List`, `Privacy manifest files` 중 `Push Notifications`는 service 혹은 technology의 사용허가를 담당하는 `entitlements`에 해당되기 때문입니다.
`Apple Push Notification service (APNs)` 환경 사용 여부를 결정하는 `APS Environment` 키 값에 `development`와 `production` 권한 값을 각각 설정하였습니다.

> 참고
[🍎 APS Environment Entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/aps-environment)

2024-07-30 23:35 UTC, GREENOVER requested changes
고생하셨습니다~
적절히 잘 구현해주셔서 마이너한 코멘트들 남겼어요 😃

코멘트에는 남기지 않았지만, 현재 Lint 경고 뜨는곳들 있죠~?
(글자수 / 사용되지 않는 인자 등등..)
해당 작업하신 부분에서 나는 Lint 경고들은 왠만하면 각자 본인파트에서 나는것들은 작업하시면서 수정해주세요~ 
cc. @zekexros @hope1053

2024-07-30 23:35 UTC, GREENOVER commented on Projects/App/Dev-Gabbangzip.entitlements
> +<?xml version="1.0" encoding="UTF-8"?>
해당 파일들 Resources에 위치시키면 안되나요~?

2024-07-30 23:35 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateCore.swift
> +    case setUpKakaoSDK
setup
해당 워딩이 사용되는 모든곳 동일한 코멘트

2024-07-30 23:35 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateCore.swift
> +      case let .messagingFCMToken(.messaging(messaging, fcmToken: fcmToken)):
msessaging 인자는 쓰이지 않네요.
와일드카드로 하셔도 충분할것 같습니다.

2024-07-30 23:35 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateCore.swift
> +          // Note: This callback is fired at each app startup and whenever a new token is generated.
후속 작업이 더 남은건가요?

2024-07-30 23:35 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateCore.swift
> +          print("FCM registration token: \(String(describing: token))")
print지양하고 logger 써주세요~

2024-07-30 23:35 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateCore.swift
> +      case let .messagingFCMToken(.messaging(messaging, fcmToken: fcmToken)):
`case let .messagingFCMToken(.messaging(_, fcmToken)):`

2024-07-30 23:35 UTC, GREENOVER commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +import FirebaseMessaging
없어도 될듯합니다🤔

2024-07-30 23:35 UTC, GREENOVER commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +  public var getDeviceToken: @Sendable (Data) -> Void
해당 작업도 비동기 작업이라고 보이는데 async하지 않아도 되는건가요~?

2024-07-30 23:35 UTC, GREENOVER commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +            if let error = error {
FirebaseClientError에 기왕 error를 받아오셨는데 underlying 값으로 error를 넘겨주는게 더 좋을것 같아요ㅎㅎ

2024-07-30 23:35 UTC, GREENOVER commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +            }
```suggestion
            if let error = error {
              continuation.resume(throwing: FirebaseClientError(
                code: .failToGetMessaging,
                underlying: error)
              )
            } else if let token = token {
              continuation.resume(returning: token)
            } else {
              continuation.resume(throwing: FirebaseClientError(code: .unknownError))
            }
```

2024-07-30 23:35 UTC, GREENOVER commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +            }
예기치 못한 else 에러가 있을 수 있어요.

2024-07-30 23:35 UTC, GREENOVER commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +    case failToGetMessaging
```suggestion
    case failToGetMessaging
    case unknownError
```

2024-07-30 23:35 UTC, GREENOVER commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +
deinit 필요없나요?
ASyncStream이 continuation을 소유하고 있기에 해당 클래스 해제 시 continuation을 적절히 종료시키지 않아도 괜찮은가해서요.
메모리 누수의 위험은 없나요?

2024-07-30 23:35 UTC, GREENOVER commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +
```suggestion
    
    deinit {
      continuation.finish()
    }
```

2024-07-31 13:42 UTC, serena0720 commented on Projects/App/Dev-Gabbangzip.entitlements
> +<?xml version="1.0" encoding="UTF-8"?>
아 그렇네요..!! 수정하겠습니당

2024-07-31 13:44 UTC, serena0720 commented on Projects/App/Sources/AppDelegateCore.swift
> +          // Note: This callback is fired at each app startup and whenever a new token is generated.
다른 팀원들을 위해 공식 문서에 있는 코멘트를 그대로 사용하였습니다🥹
해당 내용 다른 분들 확인 하셨으면 지울까 싶습니다
@zekexros  @hope1053

2024-07-31 13:45 UTC, serena0720 commented on Projects/App/Sources/AppDelegateCore.swift
> +      case let .messagingFCMToken(.messaging(messaging, fcmToken: fcmToken)):
이 부분 수정해서 분명히 커밋한 거로 기억하는데 꿈속에서 했나봐요...😇 수정하겠습니당! 꼼꼼한 리뷰 감사해요!

2024-07-31 14:13 UTC, serena0720 commented on Projects/App/Sources/AppDelegateCore.swift
> +          print("FCM registration token: \(String(describing: token))")
아하 그런방법이..! 수정하겠습니다~!
logger의 debug함수를 사용한 logDescription 케이스를 추가하였습니다!

2024-07-31 15:04 UTC, serena0720 commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +import FirebaseMessaging
Messaging 타입이 FirebaseMessaging 내부에 구현된 타입이라 해당 타입에서 에러가 발생하게 됩니다🥹

2024-07-31 15:09 UTC, serena0720 commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +            if let error = error {
오오 그렇네요! 감사합니다!!

2024-07-31 15:12 UTC, serena0720 commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +  public var getDeviceToken: @Sendable (Data) -> Void
수정하겠습니다!!💪

2024-07-31 15:13 UTC, serena0720 commented on Projects/App/Sources/AppDelegateCore.swift
> +    case setUpKakaoSDK
아하 넵 네이밍 수정하겠습니당~!💪

2024-07-31 15:32 UTC, serena0720 commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +            }
suggestion 감사합니다! 아래 코멘트들과 함께 수정하겠습니다~!🙇‍♀️

2024-07-31 15:52 UTC, serena0720 commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +
저희 프로젝트에 기존에 구현되어 있는 usernotificationClient의 NotificationCenterDelegate는 deinit 하지 않아서 같은 맥락으로 firebaseClient의 messageDelegate도 deinit을 하지 않는 것인가 하는 막연한 생각으로 deinit을 구현하지 않았습니다.

만약 messageDelegate는 deinit이 필요하다면 NotificationCenterDelegate과의 차이점은 무엇이며,
deinit의 시점을 어떤 기준으로 봐야할지 의견이 궁금합니다🙇‍♀️

2024-07-31 17:10 UTC, serena0720 commented on Projects/App/Sources/AppDelegateCore.swift
> +          print("FCM registration token: \(String(describing: token))")
해당 로직이 연결된 Device의 token값을 알고자 함인데 print에서 log로 변경하니 콘솔창에 뜨지 않습니다🥹
아마 print와 달리 log는 속도가 느리다는 점, 멀티스레드 환경에서 처리한다는 점이 작용한것으로 보입니다
현 상황에서는 log보단 print를 사용하여 device token을 확인하는 것은 어떤지, 혹은 제가 놓친부분이나 잘못 생각하는 부분이 있는지 의견 궁금합니다🙌

2024-07-31 23:14 UTC, GREENOVER commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +
메모리 로그를 찍어 보아요~

2024-07-31 23:15 UTC, GREENOVER commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +import FirebaseMessaging
저도 그렇게 생각했는데, 왜 저는 없어도 에러가 안날까유?
캐싱을 지우고했는데도 말이죠.

2024-07-31 23:18 UTC, GREENOVER commented on Projects/App/Sources/AppDelegateCore.swift
> +          print("FCM registration token: \(String(describing: token))")
print를 사용하는건 프로덕트 관점에서 아무런 상관이 없습니다.
단순히, 개발시에 디버깅 목적일뿐 유의미한 목적을 가지지 않아요.
실제 상용 환경에서 해당 부분에서 유저들이 에러가 나서 진행이 안된다면 어떻게 확인해보실건가요?
유저가 저 token까지 받아온 후에 에러가 나는지 그렇다면 해당 token값은 무엇인지 알 수 있는 길이 있나요?
그렇기에 print는 개발자를 위한 용도일뿐이지, 저걸로 실제 상용에서까지 유저들의 로그 기록을 확인할 수 없다고 한다면 그냥 print나 log를 찍는 코드를 제거하는게 맞습니다.
습관적 디버깅 코드중에 하나입니다.

2024-07-31 23:21 UTC, GREENOVER commented on Projects/App/Dev-Gabbangzip.entitlements
> +<?xml version="1.0" encoding="UTF-8"?>
Resource에서 각 하위 폴더를 만들면 안되나요?
그 후 BuildPhases에서 Copy Bundle Resources의 코드를 수정해서 타겟에 맞는 entitlements 파일만 복사되도록 설정하면 되지 않을까해요~
즉, 해당 부분은 Build Phases에서 Run Script 단계를 추가해가지고 각 스킴 빌드에 맞는 entitlements를 받아와서 복사/생성하는것을 말했습니다.

2024-08-01 04:47 UTC, zekexros requested changes
수고하셨습니다~👍

2024-08-01 04:47 UTC, zekexros commented on Projects/App/Info.plist
> +	<false/>
P3:
FCM 문서에 따르면 '사용자에게 먼저 명시적인 수신 동의를 얻으려면 FCM을 사용 중지하여 구성 시 토큰이 생성되지 않게 하면 됩니다'라고 나와있는데 명시적인 수신 동의를 얻은 후 FCM을 다시 사용하는 로직은 보이지 않네요. 로직을 보완하거나 아니면 자동 초기화 방지 기능은 사용하지 않는 것은 어떨까요

2024-08-01 04:47 UTC, zekexros commented on Projects/App/Info.plist
> +	</array>
P4:
UIBackgroundModes에 대한 값이 fetch인 이유가 궁금합니다(해당 기능을 사용하지 않고 앞으로도 없을 예정으로 생각돼서요)

2024-08-01 04:47 UTC, zekexros commented on Projects/App/Sources/AppDelegateCore.swift
> +          await send(.runFirebaseAutoInitialization)
P2:
Firebase를 설정하는 과정이 의미 있고 순차적으로 진행되어야 한다면 send로 나열하는 것이 아니라 해당 메서드를 run 클로저 내에 직접 작성해야 합니다.

2024-08-01 04:47 UTC, zekexros commented on Projects/App/Sources/AppDelegateCore.swift
> +          }
P2:
에러 핸들링이 필요합니다

2024-08-01 04:47 UTC, zekexros commented on Projects/App/Sources/AppDelegateCore.swift
> +          await send(.registerForRemoteNotifications)
P3:
마찬가지로 순차적으로 진행되어야 한다면 send로 나열하는 것이 아니라 해당 메서드를 run 클로저 내에 직접 작성해야 합니다.

2024-08-01 04:47 UTC, zekexros commented on Projects/Core/Project.swift
> +		),
P3:
줄바꿈이 이상해요

2024-08-02 00:45 UTC, hope1053 approved these changes
진짜 너무 고생많으셨습니다....멋져요 👍

2024-08-02 03:17 UTC, serena0720 commented on Projects/Core/Project.swift
> +		),
한줄로 바꾸겠슴당...🥹

2024-08-02 03:19 UTC, serena0720 commented on Projects/App/Info.plist
> +	</array>
아하 추후에 사용할까 싶어 설정해놓은 것인데 삭제하겠습니다~!

2024-08-05 00:40 UTC, serena0720 commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +import FirebaseMessaging
현재 Firebase를 import하고 있기 때문에 FirebaseMessaging을 import 할 필요가 없다는 의견이 맞는 거 같습니다!
Firebase는 FirebaseCore를 의존하고 FirebaseCore가 Messaging을 포함한 주요 Firebase 라이브러리를 갖고 있기 때문입니다.
오히려 Firebase가 주요 라이브러리를 다 갖고 있기 때문에 tuist로 외부 의존성을 불러올 필요가 있을까 싶어서 해당 dependency를 삭제해봤는데, 이때문에 에러가 발생된 거 같습니다🥹 외부 의존성을 제거하면 Firebase Core와 Firebase Messaging을 포함할 수 없어서 에러가 발생되었다고 추측합니다

결론은 import FirebaseMessaging은 삭제하고, external dependency는 유지하는 쪽으로 수정하겠습니다!

2024-08-05 01:08 UTC, GREENOVER commented on Projects/Core/Services/Firebase/FirebaseClient.swift
> +import FirebaseMessaging
Nice 👍

2024-08-05 04:00 UTC, serena0720 commented on Projects/App/Dev-Gabbangzip.entitlements
> +<?xml version="1.0" encoding="UTF-8"?>
entitlements들 각 Product, Development 폴더 내부로 이동하였습니다!

2024-08-05 04:01 UTC, serena0720 commented on Projects/App/Info.plist
> +	</array>
삭제하겠습니다~

2024-08-05 04:02 UTC, serena0720 commented on Projects/App/Info.plist
> +	<false/>
삭제하겠습니다~!

2024-08-05 04:12 UTC, serena0720 commented on Projects/App/Sources/AppDelegateCore.swift
> +          await send(.runFirebaseAutoInitialization)
위와 같이 나눈 이유로 @MainActor에서 실행되는 것과 구분하고자 함이 있습니다.
모두 하나로 합치는것이 더 낫다고 판단하시는걸까요?

2024-08-05 04:14 UTC, serena0720 commented on Projects/App/Sources/AppDelegateCore.swift
> +          }
AppDelegate에서 에러발생 시 어떤 핸들링을 할 수 있나요..?

2024-08-05 12:07 UTC, zekexros commented on Projects/App/Sources/AppDelegateCore.swift
> +          )
이 코드의 목적은 무엇인가요?

2024-08-06 01:36 UTC, zekexros commented on Projects/App/Sources/AppDelegateCore.swift
> +          )
@serena0720

2024-08-06 01:37 UTC, zekexros approved these changes

2024-08-06 03:12 UTC, GREENOVER approved these changes

2024-08-06 13:20 UTC, serena0720 commented on Projects/App/Sources/AppDelegateCore.swift
> +          )
해당 부분 hotfix로 함께 수정하겠습니다!

2024-08-06 13:21 UTC, merged