[Feat] 그룹 만들기2
mash-up-kr/gabbangzip-iOS pull request #98
Opened 2024-08-01 15:56 UTC by zekexros

## 📌 Related Issue
-  #97 
## 🚀 Description
- #86 에 이어 그룹 만들기2 구현

## ✅ TODO
- [x] 파일 업로드 API 구현
- [x] UIPasteClient 구현
- [x] Presigned-url을 이용한 S3 이미지 업로드 기능 구현(multipart/form-data)
- [x] 그룹 만들기 화면들 중 사진 고르기 화면 마무리
- [x] 그룹 만들기 화면들 중 완료 화면 및 기능 구현
- [x] 그룹 만들기 코디네이터 구현

## 📸 Screenshot

https://github.com/user-attachments/assets/f574c0d7-826f-4c92-bf90-c2395feeb0d0

## 📢 Notes
 
## 🧪 Testing(optional)

2024-08-02 00:14 UTC, GREENOVER requested changes
수고하셨습니다~
몇가지 확인 차 코멘트 남깁니다 😃
추가로, 구현 영상을 보면 사진이 프레임에 적용될때 resize되면서 비율과 상관없이 적용되어 찌그러지는것 같은데요.
기획 의도인가요?
아니라면, resizeToFit이나 clipped등을 이용하여 잘라내거나 아니면 축소시켜서 비율은 유지되거나 하는 등이 필요해보여서요 🤔
사진이 짤리는건 상관없을것 같은데 찌그러져서 훼손되어 보여서 남겨봐요~
(물론 피그마나 기획 보진 않음ㅎ)

2024-08-02 00:14 UTC, GREENOVER commented on Projects/Core/Models/CreateGroup/Response/CreatedGroupInfo.swift
> +  public init(id: Int, groupName: String, keyword: GroupData.Keyword, groupImageURL: String, invitationCode: String) {
적절히 개행하는건 어떤가요?

2024-08-02 00:14 UTC, GREENOVER commented on Projects/Core/Services/PicAPIClients/FileUploadAPI/FileUploadAPI.swift
> +  case createGroup(accessToken: String, groupName: String, keyword: String, groupImageURL: String)
요건 createGroupAPI에 있는거 같은데, 여기서도 필요한 이유가 있는건가요??

2024-08-02 00:14 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/PhotoPicker/DataURL.swift
> +struct DataUrl: Transferable {
URL로 네이밍이 되어야할것 같습니다 🙋🏻

2024-08-02 00:14 UTC, GREENOVER commented on Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoView.swift
> +          }
```suggestion
        if !selectedPhotosInfo.isEmpty,
          let image = UIImage(data: selectedPhotosInfo[0].data) {
            Image(uiImage: image)
              .resizable(resizingMode: .stretch)
              .overlay(Color.black.opacity(0.3))
            }
```
이런 표현 어떠세요?
굳이 한번 더 if 블럭을 탈 필요는 없어 보여서요 🙋🏻

2024-08-02 00:55 UTC, hope1053 commented on Projects/Features/Scene/GroupDetailScene/MemberList/MemberListCore.swift
> +        }
감사합니다..🙇‍♀️

2024-08-02 01:49 UTC, hope1053 requested changes
수고하셨습니다!! 디자인 관련 코멘트 몇 개만 확인 부탁드려요~~👍

2024-08-02 01:49 UTC, hope1053 commented on Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoView.swift
> +          }
아니면 safe subscript 사용해도 좋을 것 같아요!

2024-08-02 01:49 UTC, hope1053 commented on Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoView.swift
이번 작업 내용은 아니지만 이제 발견해서 코멘트 드려요! 포토카드 내부 상단 태그 배경색 반영이 안된 것 같습니다~
<img width="736" alt="image" src="https://github.com/user-attachments/assets/efda73d2-9b71-4d33-8c48-d7d8daf5ad91">

2024-08-02 01:49 UTC, hope1053 commented on Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordCore.swift
그리고 여기도 키워드 표시되는 순서가 조금 달라서요~ 큰 상관은 없을 것 같은데 노티 드립니당
<img width="752" alt="image" src="https://github.com/user-attachments/assets/c812fe23-9d99-4c30-a461-fdf6c67107fa">

2024-08-02 01:49 UTC, hope1053 commented on Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
> +        .padding(.top, 8)
요기 링크 복사 버튼 색상도 반영돼야할 것 같습니다~ 
<img width="744" alt="image" src="https://github.com/user-attachments/assets/93e777df-f99e-426b-8ed5-67e0bd7c8ae9">

이미지는 에러떠서 안보이는 것 같네요..?
<img width="1478" alt="image" src="https://github.com/user-attachments/assets/a6324e0f-2034-4991-ac9d-014a23901c73">

2024-08-02 01:49 UTC, hope1053 commented on Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionCore.swift
> +        return .send(.backToHome)
생성하고 홈으로 돌아갔을 때 그룹 리스트 리프레시 돼야할 것 같습니다! 아직 생성된 그룹이 반영안되고 있는 것 같네요

2024-08-02 01:49 UTC, hope1053 commented on Projects/Features/Coordinator/CreateGroupCoordinator/CreateGroupCoordinatorCore.swift
지금 약간 플로우가 제가 이해한거랑 다른 것 같아서 확인차 코멘트 드려요!
로그인 → 현재 생성된 그룹이 없는 경우 홈이 아니라 바로 하단의 화면으로 이동해야하는 것으로 알고 있습니다
<img width="387" alt="image" src="https://github.com/user-attachments/assets/d8d172a3-0852-4145-9828-97ea62e63f5f">
홈에서 그룹 만들기로 이동했을 때는 바로 하단의 화면으로 이동하구요!
<img width="388" alt="image" src="https://github.com/user-attachments/assets/adf14bd3-4902-4528-bf8f-ebbc7542f47c">

현재는 로그인 → 그룹 존재여부와 상관없이 홈으로 이동, 그룹 만들기 버튼 클릭 시 로띠 있는 화면으로 이동하고 있어서 이부분 확인 부탁드립니다~

2024-08-02 01:49 UTC, hope1053 commented on Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
> +  }
이 부분 다른 화면에서도 사용될 것 같은데 따로 분리하는건 어떨까요?

2024-08-02 02:07 UTC, GREENOVER commented on Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoView.swift
> +          }
굿
```swift
if let firstPhotoInfo = selectedPhotosInfo[safe: 0],
   let image = UIImage(data: firstPhotoInfo.data) {
    Image(uiImage: image)
        .resizable(resizingMode: .stretch)
        .overlay(Color.black.opacity(0.3))
}
```
요렇게만 깔끔할듯하네요.
Collection의 safe subscript 플젝에 구현되있었는지 기억안나지만 없다면 확장해놔도 되겠네요 👍

2024-08-02 14:56 UTC, zekexros commented on Projects/Core/Models/CreateGroup/Response/CreatedGroupInfo.swift
> +  public init(id: Int, groupName: String, keyword: GroupData.Keyword, groupImageURL: String, invitationCode: String) {
오 좋습니다

2024-08-02 15:01 UTC, zekexros commented on Projects/Core/Services/PicAPIClients/FileUploadAPI/FileUploadAPI.swift
> +  case createGroup(accessToken: String, groupName: String, keyword: String, groupImageURL: String)
필요 없습니다. API 분리 과정에서 실수로 제거하지 않았슴다!

2024-08-02 15:02 UTC, zekexros commented on Projects/DesignSystem/Sources/Views/PhotoPicker/DataURL.swift
> +struct DataUrl: Transferable {
좋습니다

2024-08-02 15:06 UTC, zekexros commented on Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoView.swift
> +          }
safe subscript가 있었군요! TCACoordinator 내에 Collection을 확장하여 safe subscript가 구현되어 있네요ㅎㅎ 
의견 감사합니다

2024-08-02 15:12 UTC, zekexros commented on Projects/Features/Scene/CreateGroupScene/SelectGroupPhoto/SelectGroupPhotoView.swift
디자인 시스템에 정의된 컴포넌트들에 대한 전반적인 개편 작업이 있었으나 화면이 이에 맞춰 업데이트되지 않은 것으로 보입니다

2024-08-02 15:12 UTC, zekexros commented on Projects/Features/Scene/CreateGroupScene/SelectKeyword/SelectKeywordCore.swift
눈썰미가 좋으시네요👽

2024-08-02 15:14 UTC, zekexros commented on Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
> +        .padding(.top, 8)
- 요기 링크 복사 버튼 색상도 반영돼야할 것 같습니다~
  - 디자인 시스템에 정의된 컴포넌트들에 대한 전반적인 개편 작업이 있었으나 화면이 이에 맞춰 업데이트되지 않은 것으로 보입니다22
- 이미지는 에러떠서 안보이는 것 같네요..?
  - shared xcconfig에 s3버킷 도메인을 추가해야 합니다. 가빵집 노션에 xcconfigs 문서를 확인해 주세요

2024-08-02 15:17 UTC, zekexros commented on Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionCore.swift
> +        return .send(.backToHome)
그룹 생성 API요청에는 성공하였으나 그룹이 보이지 않는 것은 서버에서 아직 작업이 덜 된 것으로 보입니다.
물론 말씀하신 리프레쉬 작업도 필요한 건 맞습니다. notification 방식과 shared stated 방식 중 어느 것을 선택할지 고민하고 있습니다. 추후 수정할게요

2024-08-02 15:20 UTC, zekexros commented on Projects/Features/Coordinator/CreateGroupCoordinator/CreateGroupCoordinatorCore.swift
카카오톡에서 링크를 클릭하여 앱 딥링크를 통해 그룹에 참여하는 기존 방식에서 초대 코드를 통한 그룹 참여 방식으로 변경됨에 따라 그룹 존재 여부와 상관없이 홈으로 이동하고, 홈 화면에서 그룹 혹은 이벤트 만드는 버튼이 존재하는 걸로 기획이 변경되었습니다.

2024-08-02 16:06 UTC, zekexros commented on Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
> +  }
좋은 생각이에요! CreateGroup과 Main 타겟 등 여러 타겟에서 다양한 파라미터를 받아 프레임에 있는 사진 뷰를 만들 것 같은데 어떻게 분리하면 좋을지 혹시 직접 보여주실 수 있나요?

2024-08-02 16:24 UTC, zekexros commented
<img src="https://github.com/user-attachments/assets/bc4f9a86-d6f5-475f-9247-fcaaf55e4a02" width="200" height="450">

사진의 본래의 비율을 가장 중요하게 생각하는 것은 저도 충분히 공감을 하는데, 구현할 때 위 첨부한 사진과 같이 잘리는게 이상하다고 생각하여 억지로 늘려 프레임에 맞추도록 구현했었습니다. 생각해보니 여백에 백그라운드 색상을 주면 되겠군요. 제 생각이 짧았어용

MVP에선 다크모드를 대응하지 않는다고 결정한 점을 고려하여 프레임의 이미지에 대한 백그라운드 색상은 흰색이 적절하다고 생각하는데 추가 의견이 있으시면 말씀해 주세요

<img src="https://github.com/user-attachments/assets/005a569c-71c9-48db-8172-457aab2e36b7" width="200" height="450">

2024-08-02 22:49 UTC, GREENOVER approved these changes
고생하셨습니다~~
이미지를 자를지 아니면 말씀처럼 백그라운드를 가져갈지 안드로이드는 어떻게하고 있는지와 디자인팀에 어떤 사항을 요구하는지 최종 확인을 해보면 좋을것 같습니다!

2024-08-03 04:22 UTC, hope1053 commented
> 사진의 본래의 비율을 가장 중요하게 생각하는 것은 저도 충분히 공감을 하는데, 구현할 때 위 첨부한 사진과 같이 잘리는게 이상하다고 생각하여 억지로 늘려 프레임에 맞추도록 구현했었습니다. 생각해보니 여백에 백그라운드 색상을 주면 되겠군요. 제 생각이 짧았어용
> 
> MVP에선 다크모드를 대응하지 않는다고 결정한 점을 고려하여 프레임의 이미지에 대한 백그라운드 색상은 흰색이 적절하다고 생각하는데 추가 의견이 있으시면 말씀해 주세요

전에 이 부분 관련해서 프레임에 맞춰서 자르는 방식으로 가자고 논의했던 것 같은데 제 기억도 확실치는 않아서....ㅎㅎ 찬우님 말대로 안드 & 디자인팀과 한 번 더 확인해본 뒤 확정하면 될 것 같습니다~!

2024-08-03 05:02 UTC, hope1053 commented on Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
> +  }
이 부분 저도 작업해야하는 부분이라 머지되면 제가 작업하면서 분리해봐도 될까요? 👀

2024-08-03 05:03 UTC, hope1053 approved these changes
![image](https://github.com/user-attachments/assets/b31140d5-1add-4331-a0dd-f4084329b9e5)

2024-08-03 06:47 UTC, zekexros commented on Projects/Features/Scene/CreateGroupScene/CreateGroupCompletion/CreateGroupCompletionView.swift
> +  }
좋숩니다👍

2024-08-03 08:11 UTC, merged